//----------------------------------------------------------------------------------------------------
// This file is automatically generated.
// 2017/04/01 00:00:00
//----------------------------------------------------------------------------------------------------
#include "cqt.h"
#include "cqt_net.h"

int CQT_InputLayer_if_of(CQT_LAYER *lp, void *inp, void *outp);
int CQT_Conv2D_same_3x3_if_of(CQT_LAYER *lp, void *inp, void *outp);
int CQT_MaxPooling2D_if_of(CQT_LAYER *lp, void *inp, void *outp);
int CQT_Flatten_if_of(CQT_LAYER *lp, void *inp, void *outp);
int CQT_Dense_if_of(CQT_LAYER *lp, void *inp, void *outp);

