//----------------------------------------------------------------------------------------------------
// This file is automatically generated.
// 2017/11/05 00:00:00
//----------------------------------------------------------------------------------------------------
#include "cqt_gen.h"
#include "cqt_lib.h"

int cqt_process;

// cocytus network
CQT_NET g_cqt_sequential_1;

//Layers
LY_InputLayer input_1;
LY_Conv2D conv2d_1;
LY_BatchNormalization batch_normalization_1;
LY_LeakyReLU leaky_re_lu_1;
LY_MaxPooling2D max_pooling2d_1;
LY_Conv2D conv2d_2;
LY_BatchNormalization batch_normalization_2;
LY_LeakyReLU leaky_re_lu_2;
LY_MaxPooling2D max_pooling2d_2;
LY_Conv2D conv2d_3;
LY_BatchNormalization batch_normalization_3;
LY_LeakyReLU leaky_re_lu_3;
LY_MaxPooling2D max_pooling2d_3;
LY_Conv2D conv2d_4;
LY_BatchNormalization batch_normalization_4;
LY_LeakyReLU leaky_re_lu_4;
LY_MaxPooling2D max_pooling2d_4;
LY_Conv2D conv2d_5;
LY_BatchNormalization batch_normalization_5;
LY_LeakyReLU leaky_re_lu_5;
LY_MaxPooling2D max_pooling2d_5;
LY_Conv2D conv2d_6;
LY_BatchNormalization batch_normalization_6;
LY_LeakyReLU leaky_re_lu_6;
LY_MaxPooling2D max_pooling2d_6;
LY_Conv2D conv2d_7;
LY_BatchNormalization batch_normalization_7;
LY_LeakyReLU leaky_re_lu_7;
LY_Conv2D conv2d_8;
LY_BatchNormalization batch_normalization_8;
LY_LeakyReLU leaky_re_lu_8;
LY_Conv2D conv2d_9;

//weights
NUMPY_HEADER nph_conv2d_1_W;
NUMPY_HEADER nph_conv2d_1_b;
float w_conv2d_1_W[16][3][3][3];
float w_conv2d_1_b[16];
NUMPY_HEADER nph_beta_batch_normalization_1_W;
NUMPY_HEADER nph_gamma_batch_normalization_1_W;
NUMPY_HEADER nph_moving_mean_batch_normalization_1_W;
NUMPY_HEADER nph_moving_variance_batch_normalization_1_W;
float beta_batch_normalization_1_W[16];
float gamma_batch_normalization_1_W[16];
float moving_mean_batch_normalization_1_W[16];
float moving_variance_batch_normalization_1_W[16];
NUMPY_HEADER nph_conv2d_2_W;
NUMPY_HEADER nph_conv2d_2_b;
float w_conv2d_2_W[32][16][3][3];
float w_conv2d_2_b[32];
NUMPY_HEADER nph_beta_batch_normalization_2_W;
NUMPY_HEADER nph_gamma_batch_normalization_2_W;
NUMPY_HEADER nph_moving_mean_batch_normalization_2_W;
NUMPY_HEADER nph_moving_variance_batch_normalization_2_W;
float beta_batch_normalization_2_W[32];
float gamma_batch_normalization_2_W[32];
float moving_mean_batch_normalization_2_W[32];
float moving_variance_batch_normalization_2_W[32];
NUMPY_HEADER nph_conv2d_3_W;
NUMPY_HEADER nph_conv2d_3_b;
float w_conv2d_3_W[64][32][3][3];
float w_conv2d_3_b[64];
NUMPY_HEADER nph_beta_batch_normalization_3_W;
NUMPY_HEADER nph_gamma_batch_normalization_3_W;
NUMPY_HEADER nph_moving_mean_batch_normalization_3_W;
NUMPY_HEADER nph_moving_variance_batch_normalization_3_W;
float beta_batch_normalization_3_W[64];
float gamma_batch_normalization_3_W[64];
float moving_mean_batch_normalization_3_W[64];
float moving_variance_batch_normalization_3_W[64];
NUMPY_HEADER nph_conv2d_4_W;
NUMPY_HEADER nph_conv2d_4_b;
float w_conv2d_4_W[128][64][3][3];
float w_conv2d_4_b[128];
NUMPY_HEADER nph_beta_batch_normalization_4_W;
NUMPY_HEADER nph_gamma_batch_normalization_4_W;
NUMPY_HEADER nph_moving_mean_batch_normalization_4_W;
NUMPY_HEADER nph_moving_variance_batch_normalization_4_W;
float beta_batch_normalization_4_W[128];
float gamma_batch_normalization_4_W[128];
float moving_mean_batch_normalization_4_W[128];
float moving_variance_batch_normalization_4_W[128];
NUMPY_HEADER nph_conv2d_5_W;
NUMPY_HEADER nph_conv2d_5_b;
float w_conv2d_5_W[256][128][3][3];
float w_conv2d_5_b[256];
NUMPY_HEADER nph_beta_batch_normalization_5_W;
NUMPY_HEADER nph_gamma_batch_normalization_5_W;
NUMPY_HEADER nph_moving_mean_batch_normalization_5_W;
NUMPY_HEADER nph_moving_variance_batch_normalization_5_W;
float beta_batch_normalization_5_W[256];
float gamma_batch_normalization_5_W[256];
float moving_mean_batch_normalization_5_W[256];
float moving_variance_batch_normalization_5_W[256];
NUMPY_HEADER nph_conv2d_6_W;
NUMPY_HEADER nph_conv2d_6_b;
float w_conv2d_6_W[512][256][3][3];
float w_conv2d_6_b[512];
NUMPY_HEADER nph_beta_batch_normalization_6_W;
NUMPY_HEADER nph_gamma_batch_normalization_6_W;
NUMPY_HEADER nph_moving_mean_batch_normalization_6_W;
NUMPY_HEADER nph_moving_variance_batch_normalization_6_W;
float beta_batch_normalization_6_W[512];
float gamma_batch_normalization_6_W[512];
float moving_mean_batch_normalization_6_W[512];
float moving_variance_batch_normalization_6_W[512];
NUMPY_HEADER nph_conv2d_7_W;
NUMPY_HEADER nph_conv2d_7_b;
float w_conv2d_7_W[1024][512][3][3];
float w_conv2d_7_b[1024];
NUMPY_HEADER nph_beta_batch_normalization_7_W;
NUMPY_HEADER nph_gamma_batch_normalization_7_W;
NUMPY_HEADER nph_moving_mean_batch_normalization_7_W;
NUMPY_HEADER nph_moving_variance_batch_normalization_7_W;
float beta_batch_normalization_7_W[1024];
float gamma_batch_normalization_7_W[1024];
float moving_mean_batch_normalization_7_W[1024];
float moving_variance_batch_normalization_7_W[1024];
NUMPY_HEADER nph_conv2d_8_W;
NUMPY_HEADER nph_conv2d_8_b;
float w_conv2d_8_W[1024][1024][3][3];
float w_conv2d_8_b[1024];
NUMPY_HEADER nph_beta_batch_normalization_8_W;
NUMPY_HEADER nph_gamma_batch_normalization_8_W;
NUMPY_HEADER nph_moving_mean_batch_normalization_8_W;
NUMPY_HEADER nph_moving_variance_batch_normalization_8_W;
float beta_batch_normalization_8_W[1024];
float gamma_batch_normalization_8_W[1024];
float moving_mean_batch_normalization_8_W[1024];
float moving_variance_batch_normalization_8_W[1024];
NUMPY_HEADER nph_conv2d_9_W;
NUMPY_HEADER nph_conv2d_9_b;
float w_conv2d_9_W[125][1024][1][1];
float w_conv2d_9_b[125];

//outputs
float input_1_output[3][416+NEON_VTR*3][NEON_HTR+416+NEON_HPADDING_0];
float conv2d_1_output[16][416+NEON_VTR*3][NEON_HTR+416+NEON_HPADDING_0];
float batch_normalization_1_output[16][416+NEON_VTR*3][NEON_HTR+416+NEON_HPADDING_0];
float leaky_re_lu_1_output[16][416+NEON_VTR*3][NEON_HTR+416+NEON_HPADDING_0];
float max_pooling2d_1_output[16][208+NEON_VTR*3][NEON_HTR+208+NEON_HPADDING_0];
float conv2d_2_output[32][208+NEON_VTR*3][NEON_HTR+208+NEON_HPADDING_0];
float batch_normalization_2_output[32][208+NEON_VTR*3][NEON_HTR+208+NEON_HPADDING_0];
float leaky_re_lu_2_output[32][208+NEON_VTR*3][NEON_HTR+208+NEON_HPADDING_0];
float max_pooling2d_2_output[32][104+NEON_VTR*3][NEON_HTR+104+NEON_HPADDING_0];
float conv2d_3_output[64][104+NEON_VTR*3][NEON_HTR+104+NEON_HPADDING_0];
float batch_normalization_3_output[64][104+NEON_VTR*3][NEON_HTR+104+NEON_HPADDING_0];
float leaky_re_lu_3_output[64][104+NEON_VTR*3][NEON_HTR+104+NEON_HPADDING_0];
float max_pooling2d_3_output[64][52+NEON_VTR*3][NEON_HTR+52+NEON_HPADDING_0];
float conv2d_4_output[128][52+NEON_VTR*3][NEON_HTR+52+NEON_HPADDING_0];
float batch_normalization_4_output[128][52+NEON_VTR*3][NEON_HTR+52+NEON_HPADDING_0];
float leaky_re_lu_4_output[128][52+NEON_VTR*3][NEON_HTR+52+NEON_HPADDING_0];
float max_pooling2d_4_output[128][26+NEON_VTR*3][NEON_HTR+26+NEON_HPADDING_2];
float conv2d_5_output[256][26+NEON_VTR*3][NEON_HTR+26+NEON_HPADDING_2];
float batch_normalization_5_output[256][26+NEON_VTR*3][NEON_HTR+26+NEON_HPADDING_2];
float leaky_re_lu_5_output[256][26+NEON_VTR*3][NEON_HTR+26+NEON_HPADDING_2];
float max_pooling2d_5_output[256][13+NEON_VTR*3][NEON_HTR+13+NEON_HPADDING_3];
float conv2d_6_output[512][13+NEON_VTR*3][NEON_HTR+13+NEON_HPADDING_3];
float batch_normalization_6_output[512][13+NEON_VTR*3][NEON_HTR+13+NEON_HPADDING_3];
float leaky_re_lu_6_output[512][13+NEON_VTR*3][NEON_HTR+13+NEON_HPADDING_3];
float max_pooling2d_6_output[512][13+NEON_VTR*3][NEON_HTR+13+NEON_HPADDING_3];
float conv2d_7_output[1024][13+NEON_VTR*3][NEON_HTR+13+NEON_HPADDING_3];
float batch_normalization_7_output[1024][13+NEON_VTR*3][NEON_HTR+13+NEON_HPADDING_3];
float leaky_re_lu_7_output[1024][13+NEON_VTR*3][NEON_HTR+13+NEON_HPADDING_3];
float conv2d_8_output[1024][13+NEON_VTR*3][NEON_HTR+13+NEON_HPADDING_3];
float batch_normalization_8_output[1024][13+NEON_VTR*3][NEON_HTR+13+NEON_HPADDING_3];
float leaky_re_lu_8_output[1024][13+NEON_VTR*3][NEON_HTR+13+NEON_HPADDING_3];
float conv2d_9_output[125][13+NEON_VTR*3][NEON_HTR+13+NEON_HPADDING_3];

CQT_NET* cqt_init(void) {
	g_cqt_sequential_1.layernum = 32;
	cqt_process = 0;

	strcpy(g_cqt_sequential_1.layer[0].name, "input_1");
	g_cqt_sequential_1.layer[0].type = LT_InputLayer;
	g_cqt_sequential_1.layer[0].input_dtypes[0] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[0].input_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[0].input_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[0].input_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[0].weight_dtypes[0] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[0].weight_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[0].weight_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[0].weight_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[0].output_dtypes[0] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[0].output_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[0].output_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[0].output_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[0].cqt_input_shape[0] = 0;
	g_cqt_sequential_1.layer[0].cqt_input_shape[1] = 416;
	g_cqt_sequential_1.layer[0].cqt_input_shape[2] = 416;
	g_cqt_sequential_1.layer[0].cqt_input_shape[3] = 3;
	g_cqt_sequential_1.layer[0].cqt_output_shape[0] = 0;
	g_cqt_sequential_1.layer[0].cqt_output_shape[1] = 416;
	g_cqt_sequential_1.layer[0].cqt_output_shape[2] = 416;
	g_cqt_sequential_1.layer[0].cqt_output_shape[3] = 3;
	g_cqt_sequential_1.layer[0].input_q = 8;
	g_cqt_sequential_1.layer[0].weight_q = 8;
	g_cqt_sequential_1.layer[0].output_q = 8;
	g_cqt_sequential_1.layer[0].overflow_cnt = 0;
	g_cqt_sequential_1.layer[0].neon_padding_hi = NEON_HPADDING_0;
	g_cqt_sequential_1.layer[0].neon_padding_ho = NEON_HPADDING_0;
	g_cqt_sequential_1.layer[0].param_p = &input_1;
	g_cqt_sequential_1.layer[0].data_p = &input_1_output;

	strcpy(g_cqt_sequential_1.layer[1].name, "conv2d_1");
	g_cqt_sequential_1.layer[1].type = LT_Conv2D;
	conv2d_1.filters = 16;
	conv2d_1.kernel_size[0] = 3;
	conv2d_1.kernel_size[1] = 3;
	conv2d_1.strides[0] = 1;
	conv2d_1.strides[1] = 1;
	conv2d_1.padding = PD_SAME;
	conv2d_1.data_format = DF_CHANNELS_LAST;
	conv2d_1.dilation_rate[0] = 1;
	conv2d_1.dilation_rate[1] = 1;
	conv2d_1.activation = ACT_LINEAR;
	conv2d_1.use_bias = false;
	conv2d_1.weight_np_header_p = &nph_conv2d_1_W;
	conv2d_1.weight_p = &w_conv2d_1_W;
	conv2d_1.bias_np_header_p = &nph_conv2d_1_b;
	conv2d_1.bias_p = &w_conv2d_1_b;
	g_cqt_sequential_1.layer[1].input_dtypes[0] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[1].input_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[1].input_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[1].input_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[1].weight_dtypes[0] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[1].weight_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[1].weight_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[1].weight_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[1].output_dtypes[0] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[1].output_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[1].output_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[1].output_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[1].cqt_input_shape[0] = 0;
	g_cqt_sequential_1.layer[1].cqt_input_shape[1] = 416;
	g_cqt_sequential_1.layer[1].cqt_input_shape[2] = 416;
	g_cqt_sequential_1.layer[1].cqt_input_shape[3] = 3;
	g_cqt_sequential_1.layer[1].cqt_output_shape[0] = 0;
	g_cqt_sequential_1.layer[1].cqt_output_shape[1] = 416;
	g_cqt_sequential_1.layer[1].cqt_output_shape[2] = 416;
	g_cqt_sequential_1.layer[1].cqt_output_shape[3] = 16;
	g_cqt_sequential_1.layer[1].input_q = 8;
	g_cqt_sequential_1.layer[1].weight_q = 8;
	g_cqt_sequential_1.layer[1].output_q = 8;
	g_cqt_sequential_1.layer[1].overflow_cnt = 0;
	g_cqt_sequential_1.layer[1].neon_padding_hi = NEON_HPADDING_0;
	g_cqt_sequential_1.layer[1].neon_padding_ho = NEON_HPADDING_0;
	g_cqt_sequential_1.layer[1].param_p = &conv2d_1;
	g_cqt_sequential_1.layer[1].data_p = &conv2d_1_output;

	strcpy(g_cqt_sequential_1.layer[2].name, "batch_normalization_1");
	g_cqt_sequential_1.layer[2].type = LT_BatchNormalization;
	batch_normalization_1.axis = -1;
	batch_normalization_1.momentum = 0.99;
	batch_normalization_1.epsilon = 0.001;
	batch_normalization_1.center = true;
	batch_normalization_1.scale = true;
	batch_normalization_1.beta_np_header_p = &nph_beta_batch_normalization_1_W;
	batch_normalization_1.beta_p = &beta_batch_normalization_1_W;
	batch_normalization_1.gamma_np_header_p = &nph_gamma_batch_normalization_1_W;
	batch_normalization_1.gamma_p = &gamma_batch_normalization_1_W;
	batch_normalization_1.moving_mean_np_header_p = &nph_moving_mean_batch_normalization_1_W;
	batch_normalization_1.moving_mean_p = &moving_mean_batch_normalization_1_W;
	batch_normalization_1.moving_variance_np_header_p = &nph_moving_variance_batch_normalization_1_W;
	batch_normalization_1.moving_variance_p = &moving_variance_batch_normalization_1_W;
	g_cqt_sequential_1.layer[2].input_dtypes[0] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[2].input_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[2].input_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[2].input_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[2].weight_dtypes[0] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[2].weight_dtypes[1] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[2].weight_dtypes[2] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[2].weight_dtypes[3] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[2].output_dtypes[0] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[2].output_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[2].output_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[2].output_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[2].cqt_input_shape[0] = 0;
	g_cqt_sequential_1.layer[2].cqt_input_shape[1] = 416;
	g_cqt_sequential_1.layer[2].cqt_input_shape[2] = 416;
	g_cqt_sequential_1.layer[2].cqt_input_shape[3] = 16;
	g_cqt_sequential_1.layer[2].cqt_output_shape[0] = 0;
	g_cqt_sequential_1.layer[2].cqt_output_shape[1] = 416;
	g_cqt_sequential_1.layer[2].cqt_output_shape[2] = 416;
	g_cqt_sequential_1.layer[2].cqt_output_shape[3] = 16;
	g_cqt_sequential_1.layer[2].input_q = 8;
	g_cqt_sequential_1.layer[2].weight_q = 8;
	g_cqt_sequential_1.layer[2].output_q = 8;
	g_cqt_sequential_1.layer[2].overflow_cnt = 0;
	g_cqt_sequential_1.layer[2].neon_padding_hi = NEON_HPADDING_0;
	g_cqt_sequential_1.layer[2].neon_padding_ho = NEON_HPADDING_0;
	g_cqt_sequential_1.layer[2].param_p = &batch_normalization_1;
	g_cqt_sequential_1.layer[2].data_p = &batch_normalization_1_output;

	strcpy(g_cqt_sequential_1.layer[3].name, "leaky_re_lu_1");
	g_cqt_sequential_1.layer[3].type = LT_LeakyReLU;
	leaky_re_lu_1.alpha = 0.10000000149011612;
	g_cqt_sequential_1.layer[3].input_dtypes[0] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[3].input_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[3].input_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[3].input_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[3].weight_dtypes[0] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[3].weight_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[3].weight_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[3].weight_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[3].output_dtypes[0] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[3].output_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[3].output_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[3].output_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[3].cqt_input_shape[0] = 0;
	g_cqt_sequential_1.layer[3].cqt_input_shape[1] = 416;
	g_cqt_sequential_1.layer[3].cqt_input_shape[2] = 416;
	g_cqt_sequential_1.layer[3].cqt_input_shape[3] = 16;
	g_cqt_sequential_1.layer[3].cqt_output_shape[0] = 0;
	g_cqt_sequential_1.layer[3].cqt_output_shape[1] = 416;
	g_cqt_sequential_1.layer[3].cqt_output_shape[2] = 416;
	g_cqt_sequential_1.layer[3].cqt_output_shape[3] = 16;
	g_cqt_sequential_1.layer[3].input_q = 8;
	g_cqt_sequential_1.layer[3].weight_q = 8;
	g_cqt_sequential_1.layer[3].output_q = 8;
	g_cqt_sequential_1.layer[3].overflow_cnt = 0;
	g_cqt_sequential_1.layer[3].neon_padding_hi = NEON_HPADDING_0;
	g_cqt_sequential_1.layer[3].neon_padding_ho = NEON_HPADDING_0;
	g_cqt_sequential_1.layer[3].param_p = &leaky_re_lu_1;
	g_cqt_sequential_1.layer[3].data_p = &leaky_re_lu_1_output;

	strcpy(g_cqt_sequential_1.layer[4].name, "max_pooling2d_1");
	g_cqt_sequential_1.layer[4].type = LT_MaxPooling2D;
	max_pooling2d_1.strides[0] = 2;
	max_pooling2d_1.strides[1] = 2;
	max_pooling2d_1.padding = PD_SAME;
	max_pooling2d_1.data_format = DF_CHANNELS_LAST;
	max_pooling2d_1.pool_size[0] = 2;
	max_pooling2d_1.pool_size[1] = 2;
	g_cqt_sequential_1.layer[4].input_dtypes[0] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[4].input_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[4].input_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[4].input_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[4].weight_dtypes[0] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[4].weight_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[4].weight_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[4].weight_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[4].output_dtypes[0] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[4].output_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[4].output_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[4].output_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[4].cqt_input_shape[0] = 0;
	g_cqt_sequential_1.layer[4].cqt_input_shape[1] = 416;
	g_cqt_sequential_1.layer[4].cqt_input_shape[2] = 416;
	g_cqt_sequential_1.layer[4].cqt_input_shape[3] = 16;
	g_cqt_sequential_1.layer[4].cqt_output_shape[0] = 0;
	g_cqt_sequential_1.layer[4].cqt_output_shape[1] = 208;
	g_cqt_sequential_1.layer[4].cqt_output_shape[2] = 208;
	g_cqt_sequential_1.layer[4].cqt_output_shape[3] = 16;
	g_cqt_sequential_1.layer[4].input_q = 8;
	g_cqt_sequential_1.layer[4].weight_q = 8;
	g_cqt_sequential_1.layer[4].output_q = 8;
	g_cqt_sequential_1.layer[4].overflow_cnt = 0;
	g_cqt_sequential_1.layer[4].neon_padding_hi = NEON_HPADDING_0;
	g_cqt_sequential_1.layer[4].neon_padding_ho = NEON_HPADDING_0;
	g_cqt_sequential_1.layer[4].param_p = &max_pooling2d_1;
	g_cqt_sequential_1.layer[4].data_p = &max_pooling2d_1_output;

	strcpy(g_cqt_sequential_1.layer[5].name, "conv2d_2");
	g_cqt_sequential_1.layer[5].type = LT_Conv2D;
	conv2d_2.filters = 32;
	conv2d_2.kernel_size[0] = 3;
	conv2d_2.kernel_size[1] = 3;
	conv2d_2.strides[0] = 1;
	conv2d_2.strides[1] = 1;
	conv2d_2.padding = PD_SAME;
	conv2d_2.data_format = DF_CHANNELS_LAST;
	conv2d_2.dilation_rate[0] = 1;
	conv2d_2.dilation_rate[1] = 1;
	conv2d_2.activation = ACT_LINEAR;
	conv2d_2.use_bias = false;
	conv2d_2.weight_np_header_p = &nph_conv2d_2_W;
	conv2d_2.weight_p = &w_conv2d_2_W;
	conv2d_2.bias_np_header_p = &nph_conv2d_2_b;
	conv2d_2.bias_p = &w_conv2d_2_b;
	g_cqt_sequential_1.layer[5].input_dtypes[0] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[5].input_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[5].input_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[5].input_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[5].weight_dtypes[0] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[5].weight_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[5].weight_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[5].weight_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[5].output_dtypes[0] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[5].output_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[5].output_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[5].output_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[5].cqt_input_shape[0] = 0;
	g_cqt_sequential_1.layer[5].cqt_input_shape[1] = 208;
	g_cqt_sequential_1.layer[5].cqt_input_shape[2] = 208;
	g_cqt_sequential_1.layer[5].cqt_input_shape[3] = 16;
	g_cqt_sequential_1.layer[5].cqt_output_shape[0] = 0;
	g_cqt_sequential_1.layer[5].cqt_output_shape[1] = 208;
	g_cqt_sequential_1.layer[5].cqt_output_shape[2] = 208;
	g_cqt_sequential_1.layer[5].cqt_output_shape[3] = 32;
	g_cqt_sequential_1.layer[5].input_q = 8;
	g_cqt_sequential_1.layer[5].weight_q = 8;
	g_cqt_sequential_1.layer[5].output_q = 8;
	g_cqt_sequential_1.layer[5].overflow_cnt = 0;
	g_cqt_sequential_1.layer[5].neon_padding_hi = NEON_HPADDING_0;
	g_cqt_sequential_1.layer[5].neon_padding_ho = NEON_HPADDING_0;
	g_cqt_sequential_1.layer[5].param_p = &conv2d_2;
	g_cqt_sequential_1.layer[5].data_p = &conv2d_2_output;

	strcpy(g_cqt_sequential_1.layer[6].name, "batch_normalization_2");
	g_cqt_sequential_1.layer[6].type = LT_BatchNormalization;
	batch_normalization_2.axis = -1;
	batch_normalization_2.momentum = 0.99;
	batch_normalization_2.epsilon = 0.001;
	batch_normalization_2.center = true;
	batch_normalization_2.scale = true;
	batch_normalization_2.beta_np_header_p = &nph_beta_batch_normalization_2_W;
	batch_normalization_2.beta_p = &beta_batch_normalization_2_W;
	batch_normalization_2.gamma_np_header_p = &nph_gamma_batch_normalization_2_W;
	batch_normalization_2.gamma_p = &gamma_batch_normalization_2_W;
	batch_normalization_2.moving_mean_np_header_p = &nph_moving_mean_batch_normalization_2_W;
	batch_normalization_2.moving_mean_p = &moving_mean_batch_normalization_2_W;
	batch_normalization_2.moving_variance_np_header_p = &nph_moving_variance_batch_normalization_2_W;
	batch_normalization_2.moving_variance_p = &moving_variance_batch_normalization_2_W;
	g_cqt_sequential_1.layer[6].input_dtypes[0] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[6].input_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[6].input_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[6].input_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[6].weight_dtypes[0] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[6].weight_dtypes[1] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[6].weight_dtypes[2] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[6].weight_dtypes[3] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[6].output_dtypes[0] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[6].output_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[6].output_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[6].output_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[6].cqt_input_shape[0] = 0;
	g_cqt_sequential_1.layer[6].cqt_input_shape[1] = 208;
	g_cqt_sequential_1.layer[6].cqt_input_shape[2] = 208;
	g_cqt_sequential_1.layer[6].cqt_input_shape[3] = 32;
	g_cqt_sequential_1.layer[6].cqt_output_shape[0] = 0;
	g_cqt_sequential_1.layer[6].cqt_output_shape[1] = 208;
	g_cqt_sequential_1.layer[6].cqt_output_shape[2] = 208;
	g_cqt_sequential_1.layer[6].cqt_output_shape[3] = 32;
	g_cqt_sequential_1.layer[6].input_q = 8;
	g_cqt_sequential_1.layer[6].weight_q = 8;
	g_cqt_sequential_1.layer[6].output_q = 8;
	g_cqt_sequential_1.layer[6].overflow_cnt = 0;
	g_cqt_sequential_1.layer[6].neon_padding_hi = NEON_HPADDING_0;
	g_cqt_sequential_1.layer[6].neon_padding_ho = NEON_HPADDING_0;
	g_cqt_sequential_1.layer[6].param_p = &batch_normalization_2;
	g_cqt_sequential_1.layer[6].data_p = &batch_normalization_2_output;

	strcpy(g_cqt_sequential_1.layer[7].name, "leaky_re_lu_2");
	g_cqt_sequential_1.layer[7].type = LT_LeakyReLU;
	leaky_re_lu_2.alpha = 0.10000000149011612;
	g_cqt_sequential_1.layer[7].input_dtypes[0] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[7].input_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[7].input_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[7].input_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[7].weight_dtypes[0] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[7].weight_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[7].weight_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[7].weight_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[7].output_dtypes[0] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[7].output_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[7].output_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[7].output_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[7].cqt_input_shape[0] = 0;
	g_cqt_sequential_1.layer[7].cqt_input_shape[1] = 208;
	g_cqt_sequential_1.layer[7].cqt_input_shape[2] = 208;
	g_cqt_sequential_1.layer[7].cqt_input_shape[3] = 32;
	g_cqt_sequential_1.layer[7].cqt_output_shape[0] = 0;
	g_cqt_sequential_1.layer[7].cqt_output_shape[1] = 208;
	g_cqt_sequential_1.layer[7].cqt_output_shape[2] = 208;
	g_cqt_sequential_1.layer[7].cqt_output_shape[3] = 32;
	g_cqt_sequential_1.layer[7].input_q = 8;
	g_cqt_sequential_1.layer[7].weight_q = 8;
	g_cqt_sequential_1.layer[7].output_q = 8;
	g_cqt_sequential_1.layer[7].overflow_cnt = 0;
	g_cqt_sequential_1.layer[7].neon_padding_hi = NEON_HPADDING_0;
	g_cqt_sequential_1.layer[7].neon_padding_ho = NEON_HPADDING_0;
	g_cqt_sequential_1.layer[7].param_p = &leaky_re_lu_2;
	g_cqt_sequential_1.layer[7].data_p = &leaky_re_lu_2_output;

	strcpy(g_cqt_sequential_1.layer[8].name, "max_pooling2d_2");
	g_cqt_sequential_1.layer[8].type = LT_MaxPooling2D;
	max_pooling2d_2.strides[0] = 2;
	max_pooling2d_2.strides[1] = 2;
	max_pooling2d_2.padding = PD_SAME;
	max_pooling2d_2.data_format = DF_CHANNELS_LAST;
	max_pooling2d_2.pool_size[0] = 2;
	max_pooling2d_2.pool_size[1] = 2;
	g_cqt_sequential_1.layer[8].input_dtypes[0] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[8].input_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[8].input_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[8].input_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[8].weight_dtypes[0] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[8].weight_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[8].weight_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[8].weight_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[8].output_dtypes[0] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[8].output_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[8].output_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[8].output_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[8].cqt_input_shape[0] = 0;
	g_cqt_sequential_1.layer[8].cqt_input_shape[1] = 208;
	g_cqt_sequential_1.layer[8].cqt_input_shape[2] = 208;
	g_cqt_sequential_1.layer[8].cqt_input_shape[3] = 32;
	g_cqt_sequential_1.layer[8].cqt_output_shape[0] = 0;
	g_cqt_sequential_1.layer[8].cqt_output_shape[1] = 104;
	g_cqt_sequential_1.layer[8].cqt_output_shape[2] = 104;
	g_cqt_sequential_1.layer[8].cqt_output_shape[3] = 32;
	g_cqt_sequential_1.layer[8].input_q = 8;
	g_cqt_sequential_1.layer[8].weight_q = 8;
	g_cqt_sequential_1.layer[8].output_q = 8;
	g_cqt_sequential_1.layer[8].overflow_cnt = 0;
	g_cqt_sequential_1.layer[8].neon_padding_hi = NEON_HPADDING_0;
	g_cqt_sequential_1.layer[8].neon_padding_ho = NEON_HPADDING_0;
	g_cqt_sequential_1.layer[8].param_p = &max_pooling2d_2;
	g_cqt_sequential_1.layer[8].data_p = &max_pooling2d_2_output;

	strcpy(g_cqt_sequential_1.layer[9].name, "conv2d_3");
	g_cqt_sequential_1.layer[9].type = LT_Conv2D;
	conv2d_3.filters = 64;
	conv2d_3.kernel_size[0] = 3;
	conv2d_3.kernel_size[1] = 3;
	conv2d_3.strides[0] = 1;
	conv2d_3.strides[1] = 1;
	conv2d_3.padding = PD_SAME;
	conv2d_3.data_format = DF_CHANNELS_LAST;
	conv2d_3.dilation_rate[0] = 1;
	conv2d_3.dilation_rate[1] = 1;
	conv2d_3.activation = ACT_LINEAR;
	conv2d_3.use_bias = false;
	conv2d_3.weight_np_header_p = &nph_conv2d_3_W;
	conv2d_3.weight_p = &w_conv2d_3_W;
	conv2d_3.bias_np_header_p = &nph_conv2d_3_b;
	conv2d_3.bias_p = &w_conv2d_3_b;
	g_cqt_sequential_1.layer[9].input_dtypes[0] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[9].input_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[9].input_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[9].input_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[9].weight_dtypes[0] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[9].weight_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[9].weight_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[9].weight_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[9].output_dtypes[0] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[9].output_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[9].output_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[9].output_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[9].cqt_input_shape[0] = 0;
	g_cqt_sequential_1.layer[9].cqt_input_shape[1] = 104;
	g_cqt_sequential_1.layer[9].cqt_input_shape[2] = 104;
	g_cqt_sequential_1.layer[9].cqt_input_shape[3] = 32;
	g_cqt_sequential_1.layer[9].cqt_output_shape[0] = 0;
	g_cqt_sequential_1.layer[9].cqt_output_shape[1] = 104;
	g_cqt_sequential_1.layer[9].cqt_output_shape[2] = 104;
	g_cqt_sequential_1.layer[9].cqt_output_shape[3] = 64;
	g_cqt_sequential_1.layer[9].input_q = 8;
	g_cqt_sequential_1.layer[9].weight_q = 8;
	g_cqt_sequential_1.layer[9].output_q = 8;
	g_cqt_sequential_1.layer[9].overflow_cnt = 0;
	g_cqt_sequential_1.layer[9].neon_padding_hi = NEON_HPADDING_0;
	g_cqt_sequential_1.layer[9].neon_padding_ho = NEON_HPADDING_0;
	g_cqt_sequential_1.layer[9].param_p = &conv2d_3;
	g_cqt_sequential_1.layer[9].data_p = &conv2d_3_output;

	strcpy(g_cqt_sequential_1.layer[10].name, "batch_normalization_3");
	g_cqt_sequential_1.layer[10].type = LT_BatchNormalization;
	batch_normalization_3.axis = -1;
	batch_normalization_3.momentum = 0.99;
	batch_normalization_3.epsilon = 0.001;
	batch_normalization_3.center = true;
	batch_normalization_3.scale = true;
	batch_normalization_3.beta_np_header_p = &nph_beta_batch_normalization_3_W;
	batch_normalization_3.beta_p = &beta_batch_normalization_3_W;
	batch_normalization_3.gamma_np_header_p = &nph_gamma_batch_normalization_3_W;
	batch_normalization_3.gamma_p = &gamma_batch_normalization_3_W;
	batch_normalization_3.moving_mean_np_header_p = &nph_moving_mean_batch_normalization_3_W;
	batch_normalization_3.moving_mean_p = &moving_mean_batch_normalization_3_W;
	batch_normalization_3.moving_variance_np_header_p = &nph_moving_variance_batch_normalization_3_W;
	batch_normalization_3.moving_variance_p = &moving_variance_batch_normalization_3_W;
	g_cqt_sequential_1.layer[10].input_dtypes[0] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[10].input_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[10].input_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[10].input_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[10].weight_dtypes[0] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[10].weight_dtypes[1] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[10].weight_dtypes[2] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[10].weight_dtypes[3] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[10].output_dtypes[0] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[10].output_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[10].output_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[10].output_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[10].cqt_input_shape[0] = 0;
	g_cqt_sequential_1.layer[10].cqt_input_shape[1] = 104;
	g_cqt_sequential_1.layer[10].cqt_input_shape[2] = 104;
	g_cqt_sequential_1.layer[10].cqt_input_shape[3] = 64;
	g_cqt_sequential_1.layer[10].cqt_output_shape[0] = 0;
	g_cqt_sequential_1.layer[10].cqt_output_shape[1] = 104;
	g_cqt_sequential_1.layer[10].cqt_output_shape[2] = 104;
	g_cqt_sequential_1.layer[10].cqt_output_shape[3] = 64;
	g_cqt_sequential_1.layer[10].input_q = 8;
	g_cqt_sequential_1.layer[10].weight_q = 8;
	g_cqt_sequential_1.layer[10].output_q = 8;
	g_cqt_sequential_1.layer[10].overflow_cnt = 0;
	g_cqt_sequential_1.layer[10].neon_padding_hi = NEON_HPADDING_0;
	g_cqt_sequential_1.layer[10].neon_padding_ho = NEON_HPADDING_0;
	g_cqt_sequential_1.layer[10].param_p = &batch_normalization_3;
	g_cqt_sequential_1.layer[10].data_p = &batch_normalization_3_output;

	strcpy(g_cqt_sequential_1.layer[11].name, "leaky_re_lu_3");
	g_cqt_sequential_1.layer[11].type = LT_LeakyReLU;
	leaky_re_lu_3.alpha = 0.10000000149011612;
	g_cqt_sequential_1.layer[11].input_dtypes[0] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[11].input_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[11].input_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[11].input_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[11].weight_dtypes[0] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[11].weight_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[11].weight_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[11].weight_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[11].output_dtypes[0] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[11].output_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[11].output_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[11].output_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[11].cqt_input_shape[0] = 0;
	g_cqt_sequential_1.layer[11].cqt_input_shape[1] = 104;
	g_cqt_sequential_1.layer[11].cqt_input_shape[2] = 104;
	g_cqt_sequential_1.layer[11].cqt_input_shape[3] = 64;
	g_cqt_sequential_1.layer[11].cqt_output_shape[0] = 0;
	g_cqt_sequential_1.layer[11].cqt_output_shape[1] = 104;
	g_cqt_sequential_1.layer[11].cqt_output_shape[2] = 104;
	g_cqt_sequential_1.layer[11].cqt_output_shape[3] = 64;
	g_cqt_sequential_1.layer[11].input_q = 8;
	g_cqt_sequential_1.layer[11].weight_q = 8;
	g_cqt_sequential_1.layer[11].output_q = 8;
	g_cqt_sequential_1.layer[11].overflow_cnt = 0;
	g_cqt_sequential_1.layer[11].neon_padding_hi = NEON_HPADDING_0;
	g_cqt_sequential_1.layer[11].neon_padding_ho = NEON_HPADDING_0;
	g_cqt_sequential_1.layer[11].param_p = &leaky_re_lu_3;
	g_cqt_sequential_1.layer[11].data_p = &leaky_re_lu_3_output;

	strcpy(g_cqt_sequential_1.layer[12].name, "max_pooling2d_3");
	g_cqt_sequential_1.layer[12].type = LT_MaxPooling2D;
	max_pooling2d_3.strides[0] = 2;
	max_pooling2d_3.strides[1] = 2;
	max_pooling2d_3.padding = PD_SAME;
	max_pooling2d_3.data_format = DF_CHANNELS_LAST;
	max_pooling2d_3.pool_size[0] = 2;
	max_pooling2d_3.pool_size[1] = 2;
	g_cqt_sequential_1.layer[12].input_dtypes[0] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[12].input_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[12].input_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[12].input_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[12].weight_dtypes[0] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[12].weight_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[12].weight_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[12].weight_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[12].output_dtypes[0] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[12].output_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[12].output_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[12].output_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[12].cqt_input_shape[0] = 0;
	g_cqt_sequential_1.layer[12].cqt_input_shape[1] = 104;
	g_cqt_sequential_1.layer[12].cqt_input_shape[2] = 104;
	g_cqt_sequential_1.layer[12].cqt_input_shape[3] = 64;
	g_cqt_sequential_1.layer[12].cqt_output_shape[0] = 0;
	g_cqt_sequential_1.layer[12].cqt_output_shape[1] = 52;
	g_cqt_sequential_1.layer[12].cqt_output_shape[2] = 52;
	g_cqt_sequential_1.layer[12].cqt_output_shape[3] = 64;
	g_cqt_sequential_1.layer[12].input_q = 8;
	g_cqt_sequential_1.layer[12].weight_q = 8;
	g_cqt_sequential_1.layer[12].output_q = 8;
	g_cqt_sequential_1.layer[12].overflow_cnt = 0;
	g_cqt_sequential_1.layer[12].neon_padding_hi = NEON_HPADDING_0;
	g_cqt_sequential_1.layer[12].neon_padding_ho = NEON_HPADDING_0;
	g_cqt_sequential_1.layer[12].param_p = &max_pooling2d_3;
	g_cqt_sequential_1.layer[12].data_p = &max_pooling2d_3_output;

	strcpy(g_cqt_sequential_1.layer[13].name, "conv2d_4");
	g_cqt_sequential_1.layer[13].type = LT_Conv2D;
	conv2d_4.filters = 128;
	conv2d_4.kernel_size[0] = 3;
	conv2d_4.kernel_size[1] = 3;
	conv2d_4.strides[0] = 1;
	conv2d_4.strides[1] = 1;
	conv2d_4.padding = PD_SAME;
	conv2d_4.data_format = DF_CHANNELS_LAST;
	conv2d_4.dilation_rate[0] = 1;
	conv2d_4.dilation_rate[1] = 1;
	conv2d_4.activation = ACT_LINEAR;
	conv2d_4.use_bias = false;
	conv2d_4.weight_np_header_p = &nph_conv2d_4_W;
	conv2d_4.weight_p = &w_conv2d_4_W;
	conv2d_4.bias_np_header_p = &nph_conv2d_4_b;
	conv2d_4.bias_p = &w_conv2d_4_b;
	g_cqt_sequential_1.layer[13].input_dtypes[0] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[13].input_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[13].input_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[13].input_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[13].weight_dtypes[0] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[13].weight_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[13].weight_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[13].weight_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[13].output_dtypes[0] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[13].output_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[13].output_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[13].output_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[13].cqt_input_shape[0] = 0;
	g_cqt_sequential_1.layer[13].cqt_input_shape[1] = 52;
	g_cqt_sequential_1.layer[13].cqt_input_shape[2] = 52;
	g_cqt_sequential_1.layer[13].cqt_input_shape[3] = 64;
	g_cqt_sequential_1.layer[13].cqt_output_shape[0] = 0;
	g_cqt_sequential_1.layer[13].cqt_output_shape[1] = 52;
	g_cqt_sequential_1.layer[13].cqt_output_shape[2] = 52;
	g_cqt_sequential_1.layer[13].cqt_output_shape[3] = 128;
	g_cqt_sequential_1.layer[13].input_q = 8;
	g_cqt_sequential_1.layer[13].weight_q = 8;
	g_cqt_sequential_1.layer[13].output_q = 8;
	g_cqt_sequential_1.layer[13].overflow_cnt = 0;
	g_cqt_sequential_1.layer[13].neon_padding_hi = NEON_HPADDING_0;
	g_cqt_sequential_1.layer[13].neon_padding_ho = NEON_HPADDING_0;
	g_cqt_sequential_1.layer[13].param_p = &conv2d_4;
	g_cqt_sequential_1.layer[13].data_p = &conv2d_4_output;

	strcpy(g_cqt_sequential_1.layer[14].name, "batch_normalization_4");
	g_cqt_sequential_1.layer[14].type = LT_BatchNormalization;
	batch_normalization_4.axis = -1;
	batch_normalization_4.momentum = 0.99;
	batch_normalization_4.epsilon = 0.001;
	batch_normalization_4.center = true;
	batch_normalization_4.scale = true;
	batch_normalization_4.beta_np_header_p = &nph_beta_batch_normalization_4_W;
	batch_normalization_4.beta_p = &beta_batch_normalization_4_W;
	batch_normalization_4.gamma_np_header_p = &nph_gamma_batch_normalization_4_W;
	batch_normalization_4.gamma_p = &gamma_batch_normalization_4_W;
	batch_normalization_4.moving_mean_np_header_p = &nph_moving_mean_batch_normalization_4_W;
	batch_normalization_4.moving_mean_p = &moving_mean_batch_normalization_4_W;
	batch_normalization_4.moving_variance_np_header_p = &nph_moving_variance_batch_normalization_4_W;
	batch_normalization_4.moving_variance_p = &moving_variance_batch_normalization_4_W;
	g_cqt_sequential_1.layer[14].input_dtypes[0] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[14].input_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[14].input_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[14].input_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[14].weight_dtypes[0] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[14].weight_dtypes[1] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[14].weight_dtypes[2] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[14].weight_dtypes[3] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[14].output_dtypes[0] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[14].output_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[14].output_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[14].output_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[14].cqt_input_shape[0] = 0;
	g_cqt_sequential_1.layer[14].cqt_input_shape[1] = 52;
	g_cqt_sequential_1.layer[14].cqt_input_shape[2] = 52;
	g_cqt_sequential_1.layer[14].cqt_input_shape[3] = 128;
	g_cqt_sequential_1.layer[14].cqt_output_shape[0] = 0;
	g_cqt_sequential_1.layer[14].cqt_output_shape[1] = 52;
	g_cqt_sequential_1.layer[14].cqt_output_shape[2] = 52;
	g_cqt_sequential_1.layer[14].cqt_output_shape[3] = 128;
	g_cqt_sequential_1.layer[14].input_q = 8;
	g_cqt_sequential_1.layer[14].weight_q = 8;
	g_cqt_sequential_1.layer[14].output_q = 8;
	g_cqt_sequential_1.layer[14].overflow_cnt = 0;
	g_cqt_sequential_1.layer[14].neon_padding_hi = NEON_HPADDING_0;
	g_cqt_sequential_1.layer[14].neon_padding_ho = NEON_HPADDING_0;
	g_cqt_sequential_1.layer[14].param_p = &batch_normalization_4;
	g_cqt_sequential_1.layer[14].data_p = &batch_normalization_4_output;

	strcpy(g_cqt_sequential_1.layer[15].name, "leaky_re_lu_4");
	g_cqt_sequential_1.layer[15].type = LT_LeakyReLU;
	leaky_re_lu_4.alpha = 0.10000000149011612;
	g_cqt_sequential_1.layer[15].input_dtypes[0] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[15].input_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[15].input_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[15].input_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[15].weight_dtypes[0] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[15].weight_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[15].weight_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[15].weight_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[15].output_dtypes[0] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[15].output_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[15].output_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[15].output_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[15].cqt_input_shape[0] = 0;
	g_cqt_sequential_1.layer[15].cqt_input_shape[1] = 52;
	g_cqt_sequential_1.layer[15].cqt_input_shape[2] = 52;
	g_cqt_sequential_1.layer[15].cqt_input_shape[3] = 128;
	g_cqt_sequential_1.layer[15].cqt_output_shape[0] = 0;
	g_cqt_sequential_1.layer[15].cqt_output_shape[1] = 52;
	g_cqt_sequential_1.layer[15].cqt_output_shape[2] = 52;
	g_cqt_sequential_1.layer[15].cqt_output_shape[3] = 128;
	g_cqt_sequential_1.layer[15].input_q = 8;
	g_cqt_sequential_1.layer[15].weight_q = 8;
	g_cqt_sequential_1.layer[15].output_q = 8;
	g_cqt_sequential_1.layer[15].overflow_cnt = 0;
	g_cqt_sequential_1.layer[15].neon_padding_hi = NEON_HPADDING_0;
	g_cqt_sequential_1.layer[15].neon_padding_ho = NEON_HPADDING_0;
	g_cqt_sequential_1.layer[15].param_p = &leaky_re_lu_4;
	g_cqt_sequential_1.layer[15].data_p = &leaky_re_lu_4_output;

	strcpy(g_cqt_sequential_1.layer[16].name, "max_pooling2d_4");
	g_cqt_sequential_1.layer[16].type = LT_MaxPooling2D;
	max_pooling2d_4.strides[0] = 2;
	max_pooling2d_4.strides[1] = 2;
	max_pooling2d_4.padding = PD_SAME;
	max_pooling2d_4.data_format = DF_CHANNELS_LAST;
	max_pooling2d_4.pool_size[0] = 2;
	max_pooling2d_4.pool_size[1] = 2;
	g_cqt_sequential_1.layer[16].input_dtypes[0] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[16].input_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[16].input_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[16].input_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[16].weight_dtypes[0] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[16].weight_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[16].weight_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[16].weight_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[16].output_dtypes[0] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[16].output_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[16].output_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[16].output_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[16].cqt_input_shape[0] = 0;
	g_cqt_sequential_1.layer[16].cqt_input_shape[1] = 52;
	g_cqt_sequential_1.layer[16].cqt_input_shape[2] = 52;
	g_cqt_sequential_1.layer[16].cqt_input_shape[3] = 128;
	g_cqt_sequential_1.layer[16].cqt_output_shape[0] = 0;
	g_cqt_sequential_1.layer[16].cqt_output_shape[1] = 26;
	g_cqt_sequential_1.layer[16].cqt_output_shape[2] = 26;
	g_cqt_sequential_1.layer[16].cqt_output_shape[3] = 128;
	g_cqt_sequential_1.layer[16].input_q = 8;
	g_cqt_sequential_1.layer[16].weight_q = 8;
	g_cqt_sequential_1.layer[16].output_q = 8;
	g_cqt_sequential_1.layer[16].overflow_cnt = 0;
	g_cqt_sequential_1.layer[16].neon_padding_hi = NEON_HPADDING_0;
	g_cqt_sequential_1.layer[16].neon_padding_ho = NEON_HPADDING_2;
	g_cqt_sequential_1.layer[16].param_p = &max_pooling2d_4;
	g_cqt_sequential_1.layer[16].data_p = &max_pooling2d_4_output;

	strcpy(g_cqt_sequential_1.layer[17].name, "conv2d_5");
	g_cqt_sequential_1.layer[17].type = LT_Conv2D;
	conv2d_5.filters = 256;
	conv2d_5.kernel_size[0] = 3;
	conv2d_5.kernel_size[1] = 3;
	conv2d_5.strides[0] = 1;
	conv2d_5.strides[1] = 1;
	conv2d_5.padding = PD_SAME;
	conv2d_5.data_format = DF_CHANNELS_LAST;
	conv2d_5.dilation_rate[0] = 1;
	conv2d_5.dilation_rate[1] = 1;
	conv2d_5.activation = ACT_LINEAR;
	conv2d_5.use_bias = false;
	conv2d_5.weight_np_header_p = &nph_conv2d_5_W;
	conv2d_5.weight_p = &w_conv2d_5_W;
	conv2d_5.bias_np_header_p = &nph_conv2d_5_b;
	conv2d_5.bias_p = &w_conv2d_5_b;
	g_cqt_sequential_1.layer[17].input_dtypes[0] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[17].input_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[17].input_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[17].input_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[17].weight_dtypes[0] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[17].weight_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[17].weight_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[17].weight_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[17].output_dtypes[0] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[17].output_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[17].output_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[17].output_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[17].cqt_input_shape[0] = 0;
	g_cqt_sequential_1.layer[17].cqt_input_shape[1] = 26;
	g_cqt_sequential_1.layer[17].cqt_input_shape[2] = 26;
	g_cqt_sequential_1.layer[17].cqt_input_shape[3] = 128;
	g_cqt_sequential_1.layer[17].cqt_output_shape[0] = 0;
	g_cqt_sequential_1.layer[17].cqt_output_shape[1] = 26;
	g_cqt_sequential_1.layer[17].cqt_output_shape[2] = 26;
	g_cqt_sequential_1.layer[17].cqt_output_shape[3] = 256;
	g_cqt_sequential_1.layer[17].input_q = 8;
	g_cqt_sequential_1.layer[17].weight_q = 8;
	g_cqt_sequential_1.layer[17].output_q = 8;
	g_cqt_sequential_1.layer[17].overflow_cnt = 0;
	g_cqt_sequential_1.layer[17].neon_padding_hi = NEON_HPADDING_2;
	g_cqt_sequential_1.layer[17].neon_padding_ho = NEON_HPADDING_2;
	g_cqt_sequential_1.layer[17].param_p = &conv2d_5;
	g_cqt_sequential_1.layer[17].data_p = &conv2d_5_output;

	strcpy(g_cqt_sequential_1.layer[18].name, "batch_normalization_5");
	g_cqt_sequential_1.layer[18].type = LT_BatchNormalization;
	batch_normalization_5.axis = -1;
	batch_normalization_5.momentum = 0.99;
	batch_normalization_5.epsilon = 0.001;
	batch_normalization_5.center = true;
	batch_normalization_5.scale = true;
	batch_normalization_5.beta_np_header_p = &nph_beta_batch_normalization_5_W;
	batch_normalization_5.beta_p = &beta_batch_normalization_5_W;
	batch_normalization_5.gamma_np_header_p = &nph_gamma_batch_normalization_5_W;
	batch_normalization_5.gamma_p = &gamma_batch_normalization_5_W;
	batch_normalization_5.moving_mean_np_header_p = &nph_moving_mean_batch_normalization_5_W;
	batch_normalization_5.moving_mean_p = &moving_mean_batch_normalization_5_W;
	batch_normalization_5.moving_variance_np_header_p = &nph_moving_variance_batch_normalization_5_W;
	batch_normalization_5.moving_variance_p = &moving_variance_batch_normalization_5_W;
	g_cqt_sequential_1.layer[18].input_dtypes[0] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[18].input_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[18].input_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[18].input_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[18].weight_dtypes[0] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[18].weight_dtypes[1] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[18].weight_dtypes[2] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[18].weight_dtypes[3] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[18].output_dtypes[0] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[18].output_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[18].output_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[18].output_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[18].cqt_input_shape[0] = 0;
	g_cqt_sequential_1.layer[18].cqt_input_shape[1] = 26;
	g_cqt_sequential_1.layer[18].cqt_input_shape[2] = 26;
	g_cqt_sequential_1.layer[18].cqt_input_shape[3] = 256;
	g_cqt_sequential_1.layer[18].cqt_output_shape[0] = 0;
	g_cqt_sequential_1.layer[18].cqt_output_shape[1] = 26;
	g_cqt_sequential_1.layer[18].cqt_output_shape[2] = 26;
	g_cqt_sequential_1.layer[18].cqt_output_shape[3] = 256;
	g_cqt_sequential_1.layer[18].input_q = 8;
	g_cqt_sequential_1.layer[18].weight_q = 8;
	g_cqt_sequential_1.layer[18].output_q = 8;
	g_cqt_sequential_1.layer[18].overflow_cnt = 0;
	g_cqt_sequential_1.layer[18].neon_padding_hi = NEON_HPADDING_2;
	g_cqt_sequential_1.layer[18].neon_padding_ho = NEON_HPADDING_2;
	g_cqt_sequential_1.layer[18].param_p = &batch_normalization_5;
	g_cqt_sequential_1.layer[18].data_p = &batch_normalization_5_output;

	strcpy(g_cqt_sequential_1.layer[19].name, "leaky_re_lu_5");
	g_cqt_sequential_1.layer[19].type = LT_LeakyReLU;
	leaky_re_lu_5.alpha = 0.10000000149011612;
	g_cqt_sequential_1.layer[19].input_dtypes[0] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[19].input_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[19].input_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[19].input_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[19].weight_dtypes[0] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[19].weight_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[19].weight_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[19].weight_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[19].output_dtypes[0] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[19].output_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[19].output_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[19].output_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[19].cqt_input_shape[0] = 0;
	g_cqt_sequential_1.layer[19].cqt_input_shape[1] = 26;
	g_cqt_sequential_1.layer[19].cqt_input_shape[2] = 26;
	g_cqt_sequential_1.layer[19].cqt_input_shape[3] = 256;
	g_cqt_sequential_1.layer[19].cqt_output_shape[0] = 0;
	g_cqt_sequential_1.layer[19].cqt_output_shape[1] = 26;
	g_cqt_sequential_1.layer[19].cqt_output_shape[2] = 26;
	g_cqt_sequential_1.layer[19].cqt_output_shape[3] = 256;
	g_cqt_sequential_1.layer[19].input_q = 8;
	g_cqt_sequential_1.layer[19].weight_q = 8;
	g_cqt_sequential_1.layer[19].output_q = 8;
	g_cqt_sequential_1.layer[19].overflow_cnt = 0;
	g_cqt_sequential_1.layer[19].neon_padding_hi = NEON_HPADDING_2;
	g_cqt_sequential_1.layer[19].neon_padding_ho = NEON_HPADDING_2;
	g_cqt_sequential_1.layer[19].param_p = &leaky_re_lu_5;
	g_cqt_sequential_1.layer[19].data_p = &leaky_re_lu_5_output;

	strcpy(g_cqt_sequential_1.layer[20].name, "max_pooling2d_5");
	g_cqt_sequential_1.layer[20].type = LT_MaxPooling2D;
	max_pooling2d_5.strides[0] = 2;
	max_pooling2d_5.strides[1] = 2;
	max_pooling2d_5.padding = PD_SAME;
	max_pooling2d_5.data_format = DF_CHANNELS_LAST;
	max_pooling2d_5.pool_size[0] = 2;
	max_pooling2d_5.pool_size[1] = 2;
	g_cqt_sequential_1.layer[20].input_dtypes[0] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[20].input_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[20].input_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[20].input_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[20].weight_dtypes[0] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[20].weight_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[20].weight_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[20].weight_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[20].output_dtypes[0] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[20].output_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[20].output_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[20].output_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[20].cqt_input_shape[0] = 0;
	g_cqt_sequential_1.layer[20].cqt_input_shape[1] = 26;
	g_cqt_sequential_1.layer[20].cqt_input_shape[2] = 26;
	g_cqt_sequential_1.layer[20].cqt_input_shape[3] = 256;
	g_cqt_sequential_1.layer[20].cqt_output_shape[0] = 0;
	g_cqt_sequential_1.layer[20].cqt_output_shape[1] = 13;
	g_cqt_sequential_1.layer[20].cqt_output_shape[2] = 13;
	g_cqt_sequential_1.layer[20].cqt_output_shape[3] = 256;
	g_cqt_sequential_1.layer[20].input_q = 8;
	g_cqt_sequential_1.layer[20].weight_q = 8;
	g_cqt_sequential_1.layer[20].output_q = 8;
	g_cqt_sequential_1.layer[20].overflow_cnt = 0;
	g_cqt_sequential_1.layer[20].neon_padding_hi = NEON_HPADDING_2;
	g_cqt_sequential_1.layer[20].neon_padding_ho = NEON_HPADDING_3;
	g_cqt_sequential_1.layer[20].param_p = &max_pooling2d_5;
	g_cqt_sequential_1.layer[20].data_p = &max_pooling2d_5_output;

	strcpy(g_cqt_sequential_1.layer[21].name, "conv2d_6");
	g_cqt_sequential_1.layer[21].type = LT_Conv2D;
	conv2d_6.filters = 512;
	conv2d_6.kernel_size[0] = 3;
	conv2d_6.kernel_size[1] = 3;
	conv2d_6.strides[0] = 1;
	conv2d_6.strides[1] = 1;
	conv2d_6.padding = PD_SAME;
	conv2d_6.data_format = DF_CHANNELS_LAST;
	conv2d_6.dilation_rate[0] = 1;
	conv2d_6.dilation_rate[1] = 1;
	conv2d_6.activation = ACT_LINEAR;
	conv2d_6.use_bias = false;
	conv2d_6.weight_np_header_p = &nph_conv2d_6_W;
	conv2d_6.weight_p = &w_conv2d_6_W;
	conv2d_6.bias_np_header_p = &nph_conv2d_6_b;
	conv2d_6.bias_p = &w_conv2d_6_b;
	g_cqt_sequential_1.layer[21].input_dtypes[0] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[21].input_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[21].input_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[21].input_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[21].weight_dtypes[0] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[21].weight_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[21].weight_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[21].weight_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[21].output_dtypes[0] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[21].output_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[21].output_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[21].output_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[21].cqt_input_shape[0] = 0;
	g_cqt_sequential_1.layer[21].cqt_input_shape[1] = 13;
	g_cqt_sequential_1.layer[21].cqt_input_shape[2] = 13;
	g_cqt_sequential_1.layer[21].cqt_input_shape[3] = 256;
	g_cqt_sequential_1.layer[21].cqt_output_shape[0] = 0;
	g_cqt_sequential_1.layer[21].cqt_output_shape[1] = 13;
	g_cqt_sequential_1.layer[21].cqt_output_shape[2] = 13;
	g_cqt_sequential_1.layer[21].cqt_output_shape[3] = 512;
	g_cqt_sequential_1.layer[21].input_q = 8;
	g_cqt_sequential_1.layer[21].weight_q = 8;
	g_cqt_sequential_1.layer[21].output_q = 8;
	g_cqt_sequential_1.layer[21].overflow_cnt = 0;
	g_cqt_sequential_1.layer[21].neon_padding_hi = NEON_HPADDING_3;
	g_cqt_sequential_1.layer[21].neon_padding_ho = NEON_HPADDING_3;
	g_cqt_sequential_1.layer[21].param_p = &conv2d_6;
	g_cqt_sequential_1.layer[21].data_p = &conv2d_6_output;

	strcpy(g_cqt_sequential_1.layer[22].name, "batch_normalization_6");
	g_cqt_sequential_1.layer[22].type = LT_BatchNormalization;
	batch_normalization_6.axis = -1;
	batch_normalization_6.momentum = 0.99;
	batch_normalization_6.epsilon = 0.001;
	batch_normalization_6.center = true;
	batch_normalization_6.scale = true;
	batch_normalization_6.beta_np_header_p = &nph_beta_batch_normalization_6_W;
	batch_normalization_6.beta_p = &beta_batch_normalization_6_W;
	batch_normalization_6.gamma_np_header_p = &nph_gamma_batch_normalization_6_W;
	batch_normalization_6.gamma_p = &gamma_batch_normalization_6_W;
	batch_normalization_6.moving_mean_np_header_p = &nph_moving_mean_batch_normalization_6_W;
	batch_normalization_6.moving_mean_p = &moving_mean_batch_normalization_6_W;
	batch_normalization_6.moving_variance_np_header_p = &nph_moving_variance_batch_normalization_6_W;
	batch_normalization_6.moving_variance_p = &moving_variance_batch_normalization_6_W;
	g_cqt_sequential_1.layer[22].input_dtypes[0] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[22].input_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[22].input_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[22].input_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[22].weight_dtypes[0] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[22].weight_dtypes[1] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[22].weight_dtypes[2] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[22].weight_dtypes[3] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[22].output_dtypes[0] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[22].output_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[22].output_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[22].output_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[22].cqt_input_shape[0] = 0;
	g_cqt_sequential_1.layer[22].cqt_input_shape[1] = 13;
	g_cqt_sequential_1.layer[22].cqt_input_shape[2] = 13;
	g_cqt_sequential_1.layer[22].cqt_input_shape[3] = 512;
	g_cqt_sequential_1.layer[22].cqt_output_shape[0] = 0;
	g_cqt_sequential_1.layer[22].cqt_output_shape[1] = 13;
	g_cqt_sequential_1.layer[22].cqt_output_shape[2] = 13;
	g_cqt_sequential_1.layer[22].cqt_output_shape[3] = 512;
	g_cqt_sequential_1.layer[22].input_q = 8;
	g_cqt_sequential_1.layer[22].weight_q = 8;
	g_cqt_sequential_1.layer[22].output_q = 8;
	g_cqt_sequential_1.layer[22].overflow_cnt = 0;
	g_cqt_sequential_1.layer[22].neon_padding_hi = NEON_HPADDING_3;
	g_cqt_sequential_1.layer[22].neon_padding_ho = NEON_HPADDING_3;
	g_cqt_sequential_1.layer[22].param_p = &batch_normalization_6;
	g_cqt_sequential_1.layer[22].data_p = &batch_normalization_6_output;

	strcpy(g_cqt_sequential_1.layer[23].name, "leaky_re_lu_6");
	g_cqt_sequential_1.layer[23].type = LT_LeakyReLU;
	leaky_re_lu_6.alpha = 0.10000000149011612;
	g_cqt_sequential_1.layer[23].input_dtypes[0] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[23].input_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[23].input_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[23].input_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[23].weight_dtypes[0] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[23].weight_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[23].weight_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[23].weight_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[23].output_dtypes[0] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[23].output_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[23].output_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[23].output_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[23].cqt_input_shape[0] = 0;
	g_cqt_sequential_1.layer[23].cqt_input_shape[1] = 13;
	g_cqt_sequential_1.layer[23].cqt_input_shape[2] = 13;
	g_cqt_sequential_1.layer[23].cqt_input_shape[3] = 512;
	g_cqt_sequential_1.layer[23].cqt_output_shape[0] = 0;
	g_cqt_sequential_1.layer[23].cqt_output_shape[1] = 13;
	g_cqt_sequential_1.layer[23].cqt_output_shape[2] = 13;
	g_cqt_sequential_1.layer[23].cqt_output_shape[3] = 512;
	g_cqt_sequential_1.layer[23].input_q = 8;
	g_cqt_sequential_1.layer[23].weight_q = 8;
	g_cqt_sequential_1.layer[23].output_q = 8;
	g_cqt_sequential_1.layer[23].overflow_cnt = 0;
	g_cqt_sequential_1.layer[23].neon_padding_hi = NEON_HPADDING_3;
	g_cqt_sequential_1.layer[23].neon_padding_ho = NEON_HPADDING_3;
	g_cqt_sequential_1.layer[23].param_p = &leaky_re_lu_6;
	g_cqt_sequential_1.layer[23].data_p = &leaky_re_lu_6_output;

	strcpy(g_cqt_sequential_1.layer[24].name, "max_pooling2d_6");
	g_cqt_sequential_1.layer[24].type = LT_MaxPooling2D;
	max_pooling2d_6.strides[0] = 1;
	max_pooling2d_6.strides[1] = 1;
	max_pooling2d_6.padding = PD_SAME;
	max_pooling2d_6.data_format = DF_CHANNELS_LAST;
	max_pooling2d_6.pool_size[0] = 2;
	max_pooling2d_6.pool_size[1] = 2;
	g_cqt_sequential_1.layer[24].input_dtypes[0] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[24].input_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[24].input_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[24].input_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[24].weight_dtypes[0] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[24].weight_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[24].weight_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[24].weight_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[24].output_dtypes[0] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[24].output_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[24].output_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[24].output_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[24].cqt_input_shape[0] = 0;
	g_cqt_sequential_1.layer[24].cqt_input_shape[1] = 13;
	g_cqt_sequential_1.layer[24].cqt_input_shape[2] = 13;
	g_cqt_sequential_1.layer[24].cqt_input_shape[3] = 512;
	g_cqt_sequential_1.layer[24].cqt_output_shape[0] = 0;
	g_cqt_sequential_1.layer[24].cqt_output_shape[1] = 13;
	g_cqt_sequential_1.layer[24].cqt_output_shape[2] = 13;
	g_cqt_sequential_1.layer[24].cqt_output_shape[3] = 512;
	g_cqt_sequential_1.layer[24].input_q = 8;
	g_cqt_sequential_1.layer[24].weight_q = 8;
	g_cqt_sequential_1.layer[24].output_q = 8;
	g_cqt_sequential_1.layer[24].overflow_cnt = 0;
	g_cqt_sequential_1.layer[24].neon_padding_hi = NEON_HPADDING_3;
	g_cqt_sequential_1.layer[24].neon_padding_ho = NEON_HPADDING_3;
	g_cqt_sequential_1.layer[24].param_p = &max_pooling2d_6;
	g_cqt_sequential_1.layer[24].data_p = &max_pooling2d_6_output;

	strcpy(g_cqt_sequential_1.layer[25].name, "conv2d_7");
	g_cqt_sequential_1.layer[25].type = LT_Conv2D;
	conv2d_7.filters = 1024;
	conv2d_7.kernel_size[0] = 3;
	conv2d_7.kernel_size[1] = 3;
	conv2d_7.strides[0] = 1;
	conv2d_7.strides[1] = 1;
	conv2d_7.padding = PD_SAME;
	conv2d_7.data_format = DF_CHANNELS_LAST;
	conv2d_7.dilation_rate[0] = 1;
	conv2d_7.dilation_rate[1] = 1;
	conv2d_7.activation = ACT_LINEAR;
	conv2d_7.use_bias = false;
	conv2d_7.weight_np_header_p = &nph_conv2d_7_W;
	conv2d_7.weight_p = &w_conv2d_7_W;
	conv2d_7.bias_np_header_p = &nph_conv2d_7_b;
	conv2d_7.bias_p = &w_conv2d_7_b;
	g_cqt_sequential_1.layer[25].input_dtypes[0] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[25].input_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[25].input_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[25].input_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[25].weight_dtypes[0] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[25].weight_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[25].weight_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[25].weight_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[25].output_dtypes[0] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[25].output_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[25].output_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[25].output_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[25].cqt_input_shape[0] = 0;
	g_cqt_sequential_1.layer[25].cqt_input_shape[1] = 13;
	g_cqt_sequential_1.layer[25].cqt_input_shape[2] = 13;
	g_cqt_sequential_1.layer[25].cqt_input_shape[3] = 512;
	g_cqt_sequential_1.layer[25].cqt_output_shape[0] = 0;
	g_cqt_sequential_1.layer[25].cqt_output_shape[1] = 13;
	g_cqt_sequential_1.layer[25].cqt_output_shape[2] = 13;
	g_cqt_sequential_1.layer[25].cqt_output_shape[3] = 1024;
	g_cqt_sequential_1.layer[25].input_q = 8;
	g_cqt_sequential_1.layer[25].weight_q = 8;
	g_cqt_sequential_1.layer[25].output_q = 8;
	g_cqt_sequential_1.layer[25].overflow_cnt = 0;
	g_cqt_sequential_1.layer[25].neon_padding_hi = NEON_HPADDING_3;
	g_cqt_sequential_1.layer[25].neon_padding_ho = NEON_HPADDING_3;
	g_cqt_sequential_1.layer[25].param_p = &conv2d_7;
	g_cqt_sequential_1.layer[25].data_p = &conv2d_7_output;

	strcpy(g_cqt_sequential_1.layer[26].name, "batch_normalization_7");
	g_cqt_sequential_1.layer[26].type = LT_BatchNormalization;
	batch_normalization_7.axis = -1;
	batch_normalization_7.momentum = 0.99;
	batch_normalization_7.epsilon = 0.001;
	batch_normalization_7.center = true;
	batch_normalization_7.scale = true;
	batch_normalization_7.beta_np_header_p = &nph_beta_batch_normalization_7_W;
	batch_normalization_7.beta_p = &beta_batch_normalization_7_W;
	batch_normalization_7.gamma_np_header_p = &nph_gamma_batch_normalization_7_W;
	batch_normalization_7.gamma_p = &gamma_batch_normalization_7_W;
	batch_normalization_7.moving_mean_np_header_p = &nph_moving_mean_batch_normalization_7_W;
	batch_normalization_7.moving_mean_p = &moving_mean_batch_normalization_7_W;
	batch_normalization_7.moving_variance_np_header_p = &nph_moving_variance_batch_normalization_7_W;
	batch_normalization_7.moving_variance_p = &moving_variance_batch_normalization_7_W;
	g_cqt_sequential_1.layer[26].input_dtypes[0] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[26].input_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[26].input_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[26].input_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[26].weight_dtypes[0] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[26].weight_dtypes[1] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[26].weight_dtypes[2] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[26].weight_dtypes[3] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[26].output_dtypes[0] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[26].output_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[26].output_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[26].output_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[26].cqt_input_shape[0] = 0;
	g_cqt_sequential_1.layer[26].cqt_input_shape[1] = 13;
	g_cqt_sequential_1.layer[26].cqt_input_shape[2] = 13;
	g_cqt_sequential_1.layer[26].cqt_input_shape[3] = 1024;
	g_cqt_sequential_1.layer[26].cqt_output_shape[0] = 0;
	g_cqt_sequential_1.layer[26].cqt_output_shape[1] = 13;
	g_cqt_sequential_1.layer[26].cqt_output_shape[2] = 13;
	g_cqt_sequential_1.layer[26].cqt_output_shape[3] = 1024;
	g_cqt_sequential_1.layer[26].input_q = 8;
	g_cqt_sequential_1.layer[26].weight_q = 8;
	g_cqt_sequential_1.layer[26].output_q = 8;
	g_cqt_sequential_1.layer[26].overflow_cnt = 0;
	g_cqt_sequential_1.layer[26].neon_padding_hi = NEON_HPADDING_3;
	g_cqt_sequential_1.layer[26].neon_padding_ho = NEON_HPADDING_3;
	g_cqt_sequential_1.layer[26].param_p = &batch_normalization_7;
	g_cqt_sequential_1.layer[26].data_p = &batch_normalization_7_output;

	strcpy(g_cqt_sequential_1.layer[27].name, "leaky_re_lu_7");
	g_cqt_sequential_1.layer[27].type = LT_LeakyReLU;
	leaky_re_lu_7.alpha = 0.10000000149011612;
	g_cqt_sequential_1.layer[27].input_dtypes[0] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[27].input_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[27].input_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[27].input_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[27].weight_dtypes[0] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[27].weight_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[27].weight_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[27].weight_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[27].output_dtypes[0] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[27].output_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[27].output_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[27].output_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[27].cqt_input_shape[0] = 0;
	g_cqt_sequential_1.layer[27].cqt_input_shape[1] = 13;
	g_cqt_sequential_1.layer[27].cqt_input_shape[2] = 13;
	g_cqt_sequential_1.layer[27].cqt_input_shape[3] = 1024;
	g_cqt_sequential_1.layer[27].cqt_output_shape[0] = 0;
	g_cqt_sequential_1.layer[27].cqt_output_shape[1] = 13;
	g_cqt_sequential_1.layer[27].cqt_output_shape[2] = 13;
	g_cqt_sequential_1.layer[27].cqt_output_shape[3] = 1024;
	g_cqt_sequential_1.layer[27].input_q = 8;
	g_cqt_sequential_1.layer[27].weight_q = 8;
	g_cqt_sequential_1.layer[27].output_q = 8;
	g_cqt_sequential_1.layer[27].overflow_cnt = 0;
	g_cqt_sequential_1.layer[27].neon_padding_hi = NEON_HPADDING_3;
	g_cqt_sequential_1.layer[27].neon_padding_ho = NEON_HPADDING_3;
	g_cqt_sequential_1.layer[27].param_p = &leaky_re_lu_7;
	g_cqt_sequential_1.layer[27].data_p = &leaky_re_lu_7_output;

	strcpy(g_cqt_sequential_1.layer[28].name, "conv2d_8");
	g_cqt_sequential_1.layer[28].type = LT_Conv2D;
	conv2d_8.filters = 1024;
	conv2d_8.kernel_size[0] = 3;
	conv2d_8.kernel_size[1] = 3;
	conv2d_8.strides[0] = 1;
	conv2d_8.strides[1] = 1;
	conv2d_8.padding = PD_SAME;
	conv2d_8.data_format = DF_CHANNELS_LAST;
	conv2d_8.dilation_rate[0] = 1;
	conv2d_8.dilation_rate[1] = 1;
	conv2d_8.activation = ACT_LINEAR;
	conv2d_8.use_bias = false;
	conv2d_8.weight_np_header_p = &nph_conv2d_8_W;
	conv2d_8.weight_p = &w_conv2d_8_W;
	conv2d_8.bias_np_header_p = &nph_conv2d_8_b;
	conv2d_8.bias_p = &w_conv2d_8_b;
	g_cqt_sequential_1.layer[28].input_dtypes[0] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[28].input_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[28].input_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[28].input_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[28].weight_dtypes[0] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[28].weight_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[28].weight_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[28].weight_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[28].output_dtypes[0] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[28].output_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[28].output_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[28].output_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[28].cqt_input_shape[0] = 0;
	g_cqt_sequential_1.layer[28].cqt_input_shape[1] = 13;
	g_cqt_sequential_1.layer[28].cqt_input_shape[2] = 13;
	g_cqt_sequential_1.layer[28].cqt_input_shape[3] = 1024;
	g_cqt_sequential_1.layer[28].cqt_output_shape[0] = 0;
	g_cqt_sequential_1.layer[28].cqt_output_shape[1] = 13;
	g_cqt_sequential_1.layer[28].cqt_output_shape[2] = 13;
	g_cqt_sequential_1.layer[28].cqt_output_shape[3] = 1024;
	g_cqt_sequential_1.layer[28].input_q = 8;
	g_cqt_sequential_1.layer[28].weight_q = 8;
	g_cqt_sequential_1.layer[28].output_q = 8;
	g_cqt_sequential_1.layer[28].overflow_cnt = 0;
	g_cqt_sequential_1.layer[28].neon_padding_hi = NEON_HPADDING_3;
	g_cqt_sequential_1.layer[28].neon_padding_ho = NEON_HPADDING_3;
	g_cqt_sequential_1.layer[28].param_p = &conv2d_8;
	g_cqt_sequential_1.layer[28].data_p = &conv2d_8_output;

	strcpy(g_cqt_sequential_1.layer[29].name, "batch_normalization_8");
	g_cqt_sequential_1.layer[29].type = LT_BatchNormalization;
	batch_normalization_8.axis = -1;
	batch_normalization_8.momentum = 0.99;
	batch_normalization_8.epsilon = 0.001;
	batch_normalization_8.center = true;
	batch_normalization_8.scale = true;
	batch_normalization_8.beta_np_header_p = &nph_beta_batch_normalization_8_W;
	batch_normalization_8.beta_p = &beta_batch_normalization_8_W;
	batch_normalization_8.gamma_np_header_p = &nph_gamma_batch_normalization_8_W;
	batch_normalization_8.gamma_p = &gamma_batch_normalization_8_W;
	batch_normalization_8.moving_mean_np_header_p = &nph_moving_mean_batch_normalization_8_W;
	batch_normalization_8.moving_mean_p = &moving_mean_batch_normalization_8_W;
	batch_normalization_8.moving_variance_np_header_p = &nph_moving_variance_batch_normalization_8_W;
	batch_normalization_8.moving_variance_p = &moving_variance_batch_normalization_8_W;
	g_cqt_sequential_1.layer[29].input_dtypes[0] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[29].input_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[29].input_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[29].input_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[29].weight_dtypes[0] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[29].weight_dtypes[1] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[29].weight_dtypes[2] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[29].weight_dtypes[3] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[29].output_dtypes[0] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[29].output_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[29].output_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[29].output_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[29].cqt_input_shape[0] = 0;
	g_cqt_sequential_1.layer[29].cqt_input_shape[1] = 13;
	g_cqt_sequential_1.layer[29].cqt_input_shape[2] = 13;
	g_cqt_sequential_1.layer[29].cqt_input_shape[3] = 1024;
	g_cqt_sequential_1.layer[29].cqt_output_shape[0] = 0;
	g_cqt_sequential_1.layer[29].cqt_output_shape[1] = 13;
	g_cqt_sequential_1.layer[29].cqt_output_shape[2] = 13;
	g_cqt_sequential_1.layer[29].cqt_output_shape[3] = 1024;
	g_cqt_sequential_1.layer[29].input_q = 8;
	g_cqt_sequential_1.layer[29].weight_q = 8;
	g_cqt_sequential_1.layer[29].output_q = 8;
	g_cqt_sequential_1.layer[29].overflow_cnt = 0;
	g_cqt_sequential_1.layer[29].neon_padding_hi = NEON_HPADDING_3;
	g_cqt_sequential_1.layer[29].neon_padding_ho = NEON_HPADDING_3;
	g_cqt_sequential_1.layer[29].param_p = &batch_normalization_8;
	g_cqt_sequential_1.layer[29].data_p = &batch_normalization_8_output;

	strcpy(g_cqt_sequential_1.layer[30].name, "leaky_re_lu_8");
	g_cqt_sequential_1.layer[30].type = LT_LeakyReLU;
	leaky_re_lu_8.alpha = 0.10000000149011612;
	g_cqt_sequential_1.layer[30].input_dtypes[0] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[30].input_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[30].input_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[30].input_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[30].weight_dtypes[0] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[30].weight_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[30].weight_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[30].weight_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[30].output_dtypes[0] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[30].output_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[30].output_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[30].output_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[30].cqt_input_shape[0] = 0;
	g_cqt_sequential_1.layer[30].cqt_input_shape[1] = 13;
	g_cqt_sequential_1.layer[30].cqt_input_shape[2] = 13;
	g_cqt_sequential_1.layer[30].cqt_input_shape[3] = 1024;
	g_cqt_sequential_1.layer[30].cqt_output_shape[0] = 0;
	g_cqt_sequential_1.layer[30].cqt_output_shape[1] = 13;
	g_cqt_sequential_1.layer[30].cqt_output_shape[2] = 13;
	g_cqt_sequential_1.layer[30].cqt_output_shape[3] = 1024;
	g_cqt_sequential_1.layer[30].input_q = 8;
	g_cqt_sequential_1.layer[30].weight_q = 8;
	g_cqt_sequential_1.layer[30].output_q = 8;
	g_cqt_sequential_1.layer[30].overflow_cnt = 0;
	g_cqt_sequential_1.layer[30].neon_padding_hi = NEON_HPADDING_3;
	g_cqt_sequential_1.layer[30].neon_padding_ho = NEON_HPADDING_3;
	g_cqt_sequential_1.layer[30].param_p = &leaky_re_lu_8;
	g_cqt_sequential_1.layer[30].data_p = &leaky_re_lu_8_output;

	strcpy(g_cqt_sequential_1.layer[31].name, "conv2d_9");
	g_cqt_sequential_1.layer[31].type = LT_Conv2D;
	conv2d_9.filters = 125;
	conv2d_9.kernel_size[0] = 1;
	conv2d_9.kernel_size[1] = 1;
	conv2d_9.strides[0] = 1;
	conv2d_9.strides[1] = 1;
	conv2d_9.padding = PD_SAME;
	conv2d_9.data_format = DF_CHANNELS_LAST;
	conv2d_9.dilation_rate[0] = 1;
	conv2d_9.dilation_rate[1] = 1;
	conv2d_9.activation = ACT_LINEAR;
	conv2d_9.use_bias = true;
	conv2d_9.weight_np_header_p = &nph_conv2d_9_W;
	conv2d_9.weight_p = &w_conv2d_9_W;
	conv2d_9.bias_np_header_p = &nph_conv2d_9_b;
	conv2d_9.bias_p = &w_conv2d_9_b;
	g_cqt_sequential_1.layer[31].input_dtypes[0] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[31].input_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[31].input_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[31].input_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[31].weight_dtypes[0] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[31].weight_dtypes[1] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[31].weight_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[31].weight_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[31].output_dtypes[0] = CQT_FLOAT32;
	g_cqt_sequential_1.layer[31].output_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[31].output_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[31].output_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_sequential_1.layer[31].cqt_input_shape[0] = 0;
	g_cqt_sequential_1.layer[31].cqt_input_shape[1] = 13;
	g_cqt_sequential_1.layer[31].cqt_input_shape[2] = 13;
	g_cqt_sequential_1.layer[31].cqt_input_shape[3] = 1024;
	g_cqt_sequential_1.layer[31].cqt_output_shape[0] = 0;
	g_cqt_sequential_1.layer[31].cqt_output_shape[1] = 13;
	g_cqt_sequential_1.layer[31].cqt_output_shape[2] = 13;
	g_cqt_sequential_1.layer[31].cqt_output_shape[3] = 125;
	g_cqt_sequential_1.layer[31].input_q = 8;
	g_cqt_sequential_1.layer[31].weight_q = 8;
	g_cqt_sequential_1.layer[31].output_q = 8;
	g_cqt_sequential_1.layer[31].overflow_cnt = 0;
	g_cqt_sequential_1.layer[31].neon_padding_hi = NEON_HPADDING_3;
	g_cqt_sequential_1.layer[31].neon_padding_ho = NEON_HPADDING_3;
	g_cqt_sequential_1.layer[31].param_p = &conv2d_9;
	g_cqt_sequential_1.layer[31].data_p = &conv2d_9_output;

	return &g_cqt_sequential_1;
}

int cqt_load_weight_from_files(CQT_NET* np, const char *path) {
	char buf[CQT_MAX_PATH];
	size_t path_len;
	size_t fname_w_len;
	size_t fname_b_len;
	int ret;

// conv2d_1
	path_len = strlen(path);
	fname_w_len = strlen("conv2d_1_kernel_z.npy");
	assert(path_len+fname_w_len<CQT_MAX_PATH);
	strcpy(buf, path);
	strcat(buf, "conv2d_1_kernel_z.npy");
	ret = load_from_numpy(w_conv2d_1_W, buf, 432, &nph_conv2d_1_W);
	if(ret != CQT_RET_OK){
		return ret;
	}


// batch_normalization_1
	fname_b_len = strlen("batch_normalization_1_beta_z.npy");
	assert(path_len+fname_b_len<CQT_MAX_PATH);
	strcpy(buf, path);
	strcat(buf, "batch_normalization_1_beta_z.npy");
	ret = load_from_numpy(beta_batch_normalization_1_W, buf, 16, &nph_beta_batch_normalization_1_W);
	if(ret != CQT_RET_OK){
		return ret;
	}

	fname_b_len = strlen("batch_normalization_1_gamma_z.npy");
	assert(path_len+fname_b_len<CQT_MAX_PATH);
	strcpy(buf, path);
	strcat(buf, "batch_normalization_1_gamma_z.npy");
	ret = load_from_numpy(gamma_batch_normalization_1_W, buf, 16, &nph_gamma_batch_normalization_1_W);
	if(ret != CQT_RET_OK){
		return ret;
	}

	fname_b_len = strlen("batch_normalization_1_moving_mean_z.npy");
	assert(path_len+fname_b_len<CQT_MAX_PATH);
	strcpy(buf, path);
	strcat(buf, "batch_normalization_1_moving_mean_z.npy");
	ret = load_from_numpy(moving_mean_batch_normalization_1_W, buf, 16, &nph_moving_mean_batch_normalization_1_W);
	if(ret != CQT_RET_OK){
		return ret;
	}

	fname_b_len = strlen("batch_normalization_1_moving_variance_z.npy");
	assert(path_len+fname_b_len<CQT_MAX_PATH);
	strcpy(buf, path);
	strcat(buf, "batch_normalization_1_moving_variance_z.npy");
	ret = load_from_numpy(moving_variance_batch_normalization_1_W, buf, 16, &nph_moving_variance_batch_normalization_1_W);
	if(ret != CQT_RET_OK){
		return ret;
	}

// conv2d_2
	path_len = strlen(path);
	fname_w_len = strlen("conv2d_2_kernel_z.npy");
	assert(path_len+fname_w_len<CQT_MAX_PATH);
	strcpy(buf, path);
	strcat(buf, "conv2d_2_kernel_z.npy");
	ret = load_from_numpy(w_conv2d_2_W, buf, 4608, &nph_conv2d_2_W);
	if(ret != CQT_RET_OK){
		return ret;
	}


// batch_normalization_2
	fname_b_len = strlen("batch_normalization_2_beta_z.npy");
	assert(path_len+fname_b_len<CQT_MAX_PATH);
	strcpy(buf, path);
	strcat(buf, "batch_normalization_2_beta_z.npy");
	ret = load_from_numpy(beta_batch_normalization_2_W, buf, 32, &nph_beta_batch_normalization_2_W);
	if(ret != CQT_RET_OK){
		return ret;
	}

	fname_b_len = strlen("batch_normalization_2_gamma_z.npy");
	assert(path_len+fname_b_len<CQT_MAX_PATH);
	strcpy(buf, path);
	strcat(buf, "batch_normalization_2_gamma_z.npy");
	ret = load_from_numpy(gamma_batch_normalization_2_W, buf, 32, &nph_gamma_batch_normalization_2_W);
	if(ret != CQT_RET_OK){
		return ret;
	}

	fname_b_len = strlen("batch_normalization_2_moving_mean_z.npy");
	assert(path_len+fname_b_len<CQT_MAX_PATH);
	strcpy(buf, path);
	strcat(buf, "batch_normalization_2_moving_mean_z.npy");
	ret = load_from_numpy(moving_mean_batch_normalization_2_W, buf, 32, &nph_moving_mean_batch_normalization_2_W);
	if(ret != CQT_RET_OK){
		return ret;
	}

	fname_b_len = strlen("batch_normalization_2_moving_variance_z.npy");
	assert(path_len+fname_b_len<CQT_MAX_PATH);
	strcpy(buf, path);
	strcat(buf, "batch_normalization_2_moving_variance_z.npy");
	ret = load_from_numpy(moving_variance_batch_normalization_2_W, buf, 32, &nph_moving_variance_batch_normalization_2_W);
	if(ret != CQT_RET_OK){
		return ret;
	}

// conv2d_3
	path_len = strlen(path);
	fname_w_len = strlen("conv2d_3_kernel_z.npy");
	assert(path_len+fname_w_len<CQT_MAX_PATH);
	strcpy(buf, path);
	strcat(buf, "conv2d_3_kernel_z.npy");
	ret = load_from_numpy(w_conv2d_3_W, buf, 18432, &nph_conv2d_3_W);
	if(ret != CQT_RET_OK){
		return ret;
	}


// batch_normalization_3
	fname_b_len = strlen("batch_normalization_3_beta_z.npy");
	assert(path_len+fname_b_len<CQT_MAX_PATH);
	strcpy(buf, path);
	strcat(buf, "batch_normalization_3_beta_z.npy");
	ret = load_from_numpy(beta_batch_normalization_3_W, buf, 64, &nph_beta_batch_normalization_3_W);
	if(ret != CQT_RET_OK){
		return ret;
	}

	fname_b_len = strlen("batch_normalization_3_gamma_z.npy");
	assert(path_len+fname_b_len<CQT_MAX_PATH);
	strcpy(buf, path);
	strcat(buf, "batch_normalization_3_gamma_z.npy");
	ret = load_from_numpy(gamma_batch_normalization_3_W, buf, 64, &nph_gamma_batch_normalization_3_W);
	if(ret != CQT_RET_OK){
		return ret;
	}

	fname_b_len = strlen("batch_normalization_3_moving_mean_z.npy");
	assert(path_len+fname_b_len<CQT_MAX_PATH);
	strcpy(buf, path);
	strcat(buf, "batch_normalization_3_moving_mean_z.npy");
	ret = load_from_numpy(moving_mean_batch_normalization_3_W, buf, 64, &nph_moving_mean_batch_normalization_3_W);
	if(ret != CQT_RET_OK){
		return ret;
	}

	fname_b_len = strlen("batch_normalization_3_moving_variance_z.npy");
	assert(path_len+fname_b_len<CQT_MAX_PATH);
	strcpy(buf, path);
	strcat(buf, "batch_normalization_3_moving_variance_z.npy");
	ret = load_from_numpy(moving_variance_batch_normalization_3_W, buf, 64, &nph_moving_variance_batch_normalization_3_W);
	if(ret != CQT_RET_OK){
		return ret;
	}

// conv2d_4
	path_len = strlen(path);
	fname_w_len = strlen("conv2d_4_kernel_z.npy");
	assert(path_len+fname_w_len<CQT_MAX_PATH);
	strcpy(buf, path);
	strcat(buf, "conv2d_4_kernel_z.npy");
	ret = load_from_numpy(w_conv2d_4_W, buf, 73728, &nph_conv2d_4_W);
	if(ret != CQT_RET_OK){
		return ret;
	}


// batch_normalization_4
	fname_b_len = strlen("batch_normalization_4_beta_z.npy");
	assert(path_len+fname_b_len<CQT_MAX_PATH);
	strcpy(buf, path);
	strcat(buf, "batch_normalization_4_beta_z.npy");
	ret = load_from_numpy(beta_batch_normalization_4_W, buf, 128, &nph_beta_batch_normalization_4_W);
	if(ret != CQT_RET_OK){
		return ret;
	}

	fname_b_len = strlen("batch_normalization_4_gamma_z.npy");
	assert(path_len+fname_b_len<CQT_MAX_PATH);
	strcpy(buf, path);
	strcat(buf, "batch_normalization_4_gamma_z.npy");
	ret = load_from_numpy(gamma_batch_normalization_4_W, buf, 128, &nph_gamma_batch_normalization_4_W);
	if(ret != CQT_RET_OK){
		return ret;
	}

	fname_b_len = strlen("batch_normalization_4_moving_mean_z.npy");
	assert(path_len+fname_b_len<CQT_MAX_PATH);
	strcpy(buf, path);
	strcat(buf, "batch_normalization_4_moving_mean_z.npy");
	ret = load_from_numpy(moving_mean_batch_normalization_4_W, buf, 128, &nph_moving_mean_batch_normalization_4_W);
	if(ret != CQT_RET_OK){
		return ret;
	}

	fname_b_len = strlen("batch_normalization_4_moving_variance_z.npy");
	assert(path_len+fname_b_len<CQT_MAX_PATH);
	strcpy(buf, path);
	strcat(buf, "batch_normalization_4_moving_variance_z.npy");
	ret = load_from_numpy(moving_variance_batch_normalization_4_W, buf, 128, &nph_moving_variance_batch_normalization_4_W);
	if(ret != CQT_RET_OK){
		return ret;
	}

// conv2d_5
	path_len = strlen(path);
	fname_w_len = strlen("conv2d_5_kernel_z.npy");
	assert(path_len+fname_w_len<CQT_MAX_PATH);
	strcpy(buf, path);
	strcat(buf, "conv2d_5_kernel_z.npy");
	ret = load_from_numpy(w_conv2d_5_W, buf, 294912, &nph_conv2d_5_W);
	if(ret != CQT_RET_OK){
		return ret;
	}


// batch_normalization_5
	fname_b_len = strlen("batch_normalization_5_beta_z.npy");
	assert(path_len+fname_b_len<CQT_MAX_PATH);
	strcpy(buf, path);
	strcat(buf, "batch_normalization_5_beta_z.npy");
	ret = load_from_numpy(beta_batch_normalization_5_W, buf, 256, &nph_beta_batch_normalization_5_W);
	if(ret != CQT_RET_OK){
		return ret;
	}

	fname_b_len = strlen("batch_normalization_5_gamma_z.npy");
	assert(path_len+fname_b_len<CQT_MAX_PATH);
	strcpy(buf, path);
	strcat(buf, "batch_normalization_5_gamma_z.npy");
	ret = load_from_numpy(gamma_batch_normalization_5_W, buf, 256, &nph_gamma_batch_normalization_5_W);
	if(ret != CQT_RET_OK){
		return ret;
	}

	fname_b_len = strlen("batch_normalization_5_moving_mean_z.npy");
	assert(path_len+fname_b_len<CQT_MAX_PATH);
	strcpy(buf, path);
	strcat(buf, "batch_normalization_5_moving_mean_z.npy");
	ret = load_from_numpy(moving_mean_batch_normalization_5_W, buf, 256, &nph_moving_mean_batch_normalization_5_W);
	if(ret != CQT_RET_OK){
		return ret;
	}

	fname_b_len = strlen("batch_normalization_5_moving_variance_z.npy");
	assert(path_len+fname_b_len<CQT_MAX_PATH);
	strcpy(buf, path);
	strcat(buf, "batch_normalization_5_moving_variance_z.npy");
	ret = load_from_numpy(moving_variance_batch_normalization_5_W, buf, 256, &nph_moving_variance_batch_normalization_5_W);
	if(ret != CQT_RET_OK){
		return ret;
	}

// conv2d_6
	path_len = strlen(path);
	fname_w_len = strlen("conv2d_6_kernel_z.npy");
	assert(path_len+fname_w_len<CQT_MAX_PATH);
	strcpy(buf, path);
	strcat(buf, "conv2d_6_kernel_z.npy");
	ret = load_from_numpy(w_conv2d_6_W, buf, 1179648, &nph_conv2d_6_W);
	if(ret != CQT_RET_OK){
		return ret;
	}


// batch_normalization_6
	fname_b_len = strlen("batch_normalization_6_beta_z.npy");
	assert(path_len+fname_b_len<CQT_MAX_PATH);
	strcpy(buf, path);
	strcat(buf, "batch_normalization_6_beta_z.npy");
	ret = load_from_numpy(beta_batch_normalization_6_W, buf, 512, &nph_beta_batch_normalization_6_W);
	if(ret != CQT_RET_OK){
		return ret;
	}

	fname_b_len = strlen("batch_normalization_6_gamma_z.npy");
	assert(path_len+fname_b_len<CQT_MAX_PATH);
	strcpy(buf, path);
	strcat(buf, "batch_normalization_6_gamma_z.npy");
	ret = load_from_numpy(gamma_batch_normalization_6_W, buf, 512, &nph_gamma_batch_normalization_6_W);
	if(ret != CQT_RET_OK){
		return ret;
	}

	fname_b_len = strlen("batch_normalization_6_moving_mean_z.npy");
	assert(path_len+fname_b_len<CQT_MAX_PATH);
	strcpy(buf, path);
	strcat(buf, "batch_normalization_6_moving_mean_z.npy");
	ret = load_from_numpy(moving_mean_batch_normalization_6_W, buf, 512, &nph_moving_mean_batch_normalization_6_W);
	if(ret != CQT_RET_OK){
		return ret;
	}

	fname_b_len = strlen("batch_normalization_6_moving_variance_z.npy");
	assert(path_len+fname_b_len<CQT_MAX_PATH);
	strcpy(buf, path);
	strcat(buf, "batch_normalization_6_moving_variance_z.npy");
	ret = load_from_numpy(moving_variance_batch_normalization_6_W, buf, 512, &nph_moving_variance_batch_normalization_6_W);
	if(ret != CQT_RET_OK){
		return ret;
	}

// conv2d_7
	path_len = strlen(path);
	fname_w_len = strlen("conv2d_7_kernel_z.npy");
	assert(path_len+fname_w_len<CQT_MAX_PATH);
	strcpy(buf, path);
	strcat(buf, "conv2d_7_kernel_z.npy");
	ret = load_from_numpy(w_conv2d_7_W, buf, 4718592, &nph_conv2d_7_W);
	if(ret != CQT_RET_OK){
		return ret;
	}


// batch_normalization_7
	fname_b_len = strlen("batch_normalization_7_beta_z.npy");
	assert(path_len+fname_b_len<CQT_MAX_PATH);
	strcpy(buf, path);
	strcat(buf, "batch_normalization_7_beta_z.npy");
	ret = load_from_numpy(beta_batch_normalization_7_W, buf, 1024, &nph_beta_batch_normalization_7_W);
	if(ret != CQT_RET_OK){
		return ret;
	}

	fname_b_len = strlen("batch_normalization_7_gamma_z.npy");
	assert(path_len+fname_b_len<CQT_MAX_PATH);
	strcpy(buf, path);
	strcat(buf, "batch_normalization_7_gamma_z.npy");
	ret = load_from_numpy(gamma_batch_normalization_7_W, buf, 1024, &nph_gamma_batch_normalization_7_W);
	if(ret != CQT_RET_OK){
		return ret;
	}

	fname_b_len = strlen("batch_normalization_7_moving_mean_z.npy");
	assert(path_len+fname_b_len<CQT_MAX_PATH);
	strcpy(buf, path);
	strcat(buf, "batch_normalization_7_moving_mean_z.npy");
	ret = load_from_numpy(moving_mean_batch_normalization_7_W, buf, 1024, &nph_moving_mean_batch_normalization_7_W);
	if(ret != CQT_RET_OK){
		return ret;
	}

	fname_b_len = strlen("batch_normalization_7_moving_variance_z.npy");
	assert(path_len+fname_b_len<CQT_MAX_PATH);
	strcpy(buf, path);
	strcat(buf, "batch_normalization_7_moving_variance_z.npy");
	ret = load_from_numpy(moving_variance_batch_normalization_7_W, buf, 1024, &nph_moving_variance_batch_normalization_7_W);
	if(ret != CQT_RET_OK){
		return ret;
	}

// conv2d_8
	path_len = strlen(path);
	fname_w_len = strlen("conv2d_8_kernel_z.npy");
	assert(path_len+fname_w_len<CQT_MAX_PATH);
	strcpy(buf, path);
	strcat(buf, "conv2d_8_kernel_z.npy");
	ret = load_from_numpy(w_conv2d_8_W, buf, 9437184, &nph_conv2d_8_W);
	if(ret != CQT_RET_OK){
		return ret;
	}


// batch_normalization_8
	fname_b_len = strlen("batch_normalization_8_beta_z.npy");
	assert(path_len+fname_b_len<CQT_MAX_PATH);
	strcpy(buf, path);
	strcat(buf, "batch_normalization_8_beta_z.npy");
	ret = load_from_numpy(beta_batch_normalization_8_W, buf, 1024, &nph_beta_batch_normalization_8_W);
	if(ret != CQT_RET_OK){
		return ret;
	}

	fname_b_len = strlen("batch_normalization_8_gamma_z.npy");
	assert(path_len+fname_b_len<CQT_MAX_PATH);
	strcpy(buf, path);
	strcat(buf, "batch_normalization_8_gamma_z.npy");
	ret = load_from_numpy(gamma_batch_normalization_8_W, buf, 1024, &nph_gamma_batch_normalization_8_W);
	if(ret != CQT_RET_OK){
		return ret;
	}

	fname_b_len = strlen("batch_normalization_8_moving_mean_z.npy");
	assert(path_len+fname_b_len<CQT_MAX_PATH);
	strcpy(buf, path);
	strcat(buf, "batch_normalization_8_moving_mean_z.npy");
	ret = load_from_numpy(moving_mean_batch_normalization_8_W, buf, 1024, &nph_moving_mean_batch_normalization_8_W);
	if(ret != CQT_RET_OK){
		return ret;
	}

	fname_b_len = strlen("batch_normalization_8_moving_variance_z.npy");
	assert(path_len+fname_b_len<CQT_MAX_PATH);
	strcpy(buf, path);
	strcat(buf, "batch_normalization_8_moving_variance_z.npy");
	ret = load_from_numpy(moving_variance_batch_normalization_8_W, buf, 1024, &nph_moving_variance_batch_normalization_8_W);
	if(ret != CQT_RET_OK){
		return ret;
	}

// conv2d_9
	path_len = strlen(path);
	fname_w_len = strlen("conv2d_9_kernel_z.npy");
	assert(path_len+fname_w_len<CQT_MAX_PATH);
	strcpy(buf, path);
	strcat(buf, "conv2d_9_kernel_z.npy");
	ret = load_from_numpy(w_conv2d_9_W, buf, 128000, &nph_conv2d_9_W);
	if(ret != CQT_RET_OK){
		return ret;
	}

	fname_b_len = strlen("conv2d_9_bias_z.npy");
	assert(path_len+fname_b_len<CQT_MAX_PATH);
	strcpy(buf, path);
	strcat(buf, "conv2d_9_bias_z.npy");
	ret = load_from_numpy(w_conv2d_9_b, buf, 125, &nph_conv2d_9_b);
	if(ret != CQT_RET_OK){
		return ret;
	}

	return CQT_RET_OK;
}

int cqt_run(CQT_NET* np, void *dp) {
	int ret;

	//input_1
	cqt_process = 0;
	ret = CQT_InputLayer_if_of(&(g_cqt_sequential_1.layer[0]), dp, input_1_output);
	if(ret != CQT_RET_OK){
		return ret;
	}

	//conv2d_1
	cqt_process = 1;
	ret = CQT_Conv2D_same_3x3_if_wf_of(&(g_cqt_sequential_1.layer[1]), input_1_output, conv2d_1_output);
	if(ret != CQT_RET_OK){
		return ret;
	}

	//batch_normalization_1
	cqt_process = 2;
	ret = CQT_BatchNormalization_if_wf_wf_wf_wf_of(&(g_cqt_sequential_1.layer[2]), conv2d_1_output, batch_normalization_1_output);
	if(ret != CQT_RET_OK){
		return ret;
	}

	//leaky_re_lu_1
	cqt_process = 3;
	ret = CQT_LeakyReLU_if_of(&(g_cqt_sequential_1.layer[3]), batch_normalization_1_output, leaky_re_lu_1_output);
	if(ret != CQT_RET_OK){
		return ret;
	}

	//max_pooling2d_1
	cqt_process = 4;
	ret = CQT_MaxPooling2D_if_of(&(g_cqt_sequential_1.layer[4]), leaky_re_lu_1_output, max_pooling2d_1_output);
	if(ret != CQT_RET_OK){
		return ret;
	}

	//conv2d_2
	cqt_process = 5;
	ret = CQT_Conv2D_same_3x3_if_wf_of(&(g_cqt_sequential_1.layer[5]), max_pooling2d_1_output, conv2d_2_output);
	if(ret != CQT_RET_OK){
		return ret;
	}

	//batch_normalization_2
	cqt_process = 6;
	ret = CQT_BatchNormalization_if_wf_wf_wf_wf_of(&(g_cqt_sequential_1.layer[6]), conv2d_2_output, batch_normalization_2_output);
	if(ret != CQT_RET_OK){
		return ret;
	}

	//leaky_re_lu_2
	cqt_process = 7;
	ret = CQT_LeakyReLU_if_of(&(g_cqt_sequential_1.layer[7]), batch_normalization_2_output, leaky_re_lu_2_output);
	if(ret != CQT_RET_OK){
		return ret;
	}

	//max_pooling2d_2
	cqt_process = 8;
	ret = CQT_MaxPooling2D_if_of(&(g_cqt_sequential_1.layer[8]), leaky_re_lu_2_output, max_pooling2d_2_output);
	if(ret != CQT_RET_OK){
		return ret;
	}

	//conv2d_3
	cqt_process = 9;
	ret = CQT_Conv2D_same_3x3_if_wf_of(&(g_cqt_sequential_1.layer[9]), max_pooling2d_2_output, conv2d_3_output);
	if(ret != CQT_RET_OK){
		return ret;
	}

	//batch_normalization_3
	cqt_process = 10;
	ret = CQT_BatchNormalization_if_wf_wf_wf_wf_of(&(g_cqt_sequential_1.layer[10]), conv2d_3_output, batch_normalization_3_output);
	if(ret != CQT_RET_OK){
		return ret;
	}

	//leaky_re_lu_3
	cqt_process = 11;
	ret = CQT_LeakyReLU_if_of(&(g_cqt_sequential_1.layer[11]), batch_normalization_3_output, leaky_re_lu_3_output);
	if(ret != CQT_RET_OK){
		return ret;
	}

	//max_pooling2d_3
	cqt_process = 12;
	ret = CQT_MaxPooling2D_if_of(&(g_cqt_sequential_1.layer[12]), leaky_re_lu_3_output, max_pooling2d_3_output);
	if(ret != CQT_RET_OK){
		return ret;
	}

	//conv2d_4
	cqt_process = 13;
	ret = CQT_Conv2D_same_3x3_if_wf_of(&(g_cqt_sequential_1.layer[13]), max_pooling2d_3_output, conv2d_4_output);
	if(ret != CQT_RET_OK){
		return ret;
	}

	//batch_normalization_4
	cqt_process = 14;
	ret = CQT_BatchNormalization_if_wf_wf_wf_wf_of(&(g_cqt_sequential_1.layer[14]), conv2d_4_output, batch_normalization_4_output);
	if(ret != CQT_RET_OK){
		return ret;
	}

	//leaky_re_lu_4
	cqt_process = 15;
	ret = CQT_LeakyReLU_if_of(&(g_cqt_sequential_1.layer[15]), batch_normalization_4_output, leaky_re_lu_4_output);
	if(ret != CQT_RET_OK){
		return ret;
	}

	//max_pooling2d_4
	cqt_process = 16;
	ret = CQT_MaxPooling2D_if_of(&(g_cqt_sequential_1.layer[16]), leaky_re_lu_4_output, max_pooling2d_4_output);
	if(ret != CQT_RET_OK){
		return ret;
	}

	//conv2d_5
	cqt_process = 17;
	ret = CQT_Conv2D_same_3x3_if_wf_of(&(g_cqt_sequential_1.layer[17]), max_pooling2d_4_output, conv2d_5_output);
	if(ret != CQT_RET_OK){
		return ret;
	}

	//batch_normalization_5
	cqt_process = 18;
	ret = CQT_BatchNormalization_if_wf_wf_wf_wf_of(&(g_cqt_sequential_1.layer[18]), conv2d_5_output, batch_normalization_5_output);
	if(ret != CQT_RET_OK){
		return ret;
	}

	//leaky_re_lu_5
	cqt_process = 19;
	ret = CQT_LeakyReLU_if_of(&(g_cqt_sequential_1.layer[19]), batch_normalization_5_output, leaky_re_lu_5_output);
	if(ret != CQT_RET_OK){
		return ret;
	}

	//max_pooling2d_5
	cqt_process = 20;
	ret = CQT_MaxPooling2D_if_of(&(g_cqt_sequential_1.layer[20]), leaky_re_lu_5_output, max_pooling2d_5_output);
	if(ret != CQT_RET_OK){
		return ret;
	}

	//conv2d_6
	cqt_process = 21;
	ret = CQT_Conv2D_same_3x3_if_wf_of(&(g_cqt_sequential_1.layer[21]), max_pooling2d_5_output, conv2d_6_output);
	if(ret != CQT_RET_OK){
		return ret;
	}

	//batch_normalization_6
	cqt_process = 22;
	ret = CQT_BatchNormalization_if_wf_wf_wf_wf_of(&(g_cqt_sequential_1.layer[22]), conv2d_6_output, batch_normalization_6_output);
	if(ret != CQT_RET_OK){
		return ret;
	}

	//leaky_re_lu_6
	cqt_process = 23;
	ret = CQT_LeakyReLU_if_of(&(g_cqt_sequential_1.layer[23]), batch_normalization_6_output, leaky_re_lu_6_output);
	if(ret != CQT_RET_OK){
		return ret;
	}

	//max_pooling2d_6
	cqt_process = 24;
	ret = CQT_MaxPooling2D_if_of(&(g_cqt_sequential_1.layer[24]), leaky_re_lu_6_output, max_pooling2d_6_output);
	if(ret != CQT_RET_OK){
		return ret;
	}

	//conv2d_7
	cqt_process = 25;
	ret = CQT_Conv2D_same_3x3_if_wf_of(&(g_cqt_sequential_1.layer[25]), max_pooling2d_6_output, conv2d_7_output);
	if(ret != CQT_RET_OK){
		return ret;
	}

	//batch_normalization_7
	cqt_process = 26;
	ret = CQT_BatchNormalization_if_wf_wf_wf_wf_of(&(g_cqt_sequential_1.layer[26]), conv2d_7_output, batch_normalization_7_output);
	if(ret != CQT_RET_OK){
		return ret;
	}

	//leaky_re_lu_7
	cqt_process = 27;
	ret = CQT_LeakyReLU_if_of(&(g_cqt_sequential_1.layer[27]), batch_normalization_7_output, leaky_re_lu_7_output);
	if(ret != CQT_RET_OK){
		return ret;
	}

	//conv2d_8
	cqt_process = 28;
	ret = CQT_Conv2D_same_3x3_if_wf_of(&(g_cqt_sequential_1.layer[28]), leaky_re_lu_7_output, conv2d_8_output);
	if(ret != CQT_RET_OK){
		return ret;
	}

	//batch_normalization_8
	cqt_process = 29;
	ret = CQT_BatchNormalization_if_wf_wf_wf_wf_of(&(g_cqt_sequential_1.layer[29]), conv2d_8_output, batch_normalization_8_output);
	if(ret != CQT_RET_OK){
		return ret;
	}

	//leaky_re_lu_8
	cqt_process = 30;
	ret = CQT_LeakyReLU_if_of(&(g_cqt_sequential_1.layer[30]), batch_normalization_8_output, leaky_re_lu_8_output);
	if(ret != CQT_RET_OK){
		return ret;
	}

	//conv2d_9
	cqt_process = 31;
	ret = CQT_Conv2D_same_1x1_if_wf_wf_of(&(g_cqt_sequential_1.layer[31]), leaky_re_lu_8_output, conv2d_9_output);
	if(ret != CQT_RET_OK){
		return ret;
	}

	return CQT_RET_OK;
}

void cqt_close(CQT_NET* np) {

}

