//----------------------------------------------------------------------------------------------------
// This file is automatically generated.
// 2017/11/05 00:00:00
//----------------------------------------------------------------------------------------------------
#include "cqt_debug.h"

//outputs
extern float input_1_output[3][416+NEON_VTR*3][NEON_HTR+416+NEON_HPADDING_0];
extern float conv2d_1_output[16][416+NEON_VTR*3][NEON_HTR+416+NEON_HPADDING_0];
extern float batch_normalization_1_output[16][416+NEON_VTR*3][NEON_HTR+416+NEON_HPADDING_0];
extern float leaky_re_lu_1_output[16][416+NEON_VTR*3][NEON_HTR+416+NEON_HPADDING_0];
extern float max_pooling2d_1_output[16][208+NEON_VTR*3][NEON_HTR+208+NEON_HPADDING_0];
extern float conv2d_2_output[32][208+NEON_VTR*3][NEON_HTR+208+NEON_HPADDING_0];
extern float batch_normalization_2_output[32][208+NEON_VTR*3][NEON_HTR+208+NEON_HPADDING_0];
extern float leaky_re_lu_2_output[32][208+NEON_VTR*3][NEON_HTR+208+NEON_HPADDING_0];
extern float max_pooling2d_2_output[32][104+NEON_VTR*3][NEON_HTR+104+NEON_HPADDING_0];
extern float conv2d_3_output[64][104+NEON_VTR*3][NEON_HTR+104+NEON_HPADDING_0];
extern float batch_normalization_3_output[64][104+NEON_VTR*3][NEON_HTR+104+NEON_HPADDING_0];
extern float leaky_re_lu_3_output[64][104+NEON_VTR*3][NEON_HTR+104+NEON_HPADDING_0];
extern float max_pooling2d_3_output[64][52+NEON_VTR*3][NEON_HTR+52+NEON_HPADDING_0];
extern float conv2d_4_output[128][52+NEON_VTR*3][NEON_HTR+52+NEON_HPADDING_0];
extern float batch_normalization_4_output[128][52+NEON_VTR*3][NEON_HTR+52+NEON_HPADDING_0];
extern float leaky_re_lu_4_output[128][52+NEON_VTR*3][NEON_HTR+52+NEON_HPADDING_0];
extern float max_pooling2d_4_output[128][26+NEON_VTR*3][NEON_HTR+26+NEON_HPADDING_2];
extern float conv2d_5_output[256][26+NEON_VTR*3][NEON_HTR+26+NEON_HPADDING_2];
extern float batch_normalization_5_output[256][26+NEON_VTR*3][NEON_HTR+26+NEON_HPADDING_2];
extern float leaky_re_lu_5_output[256][26+NEON_VTR*3][NEON_HTR+26+NEON_HPADDING_2];
extern float max_pooling2d_5_output[256][13+NEON_VTR*3][NEON_HTR+13+NEON_HPADDING_3];
extern float conv2d_6_output[512][13+NEON_VTR*3][NEON_HTR+13+NEON_HPADDING_3];
extern float batch_normalization_6_output[512][13+NEON_VTR*3][NEON_HTR+13+NEON_HPADDING_3];
extern float leaky_re_lu_6_output[512][13+NEON_VTR*3][NEON_HTR+13+NEON_HPADDING_3];
extern float max_pooling2d_6_output[512][13+NEON_VTR*3][NEON_HTR+13+NEON_HPADDING_3];
extern float conv2d_7_output[1024][13+NEON_VTR*3][NEON_HTR+13+NEON_HPADDING_3];
extern float batch_normalization_7_output[1024][13+NEON_VTR*3][NEON_HTR+13+NEON_HPADDING_3];
extern float leaky_re_lu_7_output[1024][13+NEON_VTR*3][NEON_HTR+13+NEON_HPADDING_3];
extern float conv2d_8_output[1024][13+NEON_VTR*3][NEON_HTR+13+NEON_HPADDING_3];
extern float batch_normalization_8_output[1024][13+NEON_VTR*3][NEON_HTR+13+NEON_HPADDING_3];
extern float leaky_re_lu_8_output[1024][13+NEON_VTR*3][NEON_HTR+13+NEON_HPADDING_3];
extern float conv2d_9_output[125][13+NEON_VTR*3][NEON_HTR+13+NEON_HPADDING_3];

extern NUMPY_HEADER np;

void cqt_layerdump(int l)
{
	switch(l) {
	case 0:
		cqt_layer0_dump();
		break;
	case 1:
		cqt_layer1_dump();
		break;
	case 2:
		cqt_layer2_dump();
		break;
	case 3:
		cqt_layer3_dump();
		break;
	case 4:
		cqt_layer4_dump();
		break;
	case 5:
		cqt_layer5_dump();
		break;
	case 6:
		cqt_layer6_dump();
		break;
	case 7:
		cqt_layer7_dump();
		break;
	case 8:
		cqt_layer8_dump();
		break;
	case 9:
		cqt_layer9_dump();
		break;
	case 10:
		cqt_layer10_dump();
		break;
	case 11:
		cqt_layer11_dump();
		break;
	case 12:
		cqt_layer12_dump();
		break;
	case 13:
		cqt_layer13_dump();
		break;
	case 14:
		cqt_layer14_dump();
		break;
	case 15:
		cqt_layer15_dump();
		break;
	case 16:
		cqt_layer16_dump();
		break;
	case 17:
		cqt_layer17_dump();
		break;
	case 18:
		cqt_layer18_dump();
		break;
	case 19:
		cqt_layer19_dump();
		break;
	case 20:
		cqt_layer20_dump();
		break;
	case 21:
		cqt_layer21_dump();
		break;
	case 22:
		cqt_layer22_dump();
		break;
	case 23:
		cqt_layer23_dump();
		break;
	case 24:
		cqt_layer24_dump();
		break;
	case 25:
		cqt_layer25_dump();
		break;
	case 26:
		cqt_layer26_dump();
		break;
	case 27:
		cqt_layer27_dump();
		break;
	case 28:
		cqt_layer28_dump();
		break;
	case 29:
		cqt_layer29_dump();
		break;
	case 30:
		cqt_layer30_dump();
		break;
	case 31:
		cqt_layer31_dump();
		break;
	default:
		printf("ERROR:invalid layer number %d\n", l);
		exit(1);
	}
}

void cqt_layer0_dump(void)
{
	NUMPY_HEADER np_0 = np;
	int ret;

	np_0.shape[0] = 3;
	np_0.shape[1] = 416 + NEON_VTR*3;
	np_0.shape[2] = NEON_HTR + 416 + NEON_HPADDING_0;
	np_0.shape[3] = 0;

	ret = save_to_numpy(input_1_output, "output/l00.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
}

void cqt_layer1_dump(void)
{
	NUMPY_HEADER np_0 = np;
	int ret;

	np_0.shape[0] = 16;
	np_0.shape[1] = 416 + NEON_VTR*3;
	np_0.shape[2] = NEON_HTR + 416 + NEON_HPADDING_0;
	np_0.shape[3] = 0;

	ret = save_to_numpy(conv2d_1_output, "output/l01.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
}

void cqt_layer2_dump(void)
{
	NUMPY_HEADER np_0 = np;
	int ret;

	np_0.shape[0] = 16;
	np_0.shape[1] = 416 + NEON_VTR*3;
	np_0.shape[2] = NEON_HTR + 416 + NEON_HPADDING_0;
	np_0.shape[3] = 0;

	ret = save_to_numpy(batch_normalization_1_output, "output/l02.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
}

void cqt_layer3_dump(void)
{
	NUMPY_HEADER np_0 = np;
	int ret;

	np_0.shape[0] = 16;
	np_0.shape[1] = 416 + NEON_VTR*3;
	np_0.shape[2] = NEON_HTR + 416 + NEON_HPADDING_0;
	np_0.shape[3] = 0;

	ret = save_to_numpy(leaky_re_lu_1_output, "output/l03.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
}

void cqt_layer4_dump(void)
{
	NUMPY_HEADER np_0 = np;
	int ret;

	np_0.shape[0] = 16;
	np_0.shape[1] = 208 + NEON_VTR*3;
	np_0.shape[2] = NEON_HTR + 208 + NEON_HPADDING_0;
	np_0.shape[3] = 0;

	ret = save_to_numpy(max_pooling2d_1_output, "output/l04.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
}

void cqt_layer5_dump(void)
{
	NUMPY_HEADER np_0 = np;
	int ret;

	np_0.shape[0] = 32;
	np_0.shape[1] = 208 + NEON_VTR*3;
	np_0.shape[2] = NEON_HTR + 208 + NEON_HPADDING_0;
	np_0.shape[3] = 0;

	ret = save_to_numpy(conv2d_2_output, "output/l05.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
}

void cqt_layer6_dump(void)
{
	NUMPY_HEADER np_0 = np;
	int ret;

	np_0.shape[0] = 32;
	np_0.shape[1] = 208 + NEON_VTR*3;
	np_0.shape[2] = NEON_HTR + 208 + NEON_HPADDING_0;
	np_0.shape[3] = 0;

	ret = save_to_numpy(batch_normalization_2_output, "output/l06.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
}

void cqt_layer7_dump(void)
{
	NUMPY_HEADER np_0 = np;
	int ret;

	np_0.shape[0] = 32;
	np_0.shape[1] = 208 + NEON_VTR*3;
	np_0.shape[2] = NEON_HTR + 208 + NEON_HPADDING_0;
	np_0.shape[3] = 0;

	ret = save_to_numpy(leaky_re_lu_2_output, "output/l07.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
}

void cqt_layer8_dump(void)
{
	NUMPY_HEADER np_0 = np;
	int ret;

	np_0.shape[0] = 32;
	np_0.shape[1] = 104 + NEON_VTR*3;
	np_0.shape[2] = NEON_HTR + 104 + NEON_HPADDING_0;
	np_0.shape[3] = 0;

	ret = save_to_numpy(max_pooling2d_2_output, "output/l08.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
}

void cqt_layer9_dump(void)
{
	NUMPY_HEADER np_0 = np;
	int ret;

	np_0.shape[0] = 64;
	np_0.shape[1] = 104 + NEON_VTR*3;
	np_0.shape[2] = NEON_HTR + 104 + NEON_HPADDING_0;
	np_0.shape[3] = 0;

	ret = save_to_numpy(conv2d_3_output, "output/l09.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
}

void cqt_layer10_dump(void)
{
	NUMPY_HEADER np_0 = np;
	int ret;

	np_0.shape[0] = 64;
	np_0.shape[1] = 104 + NEON_VTR*3;
	np_0.shape[2] = NEON_HTR + 104 + NEON_HPADDING_0;
	np_0.shape[3] = 0;

	ret = save_to_numpy(batch_normalization_3_output, "output/l10.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
}

void cqt_layer11_dump(void)
{
	NUMPY_HEADER np_0 = np;
	int ret;

	np_0.shape[0] = 64;
	np_0.shape[1] = 104 + NEON_VTR*3;
	np_0.shape[2] = NEON_HTR + 104 + NEON_HPADDING_0;
	np_0.shape[3] = 0;

	ret = save_to_numpy(leaky_re_lu_3_output, "output/l11.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
}

void cqt_layer12_dump(void)
{
	NUMPY_HEADER np_0 = np;
	int ret;

	np_0.shape[0] = 64;
	np_0.shape[1] = 52 + NEON_VTR*3;
	np_0.shape[2] = NEON_HTR + 52 + NEON_HPADDING_0;
	np_0.shape[3] = 0;

	ret = save_to_numpy(max_pooling2d_3_output, "output/l12.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
}

void cqt_layer13_dump(void)
{
	NUMPY_HEADER np_0 = np;
	int ret;

	np_0.shape[0] = 128;
	np_0.shape[1] = 52 + NEON_VTR*3;
	np_0.shape[2] = NEON_HTR + 52 + NEON_HPADDING_0;
	np_0.shape[3] = 0;

	ret = save_to_numpy(conv2d_4_output, "output/l13.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
}

void cqt_layer14_dump(void)
{
	NUMPY_HEADER np_0 = np;
	int ret;

	np_0.shape[0] = 128;
	np_0.shape[1] = 52 + NEON_VTR*3;
	np_0.shape[2] = NEON_HTR + 52 + NEON_HPADDING_0;
	np_0.shape[3] = 0;

	ret = save_to_numpy(batch_normalization_4_output, "output/l14.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
}

void cqt_layer15_dump(void)
{
	NUMPY_HEADER np_0 = np;
	int ret;

	np_0.shape[0] = 128;
	np_0.shape[1] = 52 + NEON_VTR*3;
	np_0.shape[2] = NEON_HTR + 52 + NEON_HPADDING_0;
	np_0.shape[3] = 0;

	ret = save_to_numpy(leaky_re_lu_4_output, "output/l15.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
}

void cqt_layer16_dump(void)
{
	NUMPY_HEADER np_0 = np;
	int ret;

	np_0.shape[0] = 128;
	np_0.shape[1] = 26 + NEON_VTR*3;
	np_0.shape[2] = NEON_HTR + 26 + NEON_HPADDING_2;
	np_0.shape[3] = 0;

	ret = save_to_numpy(max_pooling2d_4_output, "output/l16.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
}

void cqt_layer17_dump(void)
{
	NUMPY_HEADER np_0 = np;
	int ret;

	np_0.shape[0] = 256;
	np_0.shape[1] = 26 + NEON_VTR*3;
	np_0.shape[2] = NEON_HTR + 26 + NEON_HPADDING_2;
	np_0.shape[3] = 0;

	ret = save_to_numpy(conv2d_5_output, "output/l17.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
}

void cqt_layer18_dump(void)
{
	NUMPY_HEADER np_0 = np;
	int ret;

	np_0.shape[0] = 256;
	np_0.shape[1] = 26 + NEON_VTR*3;
	np_0.shape[2] = NEON_HTR + 26 + NEON_HPADDING_2;
	np_0.shape[3] = 0;

	ret = save_to_numpy(batch_normalization_5_output, "output/l18.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
}

void cqt_layer19_dump(void)
{
	NUMPY_HEADER np_0 = np;
	int ret;

	np_0.shape[0] = 256;
	np_0.shape[1] = 26 + NEON_VTR*3;
	np_0.shape[2] = NEON_HTR + 26 + NEON_HPADDING_2;
	np_0.shape[3] = 0;

	ret = save_to_numpy(leaky_re_lu_5_output, "output/l19.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
}

void cqt_layer20_dump(void)
{
	NUMPY_HEADER np_0 = np;
	int ret;

	np_0.shape[0] = 256;
	np_0.shape[1] = 13 + NEON_VTR*3;
	np_0.shape[2] = NEON_HTR + 13 + NEON_HPADDING_3;
	np_0.shape[3] = 0;

	ret = save_to_numpy(max_pooling2d_5_output, "output/l20.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
}

void cqt_layer21_dump(void)
{
	NUMPY_HEADER np_0 = np;
	int ret;

	np_0.shape[0] = 512;
	np_0.shape[1] = 13 + NEON_VTR*3;
	np_0.shape[2] = NEON_HTR + 13 + NEON_HPADDING_3;
	np_0.shape[3] = 0;

	ret = save_to_numpy(conv2d_6_output, "output/l21.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
}

void cqt_layer22_dump(void)
{
	NUMPY_HEADER np_0 = np;
	int ret;

	np_0.shape[0] = 512;
	np_0.shape[1] = 13 + NEON_VTR*3;
	np_0.shape[2] = NEON_HTR + 13 + NEON_HPADDING_3;
	np_0.shape[3] = 0;

	ret = save_to_numpy(batch_normalization_6_output, "output/l22.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
}

void cqt_layer23_dump(void)
{
	NUMPY_HEADER np_0 = np;
	int ret;

	np_0.shape[0] = 512;
	np_0.shape[1] = 13 + NEON_VTR*3;
	np_0.shape[2] = NEON_HTR + 13 + NEON_HPADDING_3;
	np_0.shape[3] = 0;

	ret = save_to_numpy(leaky_re_lu_6_output, "output/l23.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
}

void cqt_layer24_dump(void)
{
	NUMPY_HEADER np_0 = np;
	int ret;

	np_0.shape[0] = 512;
	np_0.shape[1] = 13 + NEON_VTR*3;
	np_0.shape[2] = NEON_HTR + 13 + NEON_HPADDING_3;
	np_0.shape[3] = 0;

	ret = save_to_numpy(max_pooling2d_6_output, "output/l24.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
}

void cqt_layer25_dump(void)
{
	NUMPY_HEADER np_0 = np;
	int ret;

	np_0.shape[0] = 1024;
	np_0.shape[1] = 13 + NEON_VTR*3;
	np_0.shape[2] = NEON_HTR + 13 + NEON_HPADDING_3;
	np_0.shape[3] = 0;

	ret = save_to_numpy(conv2d_7_output, "output/l25.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
}

void cqt_layer26_dump(void)
{
	NUMPY_HEADER np_0 = np;
	int ret;

	np_0.shape[0] = 1024;
	np_0.shape[1] = 13 + NEON_VTR*3;
	np_0.shape[2] = NEON_HTR + 13 + NEON_HPADDING_3;
	np_0.shape[3] = 0;

	ret = save_to_numpy(batch_normalization_7_output, "output/l26.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
}

void cqt_layer27_dump(void)
{
	NUMPY_HEADER np_0 = np;
	int ret;

	np_0.shape[0] = 1024;
	np_0.shape[1] = 13 + NEON_VTR*3;
	np_0.shape[2] = NEON_HTR + 13 + NEON_HPADDING_3;
	np_0.shape[3] = 0;

	ret = save_to_numpy(leaky_re_lu_7_output, "output/l27.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
}

void cqt_layer28_dump(void)
{
	NUMPY_HEADER np_0 = np;
	int ret;

	np_0.shape[0] = 1024;
	np_0.shape[1] = 13 + NEON_VTR*3;
	np_0.shape[2] = NEON_HTR + 13 + NEON_HPADDING_3;
	np_0.shape[3] = 0;

	ret = save_to_numpy(conv2d_8_output, "output/l28.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
}

void cqt_layer29_dump(void)
{
	NUMPY_HEADER np_0 = np;
	int ret;

	np_0.shape[0] = 1024;
	np_0.shape[1] = 13 + NEON_VTR*3;
	np_0.shape[2] = NEON_HTR + 13 + NEON_HPADDING_3;
	np_0.shape[3] = 0;

	ret = save_to_numpy(batch_normalization_8_output, "output/l29.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
}

void cqt_layer30_dump(void)
{
	NUMPY_HEADER np_0 = np;
	int ret;

	np_0.shape[0] = 1024;
	np_0.shape[1] = 13 + NEON_VTR*3;
	np_0.shape[2] = NEON_HTR + 13 + NEON_HPADDING_3;
	np_0.shape[3] = 0;

	ret = save_to_numpy(leaky_re_lu_8_output, "output/l30.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
}

void cqt_layer31_dump(void)
{
	NUMPY_HEADER np_0 = np;
	int ret;

	np_0.shape[0] = 125;
	np_0.shape[1] = 13 + NEON_VTR*3;
	np_0.shape[2] = NEON_HTR + 13 + NEON_HPADDING_3;
	np_0.shape[3] = 0;

	ret = save_to_numpy(conv2d_9_output, "output/l31.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
}


