//----------------------------------------------------------------------------------------------------
// This file is automatically generated.
// 2017/11/05 00:00:00
//----------------------------------------------------------------------------------------------------
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <assert.h>
#include "cqt.h"
#include "cqt_net.h"

void cqt_layerdump(int l);
void cqt_layer0_dump(void);
void cqt_layer1_dump(void);
void cqt_layer2_dump(void);
void cqt_layer3_dump(void);
void cqt_layer4_dump(void);
void cqt_layer5_dump(void);
void cqt_layer6_dump(void);
void cqt_layer7_dump(void);
void cqt_layer8_dump(void);
void cqt_layer9_dump(void);
void cqt_layer10_dump(void);
void cqt_layer11_dump(void);
void cqt_layer12_dump(void);
void cqt_layer13_dump(void);
void cqt_layer14_dump(void);
void cqt_layer15_dump(void);
void cqt_layer16_dump(void);
void cqt_layer17_dump(void);
void cqt_layer18_dump(void);
void cqt_layer19_dump(void);
void cqt_layer20_dump(void);
void cqt_layer21_dump(void);
void cqt_layer22_dump(void);
void cqt_layer23_dump(void);
void cqt_layer24_dump(void);
void cqt_layer25_dump(void);
void cqt_layer26_dump(void);
void cqt_layer27_dump(void);
void cqt_layer28_dump(void);
void cqt_layer29_dump(void);
void cqt_layer30_dump(void);
void cqt_layer31_dump(void);

