//----------------------------------------------------------------------------------------------------
// This file is automatically generated.
// 2017/09/15 00:00:00
//----------------------------------------------------------------------------------------------------
#include "cqt.h"
#include "cqt_net.h"

int CQT_InputLayer_if_of(CQT_LAYER *lp, void *inp, void *outp);
int CQT_conv2d_1_3x3(CQT_LAYER *lp, void *inp, void *outp);
int CQT_BatchNormalization_if_wf_wf_wf_wf_of(CQT_LAYER *lp, void *inp, void *outp);
int CQT_LeakyReLU_if_of(CQT_LAYER *lp, void *inp, void *outp);
int CQT_MaxPooling2D_if_of(CQT_LAYER *lp, void *inp, void *outp);
int CQT_conv2d_2_3x3(CQT_LAYER *lp, void *inp, void *outp);
int CQT_conv2d_3_3x3(CQT_LAYER *lp, void *inp, void *outp);
int CQT_conv2d_4_3x3(CQT_LAYER *lp, void *inp, void *outp);
int CQT_conv2d_5_3x3(CQT_LAYER *lp, void *inp, void *outp);
int CQT_conv2d_6_3x3(CQT_LAYER *lp, void *inp, void *outp);
int CQT_conv2d_7_3x3(CQT_LAYER *lp, void *inp, void *outp);
int CQT_conv2d_8_3x3(CQT_LAYER *lp, void *inp, void *outp);
int CQT_Conv2D_same_1x1_if_wf_wf_of(CQT_LAYER *lp, void *inp, void *outp);

