//----------------------------------------------------------------------------------------------------
// This file is automatically generated.
// 2017/07/18 00:00:00
//----------------------------------------------------------------------------------------------------
#include "cqt.h"
#include "cqt_net.h"

int CQT_InputLayer_ifx16_ofx16(CQT_LAYER *lp, void *inp, void *outp);
int CQT_Conv2D_same_3x3_ifx16_wfx16_wfx16_ofx16(CQT_LAYER *lp, void *inp, void *outp);
int CQT_MaxPooling2D_ifx16_ofx16(CQT_LAYER *lp, void *inp, void *outp);
int CQT_Flatten_ifx16_ofx16(CQT_LAYER *lp, void *inp, void *outp);
int CQT_Dense_ifx16_wfx16_wfx16_ofx16(CQT_LAYER *lp, void *inp, void *outp);

