//----------------------------------------------------------------------------------------------------
// This file is automatically generated.
// 2017/11/05 00:00:00
//----------------------------------------------------------------------------------------------------
#include "cqt.h"
#include "cqt_net.h"

int CQT_InputLayer_if_of(CQT_LAYER *lp, void *inp, void *outp);
int CQT_Conv2D_same_3x3_if_wf_of(CQT_LAYER *lp, void *inp, void *outp);
int CQT_BatchNormalization_if_wf_wf_wf_wf_of(CQT_LAYER *lp, void *inp, void *outp);
int CQT_LeakyReLU_if_of(CQT_LAYER *lp, void *inp, void *outp);
int CQT_MaxPooling2D_if_of(CQT_LAYER *lp, void *inp, void *outp);
int CQT_Conv2D_same_1x1_if_wf_wf_of(CQT_LAYER *lp, void *inp, void *outp);

