//----------------------------------------------------------------------------------------------------
// This file is automatically generated.
// 2017/07/06 00:00:00
//----------------------------------------------------------------------------------------------------
#include "cqt_gen.h"
#include "cqt_lib.h"

int cqt_process;

// cocytus network
CQT_NET g_cqt_vgg16;

//Layers
LY_InputLayer input_1;
LY_Conv2D block1_conv1;
LY_Conv2D block1_conv2;
LY_MaxPooling2D block1_pool;
LY_Conv2D block2_conv1;
LY_Conv2D block2_conv2;
LY_MaxPooling2D block2_pool;
LY_Conv2D block3_conv1;
LY_Conv2D block3_conv2;
LY_Conv2D block3_conv3;
LY_MaxPooling2D block3_pool;
LY_Conv2D block4_conv1;
LY_Conv2D block4_conv2;
LY_Conv2D block4_conv3;
LY_MaxPooling2D block4_pool;
LY_Conv2D block5_conv1;
LY_Conv2D block5_conv2;
LY_Conv2D block5_conv3;
LY_MaxPooling2D block5_pool;
LY_Flatten flatten;
LY_Dense fc1;
LY_Dense fc2;
LY_Dense predictions;

//weights
NUMPY_HEADER nph_block1_conv1_W;
NUMPY_HEADER nph_block1_conv1_b;
float w_block1_conv1_W[64][3][3][3];
float w_block1_conv1_b[64];
NUMPY_HEADER nph_block1_conv2_W;
NUMPY_HEADER nph_block1_conv2_b;
float w_block1_conv2_W[64][64][3][3];
float w_block1_conv2_b[64];
NUMPY_HEADER nph_block2_conv1_W;
NUMPY_HEADER nph_block2_conv1_b;
float w_block2_conv1_W[128][64][3][3];
float w_block2_conv1_b[128];
NUMPY_HEADER nph_block2_conv2_W;
NUMPY_HEADER nph_block2_conv2_b;
float w_block2_conv2_W[128][128][3][3];
float w_block2_conv2_b[128];
NUMPY_HEADER nph_block3_conv1_W;
NUMPY_HEADER nph_block3_conv1_b;
float w_block3_conv1_W[256][128][3][3];
float w_block3_conv1_b[256];
NUMPY_HEADER nph_block3_conv2_W;
NUMPY_HEADER nph_block3_conv2_b;
float w_block3_conv2_W[256][256][3][3];
float w_block3_conv2_b[256];
NUMPY_HEADER nph_block3_conv3_W;
NUMPY_HEADER nph_block3_conv3_b;
float w_block3_conv3_W[256][256][3][3];
float w_block3_conv3_b[256];
NUMPY_HEADER nph_block4_conv1_W;
NUMPY_HEADER nph_block4_conv1_b;
float w_block4_conv1_W[512][256][3][3];
float w_block4_conv1_b[512];
NUMPY_HEADER nph_block4_conv2_W;
NUMPY_HEADER nph_block4_conv2_b;
float w_block4_conv2_W[512][512][3][3];
float w_block4_conv2_b[512];
NUMPY_HEADER nph_block4_conv3_W;
NUMPY_HEADER nph_block4_conv3_b;
float w_block4_conv3_W[512][512][3][3];
float w_block4_conv3_b[512];
NUMPY_HEADER nph_block5_conv1_W;
NUMPY_HEADER nph_block5_conv1_b;
float w_block5_conv1_W[512][512][3][3];
float w_block5_conv1_b[512];
NUMPY_HEADER nph_block5_conv2_W;
NUMPY_HEADER nph_block5_conv2_b;
float w_block5_conv2_W[512][512][3][3];
float w_block5_conv2_b[512];
NUMPY_HEADER nph_block5_conv3_W;
NUMPY_HEADER nph_block5_conv3_b;
float w_block5_conv3_W[512][512][3][3];
float w_block5_conv3_b[512];
NUMPY_HEADER nph_fc1_W;
NUMPY_HEADER nph_fc1_b;
float w_fc1_W[4096][25088];
float w_fc1_b[4096];
NUMPY_HEADER nph_fc2_W;
NUMPY_HEADER nph_fc2_b;
float w_fc2_W[4096][4096];
float w_fc2_b[4096];
NUMPY_HEADER nph_predictions_W;
NUMPY_HEADER nph_predictions_b;
float w_predictions_W[1000][4096];
float w_predictions_b[1000];

//outputs
float input_1_output[3][224][224];
float block1_conv1_output[64][224][224];
float block1_conv2_output[64][224][224];
float block1_pool_output[64][112][112];
float block2_conv1_output[128][112][112];
float block2_conv2_output[128][112][112];
float block2_pool_output[128][56][56];
float block3_conv1_output[256][56][56];
float block3_conv2_output[256][56][56];
float block3_conv3_output[256][56][56];
float block3_pool_output[256][28][28];
float block4_conv1_output[512][28][28];
float block4_conv2_output[512][28][28];
float block4_conv3_output[512][28][28];
float block4_pool_output[512][14][14];
float block5_conv1_output[512][14][14];
float block5_conv2_output[512][14][14];
float block5_conv3_output[512][14][14];
float block5_pool_output[512][7][7];
float flatten_output[25088];
float fc1_output[4096];
float fc2_output[4096];
float predictions_output[1000];

CQT_NET* cqt_init(void) {
	g_cqt_vgg16.layernum = 23;
	cqt_process = 0;

	strcpy(g_cqt_vgg16.layer[0].name, "input_1");
	g_cqt_vgg16.layer[0].type = LT_InputLayer;
	g_cqt_vgg16.layer[0].input_dtypes[0] = CQT_FLOAT32;
	g_cqt_vgg16.layer[0].input_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[0].input_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[0].input_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[0].weight_dtypes[0] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[0].weight_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[0].weight_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[0].weight_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[0].output_dtypes[0] = CQT_FLOAT32;
	g_cqt_vgg16.layer[0].output_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[0].output_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[0].output_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[0].cqt_input_shape[0] = 0;
	g_cqt_vgg16.layer[0].cqt_input_shape[1] = 224;
	g_cqt_vgg16.layer[0].cqt_input_shape[2] = 224;
	g_cqt_vgg16.layer[0].cqt_input_shape[3] = 3;
	g_cqt_vgg16.layer[0].cqt_output_shape[0] = 0;
	g_cqt_vgg16.layer[0].cqt_output_shape[1] = 224;
	g_cqt_vgg16.layer[0].cqt_output_shape[2] = 224;
	g_cqt_vgg16.layer[0].cqt_output_shape[3] = 3;
	g_cqt_vgg16.layer[0].input_q = 8;
	g_cqt_vgg16.layer[0].weight_q = 8;
	g_cqt_vgg16.layer[0].output_q = 8;
	g_cqt_vgg16.layer[0].overflow_cnt = 0;
	g_cqt_vgg16.layer[0].param_p = &input_1;
	g_cqt_vgg16.layer[0].data_p = &input_1_output;

	strcpy(g_cqt_vgg16.layer[1].name, "block1_conv1");
	g_cqt_vgg16.layer[1].type = LT_Conv2D;
	block1_conv1.filters = 64;
	block1_conv1.kernel_size[0] = 3;
	block1_conv1.kernel_size[1] = 3;
	block1_conv1.strides[0] = 1;
	block1_conv1.strides[1] = 1;
	block1_conv1.padding = PD_SAME;
	block1_conv1.data_format = DF_CHANNELS_LAST;
	block1_conv1.dilation_rate[0] = 1;
	block1_conv1.dilation_rate[1] = 1;
	block1_conv1.activation = ACT_RELU;
	block1_conv1.use_bias = true;
	block1_conv1.weight_np_header_p = &nph_block1_conv1_W;
	block1_conv1.weight_p = &w_block1_conv1_W;
	block1_conv1.bias_np_header_p = &nph_block1_conv1_b;
	block1_conv1.bias_p = &w_block1_conv1_b;
	g_cqt_vgg16.layer[1].input_dtypes[0] = CQT_FLOAT32;
	g_cqt_vgg16.layer[1].input_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[1].input_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[1].input_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[1].weight_dtypes[0] = CQT_FLOAT32;
	g_cqt_vgg16.layer[1].weight_dtypes[1] = CQT_FLOAT32;
	g_cqt_vgg16.layer[1].weight_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[1].weight_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[1].output_dtypes[0] = CQT_FLOAT32;
	g_cqt_vgg16.layer[1].output_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[1].output_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[1].output_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[1].cqt_input_shape[0] = 0;
	g_cqt_vgg16.layer[1].cqt_input_shape[1] = 224;
	g_cqt_vgg16.layer[1].cqt_input_shape[2] = 224;
	g_cqt_vgg16.layer[1].cqt_input_shape[3] = 3;
	g_cqt_vgg16.layer[1].cqt_output_shape[0] = 0;
	g_cqt_vgg16.layer[1].cqt_output_shape[1] = 224;
	g_cqt_vgg16.layer[1].cqt_output_shape[2] = 224;
	g_cqt_vgg16.layer[1].cqt_output_shape[3] = 64;
	g_cqt_vgg16.layer[1].input_q = 8;
	g_cqt_vgg16.layer[1].weight_q = 8;
	g_cqt_vgg16.layer[1].output_q = 8;
	g_cqt_vgg16.layer[1].overflow_cnt = 0;
	g_cqt_vgg16.layer[1].param_p = &block1_conv1;
	g_cqt_vgg16.layer[1].data_p = &block1_conv1_output;

	strcpy(g_cqt_vgg16.layer[2].name, "block1_conv2");
	g_cqt_vgg16.layer[2].type = LT_Conv2D;
	block1_conv2.filters = 64;
	block1_conv2.kernel_size[0] = 3;
	block1_conv2.kernel_size[1] = 3;
	block1_conv2.strides[0] = 1;
	block1_conv2.strides[1] = 1;
	block1_conv2.padding = PD_SAME;
	block1_conv2.data_format = DF_CHANNELS_LAST;
	block1_conv2.dilation_rate[0] = 1;
	block1_conv2.dilation_rate[1] = 1;
	block1_conv2.activation = ACT_RELU;
	block1_conv2.use_bias = true;
	block1_conv2.weight_np_header_p = &nph_block1_conv2_W;
	block1_conv2.weight_p = &w_block1_conv2_W;
	block1_conv2.bias_np_header_p = &nph_block1_conv2_b;
	block1_conv2.bias_p = &w_block1_conv2_b;
	g_cqt_vgg16.layer[2].input_dtypes[0] = CQT_FLOAT32;
	g_cqt_vgg16.layer[2].input_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[2].input_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[2].input_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[2].weight_dtypes[0] = CQT_FLOAT32;
	g_cqt_vgg16.layer[2].weight_dtypes[1] = CQT_FLOAT32;
	g_cqt_vgg16.layer[2].weight_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[2].weight_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[2].output_dtypes[0] = CQT_FLOAT32;
	g_cqt_vgg16.layer[2].output_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[2].output_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[2].output_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[2].cqt_input_shape[0] = 0;
	g_cqt_vgg16.layer[2].cqt_input_shape[1] = 224;
	g_cqt_vgg16.layer[2].cqt_input_shape[2] = 224;
	g_cqt_vgg16.layer[2].cqt_input_shape[3] = 64;
	g_cqt_vgg16.layer[2].cqt_output_shape[0] = 0;
	g_cqt_vgg16.layer[2].cqt_output_shape[1] = 224;
	g_cqt_vgg16.layer[2].cqt_output_shape[2] = 224;
	g_cqt_vgg16.layer[2].cqt_output_shape[3] = 64;
	g_cqt_vgg16.layer[2].input_q = 8;
	g_cqt_vgg16.layer[2].weight_q = 8;
	g_cqt_vgg16.layer[2].output_q = 8;
	g_cqt_vgg16.layer[2].overflow_cnt = 0;
	g_cqt_vgg16.layer[2].param_p = &block1_conv2;
	g_cqt_vgg16.layer[2].data_p = &block1_conv2_output;

	strcpy(g_cqt_vgg16.layer[3].name, "block1_pool");
	g_cqt_vgg16.layer[3].type = LT_MaxPooling2D;
	block1_pool.strides[0] = 2;
	block1_pool.strides[1] = 2;
	block1_pool.padding = PD_VALID;
	block1_pool.data_format = DF_CHANNELS_LAST;
	block1_pool.pool_size[0] = 2;
	block1_pool.pool_size[1] = 2;
	g_cqt_vgg16.layer[3].input_dtypes[0] = CQT_FLOAT32;
	g_cqt_vgg16.layer[3].input_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[3].input_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[3].input_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[3].weight_dtypes[0] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[3].weight_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[3].weight_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[3].weight_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[3].output_dtypes[0] = CQT_FLOAT32;
	g_cqt_vgg16.layer[3].output_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[3].output_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[3].output_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[3].cqt_input_shape[0] = 0;
	g_cqt_vgg16.layer[3].cqt_input_shape[1] = 224;
	g_cqt_vgg16.layer[3].cqt_input_shape[2] = 224;
	g_cqt_vgg16.layer[3].cqt_input_shape[3] = 64;
	g_cqt_vgg16.layer[3].cqt_output_shape[0] = 0;
	g_cqt_vgg16.layer[3].cqt_output_shape[1] = 112;
	g_cqt_vgg16.layer[3].cqt_output_shape[2] = 112;
	g_cqt_vgg16.layer[3].cqt_output_shape[3] = 64;
	g_cqt_vgg16.layer[3].input_q = 8;
	g_cqt_vgg16.layer[3].weight_q = 8;
	g_cqt_vgg16.layer[3].output_q = 8;
	g_cqt_vgg16.layer[3].overflow_cnt = 0;
	g_cqt_vgg16.layer[3].param_p = &block1_pool;
	g_cqt_vgg16.layer[3].data_p = &block1_pool_output;

	strcpy(g_cqt_vgg16.layer[4].name, "block2_conv1");
	g_cqt_vgg16.layer[4].type = LT_Conv2D;
	block2_conv1.filters = 128;
	block2_conv1.kernel_size[0] = 3;
	block2_conv1.kernel_size[1] = 3;
	block2_conv1.strides[0] = 1;
	block2_conv1.strides[1] = 1;
	block2_conv1.padding = PD_SAME;
	block2_conv1.data_format = DF_CHANNELS_LAST;
	block2_conv1.dilation_rate[0] = 1;
	block2_conv1.dilation_rate[1] = 1;
	block2_conv1.activation = ACT_RELU;
	block2_conv1.use_bias = true;
	block2_conv1.weight_np_header_p = &nph_block2_conv1_W;
	block2_conv1.weight_p = &w_block2_conv1_W;
	block2_conv1.bias_np_header_p = &nph_block2_conv1_b;
	block2_conv1.bias_p = &w_block2_conv1_b;
	g_cqt_vgg16.layer[4].input_dtypes[0] = CQT_FLOAT32;
	g_cqt_vgg16.layer[4].input_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[4].input_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[4].input_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[4].weight_dtypes[0] = CQT_FLOAT32;
	g_cqt_vgg16.layer[4].weight_dtypes[1] = CQT_FLOAT32;
	g_cqt_vgg16.layer[4].weight_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[4].weight_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[4].output_dtypes[0] = CQT_FLOAT32;
	g_cqt_vgg16.layer[4].output_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[4].output_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[4].output_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[4].cqt_input_shape[0] = 0;
	g_cqt_vgg16.layer[4].cqt_input_shape[1] = 112;
	g_cqt_vgg16.layer[4].cqt_input_shape[2] = 112;
	g_cqt_vgg16.layer[4].cqt_input_shape[3] = 64;
	g_cqt_vgg16.layer[4].cqt_output_shape[0] = 0;
	g_cqt_vgg16.layer[4].cqt_output_shape[1] = 112;
	g_cqt_vgg16.layer[4].cqt_output_shape[2] = 112;
	g_cqt_vgg16.layer[4].cqt_output_shape[3] = 128;
	g_cqt_vgg16.layer[4].input_q = 8;
	g_cqt_vgg16.layer[4].weight_q = 8;
	g_cqt_vgg16.layer[4].output_q = 8;
	g_cqt_vgg16.layer[4].overflow_cnt = 0;
	g_cqt_vgg16.layer[4].param_p = &block2_conv1;
	g_cqt_vgg16.layer[4].data_p = &block2_conv1_output;

	strcpy(g_cqt_vgg16.layer[5].name, "block2_conv2");
	g_cqt_vgg16.layer[5].type = LT_Conv2D;
	block2_conv2.filters = 128;
	block2_conv2.kernel_size[0] = 3;
	block2_conv2.kernel_size[1] = 3;
	block2_conv2.strides[0] = 1;
	block2_conv2.strides[1] = 1;
	block2_conv2.padding = PD_SAME;
	block2_conv2.data_format = DF_CHANNELS_LAST;
	block2_conv2.dilation_rate[0] = 1;
	block2_conv2.dilation_rate[1] = 1;
	block2_conv2.activation = ACT_RELU;
	block2_conv2.use_bias = true;
	block2_conv2.weight_np_header_p = &nph_block2_conv2_W;
	block2_conv2.weight_p = &w_block2_conv2_W;
	block2_conv2.bias_np_header_p = &nph_block2_conv2_b;
	block2_conv2.bias_p = &w_block2_conv2_b;
	g_cqt_vgg16.layer[5].input_dtypes[0] = CQT_FLOAT32;
	g_cqt_vgg16.layer[5].input_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[5].input_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[5].input_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[5].weight_dtypes[0] = CQT_FLOAT32;
	g_cqt_vgg16.layer[5].weight_dtypes[1] = CQT_FLOAT32;
	g_cqt_vgg16.layer[5].weight_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[5].weight_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[5].output_dtypes[0] = CQT_FLOAT32;
	g_cqt_vgg16.layer[5].output_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[5].output_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[5].output_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[5].cqt_input_shape[0] = 0;
	g_cqt_vgg16.layer[5].cqt_input_shape[1] = 112;
	g_cqt_vgg16.layer[5].cqt_input_shape[2] = 112;
	g_cqt_vgg16.layer[5].cqt_input_shape[3] = 128;
	g_cqt_vgg16.layer[5].cqt_output_shape[0] = 0;
	g_cqt_vgg16.layer[5].cqt_output_shape[1] = 112;
	g_cqt_vgg16.layer[5].cqt_output_shape[2] = 112;
	g_cqt_vgg16.layer[5].cqt_output_shape[3] = 128;
	g_cqt_vgg16.layer[5].input_q = 8;
	g_cqt_vgg16.layer[5].weight_q = 8;
	g_cqt_vgg16.layer[5].output_q = 8;
	g_cqt_vgg16.layer[5].overflow_cnt = 0;
	g_cqt_vgg16.layer[5].param_p = &block2_conv2;
	g_cqt_vgg16.layer[5].data_p = &block2_conv2_output;

	strcpy(g_cqt_vgg16.layer[6].name, "block2_pool");
	g_cqt_vgg16.layer[6].type = LT_MaxPooling2D;
	block2_pool.strides[0] = 2;
	block2_pool.strides[1] = 2;
	block2_pool.padding = PD_VALID;
	block2_pool.data_format = DF_CHANNELS_LAST;
	block2_pool.pool_size[0] = 2;
	block2_pool.pool_size[1] = 2;
	g_cqt_vgg16.layer[6].input_dtypes[0] = CQT_FLOAT32;
	g_cqt_vgg16.layer[6].input_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[6].input_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[6].input_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[6].weight_dtypes[0] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[6].weight_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[6].weight_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[6].weight_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[6].output_dtypes[0] = CQT_FLOAT32;
	g_cqt_vgg16.layer[6].output_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[6].output_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[6].output_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[6].cqt_input_shape[0] = 0;
	g_cqt_vgg16.layer[6].cqt_input_shape[1] = 112;
	g_cqt_vgg16.layer[6].cqt_input_shape[2] = 112;
	g_cqt_vgg16.layer[6].cqt_input_shape[3] = 128;
	g_cqt_vgg16.layer[6].cqt_output_shape[0] = 0;
	g_cqt_vgg16.layer[6].cqt_output_shape[1] = 56;
	g_cqt_vgg16.layer[6].cqt_output_shape[2] = 56;
	g_cqt_vgg16.layer[6].cqt_output_shape[3] = 128;
	g_cqt_vgg16.layer[6].input_q = 8;
	g_cqt_vgg16.layer[6].weight_q = 8;
	g_cqt_vgg16.layer[6].output_q = 8;
	g_cqt_vgg16.layer[6].overflow_cnt = 0;
	g_cqt_vgg16.layer[6].param_p = &block2_pool;
	g_cqt_vgg16.layer[6].data_p = &block2_pool_output;

	strcpy(g_cqt_vgg16.layer[7].name, "block3_conv1");
	g_cqt_vgg16.layer[7].type = LT_Conv2D;
	block3_conv1.filters = 256;
	block3_conv1.kernel_size[0] = 3;
	block3_conv1.kernel_size[1] = 3;
	block3_conv1.strides[0] = 1;
	block3_conv1.strides[1] = 1;
	block3_conv1.padding = PD_SAME;
	block3_conv1.data_format = DF_CHANNELS_LAST;
	block3_conv1.dilation_rate[0] = 1;
	block3_conv1.dilation_rate[1] = 1;
	block3_conv1.activation = ACT_RELU;
	block3_conv1.use_bias = true;
	block3_conv1.weight_np_header_p = &nph_block3_conv1_W;
	block3_conv1.weight_p = &w_block3_conv1_W;
	block3_conv1.bias_np_header_p = &nph_block3_conv1_b;
	block3_conv1.bias_p = &w_block3_conv1_b;
	g_cqt_vgg16.layer[7].input_dtypes[0] = CQT_FLOAT32;
	g_cqt_vgg16.layer[7].input_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[7].input_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[7].input_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[7].weight_dtypes[0] = CQT_FLOAT32;
	g_cqt_vgg16.layer[7].weight_dtypes[1] = CQT_FLOAT32;
	g_cqt_vgg16.layer[7].weight_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[7].weight_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[7].output_dtypes[0] = CQT_FLOAT32;
	g_cqt_vgg16.layer[7].output_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[7].output_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[7].output_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[7].cqt_input_shape[0] = 0;
	g_cqt_vgg16.layer[7].cqt_input_shape[1] = 56;
	g_cqt_vgg16.layer[7].cqt_input_shape[2] = 56;
	g_cqt_vgg16.layer[7].cqt_input_shape[3] = 128;
	g_cqt_vgg16.layer[7].cqt_output_shape[0] = 0;
	g_cqt_vgg16.layer[7].cqt_output_shape[1] = 56;
	g_cqt_vgg16.layer[7].cqt_output_shape[2] = 56;
	g_cqt_vgg16.layer[7].cqt_output_shape[3] = 256;
	g_cqt_vgg16.layer[7].input_q = 8;
	g_cqt_vgg16.layer[7].weight_q = 8;
	g_cqt_vgg16.layer[7].output_q = 8;
	g_cqt_vgg16.layer[7].overflow_cnt = 0;
	g_cqt_vgg16.layer[7].param_p = &block3_conv1;
	g_cqt_vgg16.layer[7].data_p = &block3_conv1_output;

	strcpy(g_cqt_vgg16.layer[8].name, "block3_conv2");
	g_cqt_vgg16.layer[8].type = LT_Conv2D;
	block3_conv2.filters = 256;
	block3_conv2.kernel_size[0] = 3;
	block3_conv2.kernel_size[1] = 3;
	block3_conv2.strides[0] = 1;
	block3_conv2.strides[1] = 1;
	block3_conv2.padding = PD_SAME;
	block3_conv2.data_format = DF_CHANNELS_LAST;
	block3_conv2.dilation_rate[0] = 1;
	block3_conv2.dilation_rate[1] = 1;
	block3_conv2.activation = ACT_RELU;
	block3_conv2.use_bias = true;
	block3_conv2.weight_np_header_p = &nph_block3_conv2_W;
	block3_conv2.weight_p = &w_block3_conv2_W;
	block3_conv2.bias_np_header_p = &nph_block3_conv2_b;
	block3_conv2.bias_p = &w_block3_conv2_b;
	g_cqt_vgg16.layer[8].input_dtypes[0] = CQT_FLOAT32;
	g_cqt_vgg16.layer[8].input_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[8].input_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[8].input_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[8].weight_dtypes[0] = CQT_FLOAT32;
	g_cqt_vgg16.layer[8].weight_dtypes[1] = CQT_FLOAT32;
	g_cqt_vgg16.layer[8].weight_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[8].weight_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[8].output_dtypes[0] = CQT_FLOAT32;
	g_cqt_vgg16.layer[8].output_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[8].output_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[8].output_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[8].cqt_input_shape[0] = 0;
	g_cqt_vgg16.layer[8].cqt_input_shape[1] = 56;
	g_cqt_vgg16.layer[8].cqt_input_shape[2] = 56;
	g_cqt_vgg16.layer[8].cqt_input_shape[3] = 256;
	g_cqt_vgg16.layer[8].cqt_output_shape[0] = 0;
	g_cqt_vgg16.layer[8].cqt_output_shape[1] = 56;
	g_cqt_vgg16.layer[8].cqt_output_shape[2] = 56;
	g_cqt_vgg16.layer[8].cqt_output_shape[3] = 256;
	g_cqt_vgg16.layer[8].input_q = 8;
	g_cqt_vgg16.layer[8].weight_q = 8;
	g_cqt_vgg16.layer[8].output_q = 8;
	g_cqt_vgg16.layer[8].overflow_cnt = 0;
	g_cqt_vgg16.layer[8].param_p = &block3_conv2;
	g_cqt_vgg16.layer[8].data_p = &block3_conv2_output;

	strcpy(g_cqt_vgg16.layer[9].name, "block3_conv3");
	g_cqt_vgg16.layer[9].type = LT_Conv2D;
	block3_conv3.filters = 256;
	block3_conv3.kernel_size[0] = 3;
	block3_conv3.kernel_size[1] = 3;
	block3_conv3.strides[0] = 1;
	block3_conv3.strides[1] = 1;
	block3_conv3.padding = PD_SAME;
	block3_conv3.data_format = DF_CHANNELS_LAST;
	block3_conv3.dilation_rate[0] = 1;
	block3_conv3.dilation_rate[1] = 1;
	block3_conv3.activation = ACT_RELU;
	block3_conv3.use_bias = true;
	block3_conv3.weight_np_header_p = &nph_block3_conv3_W;
	block3_conv3.weight_p = &w_block3_conv3_W;
	block3_conv3.bias_np_header_p = &nph_block3_conv3_b;
	block3_conv3.bias_p = &w_block3_conv3_b;
	g_cqt_vgg16.layer[9].input_dtypes[0] = CQT_FLOAT32;
	g_cqt_vgg16.layer[9].input_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[9].input_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[9].input_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[9].weight_dtypes[0] = CQT_FLOAT32;
	g_cqt_vgg16.layer[9].weight_dtypes[1] = CQT_FLOAT32;
	g_cqt_vgg16.layer[9].weight_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[9].weight_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[9].output_dtypes[0] = CQT_FLOAT32;
	g_cqt_vgg16.layer[9].output_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[9].output_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[9].output_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[9].cqt_input_shape[0] = 0;
	g_cqt_vgg16.layer[9].cqt_input_shape[1] = 56;
	g_cqt_vgg16.layer[9].cqt_input_shape[2] = 56;
	g_cqt_vgg16.layer[9].cqt_input_shape[3] = 256;
	g_cqt_vgg16.layer[9].cqt_output_shape[0] = 0;
	g_cqt_vgg16.layer[9].cqt_output_shape[1] = 56;
	g_cqt_vgg16.layer[9].cqt_output_shape[2] = 56;
	g_cqt_vgg16.layer[9].cqt_output_shape[3] = 256;
	g_cqt_vgg16.layer[9].input_q = 8;
	g_cqt_vgg16.layer[9].weight_q = 8;
	g_cqt_vgg16.layer[9].output_q = 8;
	g_cqt_vgg16.layer[9].overflow_cnt = 0;
	g_cqt_vgg16.layer[9].param_p = &block3_conv3;
	g_cqt_vgg16.layer[9].data_p = &block3_conv3_output;

	strcpy(g_cqt_vgg16.layer[10].name, "block3_pool");
	g_cqt_vgg16.layer[10].type = LT_MaxPooling2D;
	block3_pool.strides[0] = 2;
	block3_pool.strides[1] = 2;
	block3_pool.padding = PD_VALID;
	block3_pool.data_format = DF_CHANNELS_LAST;
	block3_pool.pool_size[0] = 2;
	block3_pool.pool_size[1] = 2;
	g_cqt_vgg16.layer[10].input_dtypes[0] = CQT_FLOAT32;
	g_cqt_vgg16.layer[10].input_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[10].input_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[10].input_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[10].weight_dtypes[0] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[10].weight_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[10].weight_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[10].weight_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[10].output_dtypes[0] = CQT_FLOAT32;
	g_cqt_vgg16.layer[10].output_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[10].output_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[10].output_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[10].cqt_input_shape[0] = 0;
	g_cqt_vgg16.layer[10].cqt_input_shape[1] = 56;
	g_cqt_vgg16.layer[10].cqt_input_shape[2] = 56;
	g_cqt_vgg16.layer[10].cqt_input_shape[3] = 256;
	g_cqt_vgg16.layer[10].cqt_output_shape[0] = 0;
	g_cqt_vgg16.layer[10].cqt_output_shape[1] = 28;
	g_cqt_vgg16.layer[10].cqt_output_shape[2] = 28;
	g_cqt_vgg16.layer[10].cqt_output_shape[3] = 256;
	g_cqt_vgg16.layer[10].input_q = 8;
	g_cqt_vgg16.layer[10].weight_q = 8;
	g_cqt_vgg16.layer[10].output_q = 8;
	g_cqt_vgg16.layer[10].overflow_cnt = 0;
	g_cqt_vgg16.layer[10].param_p = &block3_pool;
	g_cqt_vgg16.layer[10].data_p = &block3_pool_output;

	strcpy(g_cqt_vgg16.layer[11].name, "block4_conv1");
	g_cqt_vgg16.layer[11].type = LT_Conv2D;
	block4_conv1.filters = 512;
	block4_conv1.kernel_size[0] = 3;
	block4_conv1.kernel_size[1] = 3;
	block4_conv1.strides[0] = 1;
	block4_conv1.strides[1] = 1;
	block4_conv1.padding = PD_SAME;
	block4_conv1.data_format = DF_CHANNELS_LAST;
	block4_conv1.dilation_rate[0] = 1;
	block4_conv1.dilation_rate[1] = 1;
	block4_conv1.activation = ACT_RELU;
	block4_conv1.use_bias = true;
	block4_conv1.weight_np_header_p = &nph_block4_conv1_W;
	block4_conv1.weight_p = &w_block4_conv1_W;
	block4_conv1.bias_np_header_p = &nph_block4_conv1_b;
	block4_conv1.bias_p = &w_block4_conv1_b;
	g_cqt_vgg16.layer[11].input_dtypes[0] = CQT_FLOAT32;
	g_cqt_vgg16.layer[11].input_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[11].input_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[11].input_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[11].weight_dtypes[0] = CQT_FLOAT32;
	g_cqt_vgg16.layer[11].weight_dtypes[1] = CQT_FLOAT32;
	g_cqt_vgg16.layer[11].weight_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[11].weight_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[11].output_dtypes[0] = CQT_FLOAT32;
	g_cqt_vgg16.layer[11].output_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[11].output_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[11].output_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[11].cqt_input_shape[0] = 0;
	g_cqt_vgg16.layer[11].cqt_input_shape[1] = 28;
	g_cqt_vgg16.layer[11].cqt_input_shape[2] = 28;
	g_cqt_vgg16.layer[11].cqt_input_shape[3] = 256;
	g_cqt_vgg16.layer[11].cqt_output_shape[0] = 0;
	g_cqt_vgg16.layer[11].cqt_output_shape[1] = 28;
	g_cqt_vgg16.layer[11].cqt_output_shape[2] = 28;
	g_cqt_vgg16.layer[11].cqt_output_shape[3] = 512;
	g_cqt_vgg16.layer[11].input_q = 8;
	g_cqt_vgg16.layer[11].weight_q = 8;
	g_cqt_vgg16.layer[11].output_q = 8;
	g_cqt_vgg16.layer[11].overflow_cnt = 0;
	g_cqt_vgg16.layer[11].param_p = &block4_conv1;
	g_cqt_vgg16.layer[11].data_p = &block4_conv1_output;

	strcpy(g_cqt_vgg16.layer[12].name, "block4_conv2");
	g_cqt_vgg16.layer[12].type = LT_Conv2D;
	block4_conv2.filters = 512;
	block4_conv2.kernel_size[0] = 3;
	block4_conv2.kernel_size[1] = 3;
	block4_conv2.strides[0] = 1;
	block4_conv2.strides[1] = 1;
	block4_conv2.padding = PD_SAME;
	block4_conv2.data_format = DF_CHANNELS_LAST;
	block4_conv2.dilation_rate[0] = 1;
	block4_conv2.dilation_rate[1] = 1;
	block4_conv2.activation = ACT_RELU;
	block4_conv2.use_bias = true;
	block4_conv2.weight_np_header_p = &nph_block4_conv2_W;
	block4_conv2.weight_p = &w_block4_conv2_W;
	block4_conv2.bias_np_header_p = &nph_block4_conv2_b;
	block4_conv2.bias_p = &w_block4_conv2_b;
	g_cqt_vgg16.layer[12].input_dtypes[0] = CQT_FLOAT32;
	g_cqt_vgg16.layer[12].input_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[12].input_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[12].input_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[12].weight_dtypes[0] = CQT_FLOAT32;
	g_cqt_vgg16.layer[12].weight_dtypes[1] = CQT_FLOAT32;
	g_cqt_vgg16.layer[12].weight_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[12].weight_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[12].output_dtypes[0] = CQT_FLOAT32;
	g_cqt_vgg16.layer[12].output_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[12].output_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[12].output_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[12].cqt_input_shape[0] = 0;
	g_cqt_vgg16.layer[12].cqt_input_shape[1] = 28;
	g_cqt_vgg16.layer[12].cqt_input_shape[2] = 28;
	g_cqt_vgg16.layer[12].cqt_input_shape[3] = 512;
	g_cqt_vgg16.layer[12].cqt_output_shape[0] = 0;
	g_cqt_vgg16.layer[12].cqt_output_shape[1] = 28;
	g_cqt_vgg16.layer[12].cqt_output_shape[2] = 28;
	g_cqt_vgg16.layer[12].cqt_output_shape[3] = 512;
	g_cqt_vgg16.layer[12].input_q = 8;
	g_cqt_vgg16.layer[12].weight_q = 8;
	g_cqt_vgg16.layer[12].output_q = 8;
	g_cqt_vgg16.layer[12].overflow_cnt = 0;
	g_cqt_vgg16.layer[12].param_p = &block4_conv2;
	g_cqt_vgg16.layer[12].data_p = &block4_conv2_output;

	strcpy(g_cqt_vgg16.layer[13].name, "block4_conv3");
	g_cqt_vgg16.layer[13].type = LT_Conv2D;
	block4_conv3.filters = 512;
	block4_conv3.kernel_size[0] = 3;
	block4_conv3.kernel_size[1] = 3;
	block4_conv3.strides[0] = 1;
	block4_conv3.strides[1] = 1;
	block4_conv3.padding = PD_SAME;
	block4_conv3.data_format = DF_CHANNELS_LAST;
	block4_conv3.dilation_rate[0] = 1;
	block4_conv3.dilation_rate[1] = 1;
	block4_conv3.activation = ACT_RELU;
	block4_conv3.use_bias = true;
	block4_conv3.weight_np_header_p = &nph_block4_conv3_W;
	block4_conv3.weight_p = &w_block4_conv3_W;
	block4_conv3.bias_np_header_p = &nph_block4_conv3_b;
	block4_conv3.bias_p = &w_block4_conv3_b;
	g_cqt_vgg16.layer[13].input_dtypes[0] = CQT_FLOAT32;
	g_cqt_vgg16.layer[13].input_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[13].input_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[13].input_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[13].weight_dtypes[0] = CQT_FLOAT32;
	g_cqt_vgg16.layer[13].weight_dtypes[1] = CQT_FLOAT32;
	g_cqt_vgg16.layer[13].weight_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[13].weight_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[13].output_dtypes[0] = CQT_FLOAT32;
	g_cqt_vgg16.layer[13].output_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[13].output_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[13].output_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[13].cqt_input_shape[0] = 0;
	g_cqt_vgg16.layer[13].cqt_input_shape[1] = 28;
	g_cqt_vgg16.layer[13].cqt_input_shape[2] = 28;
	g_cqt_vgg16.layer[13].cqt_input_shape[3] = 512;
	g_cqt_vgg16.layer[13].cqt_output_shape[0] = 0;
	g_cqt_vgg16.layer[13].cqt_output_shape[1] = 28;
	g_cqt_vgg16.layer[13].cqt_output_shape[2] = 28;
	g_cqt_vgg16.layer[13].cqt_output_shape[3] = 512;
	g_cqt_vgg16.layer[13].input_q = 8;
	g_cqt_vgg16.layer[13].weight_q = 8;
	g_cqt_vgg16.layer[13].output_q = 8;
	g_cqt_vgg16.layer[13].overflow_cnt = 0;
	g_cqt_vgg16.layer[13].param_p = &block4_conv3;
	g_cqt_vgg16.layer[13].data_p = &block4_conv3_output;

	strcpy(g_cqt_vgg16.layer[14].name, "block4_pool");
	g_cqt_vgg16.layer[14].type = LT_MaxPooling2D;
	block4_pool.strides[0] = 2;
	block4_pool.strides[1] = 2;
	block4_pool.padding = PD_VALID;
	block4_pool.data_format = DF_CHANNELS_LAST;
	block4_pool.pool_size[0] = 2;
	block4_pool.pool_size[1] = 2;
	g_cqt_vgg16.layer[14].input_dtypes[0] = CQT_FLOAT32;
	g_cqt_vgg16.layer[14].input_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[14].input_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[14].input_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[14].weight_dtypes[0] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[14].weight_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[14].weight_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[14].weight_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[14].output_dtypes[0] = CQT_FLOAT32;
	g_cqt_vgg16.layer[14].output_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[14].output_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[14].output_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[14].cqt_input_shape[0] = 0;
	g_cqt_vgg16.layer[14].cqt_input_shape[1] = 28;
	g_cqt_vgg16.layer[14].cqt_input_shape[2] = 28;
	g_cqt_vgg16.layer[14].cqt_input_shape[3] = 512;
	g_cqt_vgg16.layer[14].cqt_output_shape[0] = 0;
	g_cqt_vgg16.layer[14].cqt_output_shape[1] = 14;
	g_cqt_vgg16.layer[14].cqt_output_shape[2] = 14;
	g_cqt_vgg16.layer[14].cqt_output_shape[3] = 512;
	g_cqt_vgg16.layer[14].input_q = 8;
	g_cqt_vgg16.layer[14].weight_q = 8;
	g_cqt_vgg16.layer[14].output_q = 8;
	g_cqt_vgg16.layer[14].overflow_cnt = 0;
	g_cqt_vgg16.layer[14].param_p = &block4_pool;
	g_cqt_vgg16.layer[14].data_p = &block4_pool_output;

	strcpy(g_cqt_vgg16.layer[15].name, "block5_conv1");
	g_cqt_vgg16.layer[15].type = LT_Conv2D;
	block5_conv1.filters = 512;
	block5_conv1.kernel_size[0] = 3;
	block5_conv1.kernel_size[1] = 3;
	block5_conv1.strides[0] = 1;
	block5_conv1.strides[1] = 1;
	block5_conv1.padding = PD_SAME;
	block5_conv1.data_format = DF_CHANNELS_LAST;
	block5_conv1.dilation_rate[0] = 1;
	block5_conv1.dilation_rate[1] = 1;
	block5_conv1.activation = ACT_RELU;
	block5_conv1.use_bias = true;
	block5_conv1.weight_np_header_p = &nph_block5_conv1_W;
	block5_conv1.weight_p = &w_block5_conv1_W;
	block5_conv1.bias_np_header_p = &nph_block5_conv1_b;
	block5_conv1.bias_p = &w_block5_conv1_b;
	g_cqt_vgg16.layer[15].input_dtypes[0] = CQT_FLOAT32;
	g_cqt_vgg16.layer[15].input_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[15].input_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[15].input_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[15].weight_dtypes[0] = CQT_FLOAT32;
	g_cqt_vgg16.layer[15].weight_dtypes[1] = CQT_FLOAT32;
	g_cqt_vgg16.layer[15].weight_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[15].weight_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[15].output_dtypes[0] = CQT_FLOAT32;
	g_cqt_vgg16.layer[15].output_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[15].output_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[15].output_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[15].cqt_input_shape[0] = 0;
	g_cqt_vgg16.layer[15].cqt_input_shape[1] = 14;
	g_cqt_vgg16.layer[15].cqt_input_shape[2] = 14;
	g_cqt_vgg16.layer[15].cqt_input_shape[3] = 512;
	g_cqt_vgg16.layer[15].cqt_output_shape[0] = 0;
	g_cqt_vgg16.layer[15].cqt_output_shape[1] = 14;
	g_cqt_vgg16.layer[15].cqt_output_shape[2] = 14;
	g_cqt_vgg16.layer[15].cqt_output_shape[3] = 512;
	g_cqt_vgg16.layer[15].input_q = 8;
	g_cqt_vgg16.layer[15].weight_q = 8;
	g_cqt_vgg16.layer[15].output_q = 8;
	g_cqt_vgg16.layer[15].overflow_cnt = 0;
	g_cqt_vgg16.layer[15].param_p = &block5_conv1;
	g_cqt_vgg16.layer[15].data_p = &block5_conv1_output;

	strcpy(g_cqt_vgg16.layer[16].name, "block5_conv2");
	g_cqt_vgg16.layer[16].type = LT_Conv2D;
	block5_conv2.filters = 512;
	block5_conv2.kernel_size[0] = 3;
	block5_conv2.kernel_size[1] = 3;
	block5_conv2.strides[0] = 1;
	block5_conv2.strides[1] = 1;
	block5_conv2.padding = PD_SAME;
	block5_conv2.data_format = DF_CHANNELS_LAST;
	block5_conv2.dilation_rate[0] = 1;
	block5_conv2.dilation_rate[1] = 1;
	block5_conv2.activation = ACT_RELU;
	block5_conv2.use_bias = true;
	block5_conv2.weight_np_header_p = &nph_block5_conv2_W;
	block5_conv2.weight_p = &w_block5_conv2_W;
	block5_conv2.bias_np_header_p = &nph_block5_conv2_b;
	block5_conv2.bias_p = &w_block5_conv2_b;
	g_cqt_vgg16.layer[16].input_dtypes[0] = CQT_FLOAT32;
	g_cqt_vgg16.layer[16].input_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[16].input_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[16].input_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[16].weight_dtypes[0] = CQT_FLOAT32;
	g_cqt_vgg16.layer[16].weight_dtypes[1] = CQT_FLOAT32;
	g_cqt_vgg16.layer[16].weight_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[16].weight_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[16].output_dtypes[0] = CQT_FLOAT32;
	g_cqt_vgg16.layer[16].output_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[16].output_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[16].output_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[16].cqt_input_shape[0] = 0;
	g_cqt_vgg16.layer[16].cqt_input_shape[1] = 14;
	g_cqt_vgg16.layer[16].cqt_input_shape[2] = 14;
	g_cqt_vgg16.layer[16].cqt_input_shape[3] = 512;
	g_cqt_vgg16.layer[16].cqt_output_shape[0] = 0;
	g_cqt_vgg16.layer[16].cqt_output_shape[1] = 14;
	g_cqt_vgg16.layer[16].cqt_output_shape[2] = 14;
	g_cqt_vgg16.layer[16].cqt_output_shape[3] = 512;
	g_cqt_vgg16.layer[16].input_q = 8;
	g_cqt_vgg16.layer[16].weight_q = 8;
	g_cqt_vgg16.layer[16].output_q = 8;
	g_cqt_vgg16.layer[16].overflow_cnt = 0;
	g_cqt_vgg16.layer[16].param_p = &block5_conv2;
	g_cqt_vgg16.layer[16].data_p = &block5_conv2_output;

	strcpy(g_cqt_vgg16.layer[17].name, "block5_conv3");
	g_cqt_vgg16.layer[17].type = LT_Conv2D;
	block5_conv3.filters = 512;
	block5_conv3.kernel_size[0] = 3;
	block5_conv3.kernel_size[1] = 3;
	block5_conv3.strides[0] = 1;
	block5_conv3.strides[1] = 1;
	block5_conv3.padding = PD_SAME;
	block5_conv3.data_format = DF_CHANNELS_LAST;
	block5_conv3.dilation_rate[0] = 1;
	block5_conv3.dilation_rate[1] = 1;
	block5_conv3.activation = ACT_RELU;
	block5_conv3.use_bias = true;
	block5_conv3.weight_np_header_p = &nph_block5_conv3_W;
	block5_conv3.weight_p = &w_block5_conv3_W;
	block5_conv3.bias_np_header_p = &nph_block5_conv3_b;
	block5_conv3.bias_p = &w_block5_conv3_b;
	g_cqt_vgg16.layer[17].input_dtypes[0] = CQT_FLOAT32;
	g_cqt_vgg16.layer[17].input_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[17].input_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[17].input_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[17].weight_dtypes[0] = CQT_FLOAT32;
	g_cqt_vgg16.layer[17].weight_dtypes[1] = CQT_FLOAT32;
	g_cqt_vgg16.layer[17].weight_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[17].weight_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[17].output_dtypes[0] = CQT_FLOAT32;
	g_cqt_vgg16.layer[17].output_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[17].output_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[17].output_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[17].cqt_input_shape[0] = 0;
	g_cqt_vgg16.layer[17].cqt_input_shape[1] = 14;
	g_cqt_vgg16.layer[17].cqt_input_shape[2] = 14;
	g_cqt_vgg16.layer[17].cqt_input_shape[3] = 512;
	g_cqt_vgg16.layer[17].cqt_output_shape[0] = 0;
	g_cqt_vgg16.layer[17].cqt_output_shape[1] = 14;
	g_cqt_vgg16.layer[17].cqt_output_shape[2] = 14;
	g_cqt_vgg16.layer[17].cqt_output_shape[3] = 512;
	g_cqt_vgg16.layer[17].input_q = 8;
	g_cqt_vgg16.layer[17].weight_q = 8;
	g_cqt_vgg16.layer[17].output_q = 8;
	g_cqt_vgg16.layer[17].overflow_cnt = 0;
	g_cqt_vgg16.layer[17].param_p = &block5_conv3;
	g_cqt_vgg16.layer[17].data_p = &block5_conv3_output;

	strcpy(g_cqt_vgg16.layer[18].name, "block5_pool");
	g_cqt_vgg16.layer[18].type = LT_MaxPooling2D;
	block5_pool.strides[0] = 2;
	block5_pool.strides[1] = 2;
	block5_pool.padding = PD_VALID;
	block5_pool.data_format = DF_CHANNELS_LAST;
	block5_pool.pool_size[0] = 2;
	block5_pool.pool_size[1] = 2;
	g_cqt_vgg16.layer[18].input_dtypes[0] = CQT_FLOAT32;
	g_cqt_vgg16.layer[18].input_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[18].input_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[18].input_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[18].weight_dtypes[0] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[18].weight_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[18].weight_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[18].weight_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[18].output_dtypes[0] = CQT_FLOAT32;
	g_cqt_vgg16.layer[18].output_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[18].output_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[18].output_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[18].cqt_input_shape[0] = 0;
	g_cqt_vgg16.layer[18].cqt_input_shape[1] = 14;
	g_cqt_vgg16.layer[18].cqt_input_shape[2] = 14;
	g_cqt_vgg16.layer[18].cqt_input_shape[3] = 512;
	g_cqt_vgg16.layer[18].cqt_output_shape[0] = 0;
	g_cqt_vgg16.layer[18].cqt_output_shape[1] = 7;
	g_cqt_vgg16.layer[18].cqt_output_shape[2] = 7;
	g_cqt_vgg16.layer[18].cqt_output_shape[3] = 512;
	g_cqt_vgg16.layer[18].input_q = 8;
	g_cqt_vgg16.layer[18].weight_q = 8;
	g_cqt_vgg16.layer[18].output_q = 8;
	g_cqt_vgg16.layer[18].overflow_cnt = 0;
	g_cqt_vgg16.layer[18].param_p = &block5_pool;
	g_cqt_vgg16.layer[18].data_p = &block5_pool_output;

	strcpy(g_cqt_vgg16.layer[19].name, "flatten");
	g_cqt_vgg16.layer[19].type = LT_Flatten;
	g_cqt_vgg16.layer[19].input_dtypes[0] = CQT_FLOAT32;
	g_cqt_vgg16.layer[19].input_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[19].input_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[19].input_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[19].weight_dtypes[0] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[19].weight_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[19].weight_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[19].weight_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[19].output_dtypes[0] = CQT_FLOAT32;
	g_cqt_vgg16.layer[19].output_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[19].output_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[19].output_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[19].cqt_input_shape[0] = 0;
	g_cqt_vgg16.layer[19].cqt_input_shape[1] = 7;
	g_cqt_vgg16.layer[19].cqt_input_shape[2] = 7;
	g_cqt_vgg16.layer[19].cqt_input_shape[3] = 512;
	g_cqt_vgg16.layer[19].cqt_output_shape[0] = 0;
	g_cqt_vgg16.layer[19].cqt_output_shape[1] = 25088;
	g_cqt_vgg16.layer[19].cqt_output_shape[2] = 0;
	g_cqt_vgg16.layer[19].cqt_output_shape[3] = 0;
	g_cqt_vgg16.layer[19].input_q = 8;
	g_cqt_vgg16.layer[19].weight_q = 8;
	g_cqt_vgg16.layer[19].output_q = 8;
	g_cqt_vgg16.layer[19].overflow_cnt = 0;
	g_cqt_vgg16.layer[19].param_p = &flatten;
	g_cqt_vgg16.layer[19].data_p = &flatten_output;

	strcpy(g_cqt_vgg16.layer[20].name, "fc1");
	g_cqt_vgg16.layer[20].type = LT_Dense;
	fc1.units = 4096;
	fc1.activation = ACT_RELU;
	fc1.use_bias = true;
	fc1.weight_np_header_p = &nph_fc1_W;
	fc1.weight_p = &w_fc1_W;
	fc1.bias_np_header_p = &nph_fc1_b;
	fc1.bias_p = &w_fc1_b;
	g_cqt_vgg16.layer[20].input_dtypes[0] = CQT_FLOAT32;
	g_cqt_vgg16.layer[20].input_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[20].input_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[20].input_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[20].weight_dtypes[0] = CQT_FLOAT32;
	g_cqt_vgg16.layer[20].weight_dtypes[1] = CQT_FLOAT32;
	g_cqt_vgg16.layer[20].weight_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[20].weight_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[20].output_dtypes[0] = CQT_FLOAT32;
	g_cqt_vgg16.layer[20].output_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[20].output_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[20].output_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[20].cqt_input_shape[0] = 0;
	g_cqt_vgg16.layer[20].cqt_input_shape[1] = 25088;
	g_cqt_vgg16.layer[20].cqt_input_shape[2] = 0;
	g_cqt_vgg16.layer[20].cqt_input_shape[3] = 0;
	g_cqt_vgg16.layer[20].cqt_output_shape[0] = 0;
	g_cqt_vgg16.layer[20].cqt_output_shape[1] = 4096;
	g_cqt_vgg16.layer[20].cqt_output_shape[2] = 0;
	g_cqt_vgg16.layer[20].cqt_output_shape[3] = 0;
	g_cqt_vgg16.layer[20].input_q = 8;
	g_cqt_vgg16.layer[20].weight_q = 8;
	g_cqt_vgg16.layer[20].output_q = 8;
	g_cqt_vgg16.layer[20].overflow_cnt = 0;
	g_cqt_vgg16.layer[20].param_p = &fc1;
	g_cqt_vgg16.layer[20].data_p = &fc1_output;

	strcpy(g_cqt_vgg16.layer[21].name, "fc2");
	g_cqt_vgg16.layer[21].type = LT_Dense;
	fc2.units = 4096;
	fc2.activation = ACT_RELU;
	fc2.use_bias = true;
	fc2.weight_np_header_p = &nph_fc2_W;
	fc2.weight_p = &w_fc2_W;
	fc2.bias_np_header_p = &nph_fc2_b;
	fc2.bias_p = &w_fc2_b;
	g_cqt_vgg16.layer[21].input_dtypes[0] = CQT_FLOAT32;
	g_cqt_vgg16.layer[21].input_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[21].input_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[21].input_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[21].weight_dtypes[0] = CQT_FLOAT32;
	g_cqt_vgg16.layer[21].weight_dtypes[1] = CQT_FLOAT32;
	g_cqt_vgg16.layer[21].weight_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[21].weight_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[21].output_dtypes[0] = CQT_FLOAT32;
	g_cqt_vgg16.layer[21].output_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[21].output_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[21].output_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[21].cqt_input_shape[0] = 0;
	g_cqt_vgg16.layer[21].cqt_input_shape[1] = 4096;
	g_cqt_vgg16.layer[21].cqt_input_shape[2] = 0;
	g_cqt_vgg16.layer[21].cqt_input_shape[3] = 0;
	g_cqt_vgg16.layer[21].cqt_output_shape[0] = 0;
	g_cqt_vgg16.layer[21].cqt_output_shape[1] = 4096;
	g_cqt_vgg16.layer[21].cqt_output_shape[2] = 0;
	g_cqt_vgg16.layer[21].cqt_output_shape[3] = 0;
	g_cqt_vgg16.layer[21].input_q = 8;
	g_cqt_vgg16.layer[21].weight_q = 8;
	g_cqt_vgg16.layer[21].output_q = 8;
	g_cqt_vgg16.layer[21].overflow_cnt = 0;
	g_cqt_vgg16.layer[21].param_p = &fc2;
	g_cqt_vgg16.layer[21].data_p = &fc2_output;

	strcpy(g_cqt_vgg16.layer[22].name, "predictions");
	g_cqt_vgg16.layer[22].type = LT_Dense;
	predictions.units = 1000;
	predictions.activation = ACT_SOFTMAX;
	predictions.use_bias = true;
	predictions.weight_np_header_p = &nph_predictions_W;
	predictions.weight_p = &w_predictions_W;
	predictions.bias_np_header_p = &nph_predictions_b;
	predictions.bias_p = &w_predictions_b;
	g_cqt_vgg16.layer[22].input_dtypes[0] = CQT_FLOAT32;
	g_cqt_vgg16.layer[22].input_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[22].input_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[22].input_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[22].weight_dtypes[0] = CQT_FLOAT32;
	g_cqt_vgg16.layer[22].weight_dtypes[1] = CQT_FLOAT32;
	g_cqt_vgg16.layer[22].weight_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[22].weight_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[22].output_dtypes[0] = CQT_FLOAT32;
	g_cqt_vgg16.layer[22].output_dtypes[1] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[22].output_dtypes[2] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[22].output_dtypes[3] = CQT_DTYPE_NONE;
	g_cqt_vgg16.layer[22].cqt_input_shape[0] = 0;
	g_cqt_vgg16.layer[22].cqt_input_shape[1] = 4096;
	g_cqt_vgg16.layer[22].cqt_input_shape[2] = 0;
	g_cqt_vgg16.layer[22].cqt_input_shape[3] = 0;
	g_cqt_vgg16.layer[22].cqt_output_shape[0] = 0;
	g_cqt_vgg16.layer[22].cqt_output_shape[1] = 1000;
	g_cqt_vgg16.layer[22].cqt_output_shape[2] = 0;
	g_cqt_vgg16.layer[22].cqt_output_shape[3] = 0;
	g_cqt_vgg16.layer[22].input_q = 8;
	g_cqt_vgg16.layer[22].weight_q = 8;
	g_cqt_vgg16.layer[22].output_q = 8;
	g_cqt_vgg16.layer[22].overflow_cnt = 0;
	g_cqt_vgg16.layer[22].param_p = &predictions;
	g_cqt_vgg16.layer[22].data_p = &predictions_output;

	return &g_cqt_vgg16;
}

int cqt_load_weight_from_files(CQT_NET* np, const char *path) {
	char buf[CQT_MAX_PATH];
	size_t path_len;
	size_t fname_w_len;
	size_t fname_b_len;
	int ret;

// block1_conv1
	path_len = strlen(path);
	fname_w_len = strlen("block1_conv1_W_1_z.npy");
	assert(path_len+fname_w_len<CQT_MAX_PATH);
	strcpy(buf, path);
	strcat(buf, "block1_conv1_W_1_z.npy");
	ret = load_from_numpy(w_block1_conv1_W, buf, 1728, &nph_block1_conv1_W);
	if(ret != CQT_RET_OK){
		return ret;
	}

	fname_b_len = strlen("block1_conv1_b_1_z.npy");
	assert(path_len+fname_b_len<CQT_MAX_PATH);
	strcpy(buf, path);
	strcat(buf, "block1_conv1_b_1_z.npy");
	ret = load_from_numpy(w_block1_conv1_b, buf, 64, &nph_block1_conv1_b);
	if(ret != CQT_RET_OK){
		return ret;
	}

// block1_conv2
	path_len = strlen(path);
	fname_w_len = strlen("block1_conv2_W_1_z.npy");
	assert(path_len+fname_w_len<CQT_MAX_PATH);
	strcpy(buf, path);
	strcat(buf, "block1_conv2_W_1_z.npy");
	ret = load_from_numpy(w_block1_conv2_W, buf, 36864, &nph_block1_conv2_W);
	if(ret != CQT_RET_OK){
		return ret;
	}

	fname_b_len = strlen("block1_conv2_b_1_z.npy");
	assert(path_len+fname_b_len<CQT_MAX_PATH);
	strcpy(buf, path);
	strcat(buf, "block1_conv2_b_1_z.npy");
	ret = load_from_numpy(w_block1_conv2_b, buf, 64, &nph_block1_conv2_b);
	if(ret != CQT_RET_OK){
		return ret;
	}

// block2_conv1
	path_len = strlen(path);
	fname_w_len = strlen("block2_conv1_W_1_z.npy");
	assert(path_len+fname_w_len<CQT_MAX_PATH);
	strcpy(buf, path);
	strcat(buf, "block2_conv1_W_1_z.npy");
	ret = load_from_numpy(w_block2_conv1_W, buf, 73728, &nph_block2_conv1_W);
	if(ret != CQT_RET_OK){
		return ret;
	}

	fname_b_len = strlen("block2_conv1_b_1_z.npy");
	assert(path_len+fname_b_len<CQT_MAX_PATH);
	strcpy(buf, path);
	strcat(buf, "block2_conv1_b_1_z.npy");
	ret = load_from_numpy(w_block2_conv1_b, buf, 128, &nph_block2_conv1_b);
	if(ret != CQT_RET_OK){
		return ret;
	}

// block2_conv2
	path_len = strlen(path);
	fname_w_len = strlen("block2_conv2_W_1_z.npy");
	assert(path_len+fname_w_len<CQT_MAX_PATH);
	strcpy(buf, path);
	strcat(buf, "block2_conv2_W_1_z.npy");
	ret = load_from_numpy(w_block2_conv2_W, buf, 147456, &nph_block2_conv2_W);
	if(ret != CQT_RET_OK){
		return ret;
	}

	fname_b_len = strlen("block2_conv2_b_1_z.npy");
	assert(path_len+fname_b_len<CQT_MAX_PATH);
	strcpy(buf, path);
	strcat(buf, "block2_conv2_b_1_z.npy");
	ret = load_from_numpy(w_block2_conv2_b, buf, 128, &nph_block2_conv2_b);
	if(ret != CQT_RET_OK){
		return ret;
	}

// block3_conv1
	path_len = strlen(path);
	fname_w_len = strlen("block3_conv1_W_1_z.npy");
	assert(path_len+fname_w_len<CQT_MAX_PATH);
	strcpy(buf, path);
	strcat(buf, "block3_conv1_W_1_z.npy");
	ret = load_from_numpy(w_block3_conv1_W, buf, 294912, &nph_block3_conv1_W);
	if(ret != CQT_RET_OK){
		return ret;
	}

	fname_b_len = strlen("block3_conv1_b_1_z.npy");
	assert(path_len+fname_b_len<CQT_MAX_PATH);
	strcpy(buf, path);
	strcat(buf, "block3_conv1_b_1_z.npy");
	ret = load_from_numpy(w_block3_conv1_b, buf, 256, &nph_block3_conv1_b);
	if(ret != CQT_RET_OK){
		return ret;
	}

// block3_conv2
	path_len = strlen(path);
	fname_w_len = strlen("block3_conv2_W_1_z.npy");
	assert(path_len+fname_w_len<CQT_MAX_PATH);
	strcpy(buf, path);
	strcat(buf, "block3_conv2_W_1_z.npy");
	ret = load_from_numpy(w_block3_conv2_W, buf, 589824, &nph_block3_conv2_W);
	if(ret != CQT_RET_OK){
		return ret;
	}

	fname_b_len = strlen("block3_conv2_b_1_z.npy");
	assert(path_len+fname_b_len<CQT_MAX_PATH);
	strcpy(buf, path);
	strcat(buf, "block3_conv2_b_1_z.npy");
	ret = load_from_numpy(w_block3_conv2_b, buf, 256, &nph_block3_conv2_b);
	if(ret != CQT_RET_OK){
		return ret;
	}

// block3_conv3
	path_len = strlen(path);
	fname_w_len = strlen("block3_conv3_W_1_z.npy");
	assert(path_len+fname_w_len<CQT_MAX_PATH);
	strcpy(buf, path);
	strcat(buf, "block3_conv3_W_1_z.npy");
	ret = load_from_numpy(w_block3_conv3_W, buf, 589824, &nph_block3_conv3_W);
	if(ret != CQT_RET_OK){
		return ret;
	}

	fname_b_len = strlen("block3_conv3_b_1_z.npy");
	assert(path_len+fname_b_len<CQT_MAX_PATH);
	strcpy(buf, path);
	strcat(buf, "block3_conv3_b_1_z.npy");
	ret = load_from_numpy(w_block3_conv3_b, buf, 256, &nph_block3_conv3_b);
	if(ret != CQT_RET_OK){
		return ret;
	}

// block4_conv1
	path_len = strlen(path);
	fname_w_len = strlen("block4_conv1_W_1_z.npy");
	assert(path_len+fname_w_len<CQT_MAX_PATH);
	strcpy(buf, path);
	strcat(buf, "block4_conv1_W_1_z.npy");
	ret = load_from_numpy(w_block4_conv1_W, buf, 1179648, &nph_block4_conv1_W);
	if(ret != CQT_RET_OK){
		return ret;
	}

	fname_b_len = strlen("block4_conv1_b_1_z.npy");
	assert(path_len+fname_b_len<CQT_MAX_PATH);
	strcpy(buf, path);
	strcat(buf, "block4_conv1_b_1_z.npy");
	ret = load_from_numpy(w_block4_conv1_b, buf, 512, &nph_block4_conv1_b);
	if(ret != CQT_RET_OK){
		return ret;
	}

// block4_conv2
	path_len = strlen(path);
	fname_w_len = strlen("block4_conv2_W_1_z.npy");
	assert(path_len+fname_w_len<CQT_MAX_PATH);
	strcpy(buf, path);
	strcat(buf, "block4_conv2_W_1_z.npy");
	ret = load_from_numpy(w_block4_conv2_W, buf, 2359296, &nph_block4_conv2_W);
	if(ret != CQT_RET_OK){
		return ret;
	}

	fname_b_len = strlen("block4_conv2_b_1_z.npy");
	assert(path_len+fname_b_len<CQT_MAX_PATH);
	strcpy(buf, path);
	strcat(buf, "block4_conv2_b_1_z.npy");
	ret = load_from_numpy(w_block4_conv2_b, buf, 512, &nph_block4_conv2_b);
	if(ret != CQT_RET_OK){
		return ret;
	}

// block4_conv3
	path_len = strlen(path);
	fname_w_len = strlen("block4_conv3_W_1_z.npy");
	assert(path_len+fname_w_len<CQT_MAX_PATH);
	strcpy(buf, path);
	strcat(buf, "block4_conv3_W_1_z.npy");
	ret = load_from_numpy(w_block4_conv3_W, buf, 2359296, &nph_block4_conv3_W);
	if(ret != CQT_RET_OK){
		return ret;
	}

	fname_b_len = strlen("block4_conv3_b_1_z.npy");
	assert(path_len+fname_b_len<CQT_MAX_PATH);
	strcpy(buf, path);
	strcat(buf, "block4_conv3_b_1_z.npy");
	ret = load_from_numpy(w_block4_conv3_b, buf, 512, &nph_block4_conv3_b);
	if(ret != CQT_RET_OK){
		return ret;
	}

// block5_conv1
	path_len = strlen(path);
	fname_w_len = strlen("block5_conv1_W_1_z.npy");
	assert(path_len+fname_w_len<CQT_MAX_PATH);
	strcpy(buf, path);
	strcat(buf, "block5_conv1_W_1_z.npy");
	ret = load_from_numpy(w_block5_conv1_W, buf, 2359296, &nph_block5_conv1_W);
	if(ret != CQT_RET_OK){
		return ret;
	}

	fname_b_len = strlen("block5_conv1_b_1_z.npy");
	assert(path_len+fname_b_len<CQT_MAX_PATH);
	strcpy(buf, path);
	strcat(buf, "block5_conv1_b_1_z.npy");
	ret = load_from_numpy(w_block5_conv1_b, buf, 512, &nph_block5_conv1_b);
	if(ret != CQT_RET_OK){
		return ret;
	}

// block5_conv2
	path_len = strlen(path);
	fname_w_len = strlen("block5_conv2_W_1_z.npy");
	assert(path_len+fname_w_len<CQT_MAX_PATH);
	strcpy(buf, path);
	strcat(buf, "block5_conv2_W_1_z.npy");
	ret = load_from_numpy(w_block5_conv2_W, buf, 2359296, &nph_block5_conv2_W);
	if(ret != CQT_RET_OK){
		return ret;
	}

	fname_b_len = strlen("block5_conv2_b_1_z.npy");
	assert(path_len+fname_b_len<CQT_MAX_PATH);
	strcpy(buf, path);
	strcat(buf, "block5_conv2_b_1_z.npy");
	ret = load_from_numpy(w_block5_conv2_b, buf, 512, &nph_block5_conv2_b);
	if(ret != CQT_RET_OK){
		return ret;
	}

// block5_conv3
	path_len = strlen(path);
	fname_w_len = strlen("block5_conv3_W_1_z.npy");
	assert(path_len+fname_w_len<CQT_MAX_PATH);
	strcpy(buf, path);
	strcat(buf, "block5_conv3_W_1_z.npy");
	ret = load_from_numpy(w_block5_conv3_W, buf, 2359296, &nph_block5_conv3_W);
	if(ret != CQT_RET_OK){
		return ret;
	}

	fname_b_len = strlen("block5_conv3_b_1_z.npy");
	assert(path_len+fname_b_len<CQT_MAX_PATH);
	strcpy(buf, path);
	strcat(buf, "block5_conv3_b_1_z.npy");
	ret = load_from_numpy(w_block5_conv3_b, buf, 512, &nph_block5_conv3_b);
	if(ret != CQT_RET_OK){
		return ret;
	}

// fc1
	path_len = strlen(path);
	fname_w_len = strlen("fc1_W_1_z.npy");
	assert(path_len+fname_w_len<CQT_MAX_PATH);
	strcpy(buf, path);
	strcat(buf, "fc1_W_1_z.npy");
	ret = load_from_numpy(w_fc1_W, buf, 102760448, &nph_fc1_W);
	if(ret != CQT_RET_OK){
		return ret;
	}

	fname_b_len = strlen("fc1_b_1_z.npy");
	assert(path_len+fname_b_len<CQT_MAX_PATH);
	strcpy(buf, path);
	strcat(buf, "fc1_b_1_z.npy");
	ret = load_from_numpy(w_fc1_b, buf, 4096, &nph_fc1_b);
	if(ret != CQT_RET_OK){
		return ret;
	}

// fc2
	path_len = strlen(path);
	fname_w_len = strlen("fc2_W_1_z.npy");
	assert(path_len+fname_w_len<CQT_MAX_PATH);
	strcpy(buf, path);
	strcat(buf, "fc2_W_1_z.npy");
	ret = load_from_numpy(w_fc2_W, buf, 16777216, &nph_fc2_W);
	if(ret != CQT_RET_OK){
		return ret;
	}

	fname_b_len = strlen("fc2_b_1_z.npy");
	assert(path_len+fname_b_len<CQT_MAX_PATH);
	strcpy(buf, path);
	strcat(buf, "fc2_b_1_z.npy");
	ret = load_from_numpy(w_fc2_b, buf, 4096, &nph_fc2_b);
	if(ret != CQT_RET_OK){
		return ret;
	}

// predictions
	path_len = strlen(path);
	fname_w_len = strlen("predictions_W_1_z.npy");
	assert(path_len+fname_w_len<CQT_MAX_PATH);
	strcpy(buf, path);
	strcat(buf, "predictions_W_1_z.npy");
	ret = load_from_numpy(w_predictions_W, buf, 4096000, &nph_predictions_W);
	if(ret != CQT_RET_OK){
		return ret;
	}

	fname_b_len = strlen("predictions_b_1_z.npy");
	assert(path_len+fname_b_len<CQT_MAX_PATH);
	strcpy(buf, path);
	strcat(buf, "predictions_b_1_z.npy");
	ret = load_from_numpy(w_predictions_b, buf, 1000, &nph_predictions_b);
	if(ret != CQT_RET_OK){
		return ret;
	}

	return CQT_RET_OK;
}

int cqt_run(CQT_NET* np, void *dp) {
	int ret;

	//input_1
	cqt_process = 0;
	ret = CQT_InputLayer_if_of(&(g_cqt_vgg16.layer[0]), dp, input_1_output);
	if(ret != CQT_RET_OK){
		return ret;
	}

	//block1_conv1
	cqt_process = 1;
	ret = CQT_Conv2D_same_3x3_if_wf_wf_of(&(g_cqt_vgg16.layer[1]), input_1_output, block1_conv1_output);
	if(ret != CQT_RET_OK){
		return ret;
	}

	//block1_conv2
	cqt_process = 2;
	ret = CQT_Conv2D_same_3x3_if_wf_wf_of(&(g_cqt_vgg16.layer[2]), block1_conv1_output, block1_conv2_output);
	if(ret != CQT_RET_OK){
		return ret;
	}

	//block1_pool
	cqt_process = 3;
	ret = CQT_MaxPooling2D_if_of(&(g_cqt_vgg16.layer[3]), block1_conv2_output, block1_pool_output);
	if(ret != CQT_RET_OK){
		return ret;
	}

	//block2_conv1
	cqt_process = 4;
	ret = CQT_Conv2D_same_3x3_if_wf_wf_of(&(g_cqt_vgg16.layer[4]), block1_pool_output, block2_conv1_output);
	if(ret != CQT_RET_OK){
		return ret;
	}

	//block2_conv2
	cqt_process = 5;
	ret = CQT_Conv2D_same_3x3_if_wf_wf_of(&(g_cqt_vgg16.layer[5]), block2_conv1_output, block2_conv2_output);
	if(ret != CQT_RET_OK){
		return ret;
	}

	//block2_pool
	cqt_process = 6;
	ret = CQT_MaxPooling2D_if_of(&(g_cqt_vgg16.layer[6]), block2_conv2_output, block2_pool_output);
	if(ret != CQT_RET_OK){
		return ret;
	}

	//block3_conv1
	cqt_process = 7;
	ret = CQT_Conv2D_same_3x3_if_wf_wf_of(&(g_cqt_vgg16.layer[7]), block2_pool_output, block3_conv1_output);
	if(ret != CQT_RET_OK){
		return ret;
	}

	//block3_conv2
	cqt_process = 8;
	ret = CQT_Conv2D_same_3x3_if_wf_wf_of(&(g_cqt_vgg16.layer[8]), block3_conv1_output, block3_conv2_output);
	if(ret != CQT_RET_OK){
		return ret;
	}

	//block3_conv3
	cqt_process = 9;
	ret = CQT_Conv2D_same_3x3_if_wf_wf_of(&(g_cqt_vgg16.layer[9]), block3_conv2_output, block3_conv3_output);
	if(ret != CQT_RET_OK){
		return ret;
	}

	//block3_pool
	cqt_process = 10;
	ret = CQT_MaxPooling2D_if_of(&(g_cqt_vgg16.layer[10]), block3_conv3_output, block3_pool_output);
	if(ret != CQT_RET_OK){
		return ret;
	}

	//block4_conv1
	cqt_process = 11;
	ret = CQT_Conv2D_same_3x3_if_wf_wf_of(&(g_cqt_vgg16.layer[11]), block3_pool_output, block4_conv1_output);
	if(ret != CQT_RET_OK){
		return ret;
	}

	//block4_conv2
	cqt_process = 12;
	ret = CQT_Conv2D_same_3x3_if_wf_wf_of(&(g_cqt_vgg16.layer[12]), block4_conv1_output, block4_conv2_output);
	if(ret != CQT_RET_OK){
		return ret;
	}

	//block4_conv3
	cqt_process = 13;
	ret = CQT_Conv2D_same_3x3_if_wf_wf_of(&(g_cqt_vgg16.layer[13]), block4_conv2_output, block4_conv3_output);
	if(ret != CQT_RET_OK){
		return ret;
	}

	//block4_pool
	cqt_process = 14;
	ret = CQT_MaxPooling2D_if_of(&(g_cqt_vgg16.layer[14]), block4_conv3_output, block4_pool_output);
	if(ret != CQT_RET_OK){
		return ret;
	}

	//block5_conv1
	cqt_process = 15;
	ret = CQT_Conv2D_same_3x3_if_wf_wf_of(&(g_cqt_vgg16.layer[15]), block4_pool_output, block5_conv1_output);
	if(ret != CQT_RET_OK){
		return ret;
	}

	//block5_conv2
	cqt_process = 16;
	ret = CQT_Conv2D_same_3x3_if_wf_wf_of(&(g_cqt_vgg16.layer[16]), block5_conv1_output, block5_conv2_output);
	if(ret != CQT_RET_OK){
		return ret;
	}

	//block5_conv3
	cqt_process = 17;
	ret = CQT_Conv2D_same_3x3_if_wf_wf_of(&(g_cqt_vgg16.layer[17]), block5_conv2_output, block5_conv3_output);
	if(ret != CQT_RET_OK){
		return ret;
	}

	//block5_pool
	cqt_process = 18;
	ret = CQT_MaxPooling2D_if_of(&(g_cqt_vgg16.layer[18]), block5_conv3_output, block5_pool_output);
	if(ret != CQT_RET_OK){
		return ret;
	}

	//flatten
	cqt_process = 19;
	ret = CQT_Flatten_if_of(&(g_cqt_vgg16.layer[19]), block5_pool_output, flatten_output);
	if(ret != CQT_RET_OK){
		return ret;
	}

	//fc1
	cqt_process = 20;
	ret = CQT_Dense_if_wf_wf_of(&(g_cqt_vgg16.layer[20]), flatten_output, fc1_output);
	if(ret != CQT_RET_OK){
		return ret;
	}

	//fc2
	cqt_process = 21;
	ret = CQT_Dense_if_wf_wf_of(&(g_cqt_vgg16.layer[21]), fc1_output, fc2_output);
	if(ret != CQT_RET_OK){
		return ret;
	}

	//predictions
	cqt_process = 22;
	ret = CQT_Dense_if_wf_wf_of(&(g_cqt_vgg16.layer[22]), fc2_output, predictions_output);
	if(ret != CQT_RET_OK){
		return ret;
	}

	return CQT_RET_OK;
}

