//----------------------------------------------------------------------------------------------------
// This file is automatically generated.
// 2017/07/18 00:00:00
//----------------------------------------------------------------------------------------------------
#include "cqt_debug.h"

//outputs
extern FIXP16 input_1_output[3][224][224];
extern FIXP16 block1_conv1_output[64][224][224];
extern FIXP16 block1_conv2_output[64][224][224];
extern FIXP16 block1_pool_output[64][112][112];
extern FIXP16 block2_conv1_output[128][112][112];
extern FIXP16 block2_conv2_output[128][112][112];
extern FIXP16 block2_pool_output[128][56][56];
extern FIXP16 block3_conv1_output[256][56][56];
extern FIXP16 block3_conv2_output[256][56][56];
extern FIXP16 block3_conv3_output[256][56][56];
extern FIXP16 block3_pool_output[256][28][28];
extern FIXP16 block4_conv1_output[512][28][28];
extern FIXP16 block4_conv2_output[512][28][28];
extern FIXP16 block4_conv3_output[512][28][28];
extern FIXP16 block4_pool_output[512][14][14];
extern FIXP16 block5_conv1_output[512][14][14];
extern FIXP16 block5_conv2_output[512][14][14];
extern FIXP16 block5_conv3_output[512][14][14];
extern FIXP16 block5_pool_output[512][7][7];
extern FIXP16 flatten_output[25088];
extern FIXP16 fc1_output[4096];
extern FIXP16 fc2_output[4096];
extern FIXP16 predictions_output[1000];

extern NUMPY_HEADER np;

void cqt_layerdump(int l)
{
	switch(l) {
	case 0:
		cqt_layer0_dump();
		break;
	case 1:
		cqt_layer1_dump();
		break;
	case 2:
		cqt_layer2_dump();
		break;
	case 3:
		cqt_layer3_dump();
		break;
	case 4:
		cqt_layer4_dump();
		break;
	case 5:
		cqt_layer5_dump();
		break;
	case 6:
		cqt_layer6_dump();
		break;
	case 7:
		cqt_layer7_dump();
		break;
	case 8:
		cqt_layer8_dump();
		break;
	case 9:
		cqt_layer9_dump();
		break;
	case 10:
		cqt_layer10_dump();
		break;
	case 11:
		cqt_layer11_dump();
		break;
	case 12:
		cqt_layer12_dump();
		break;
	case 13:
		cqt_layer13_dump();
		break;
	case 14:
		cqt_layer14_dump();
		break;
	case 15:
		cqt_layer15_dump();
		break;
	case 16:
		cqt_layer16_dump();
		break;
	case 17:
		cqt_layer17_dump();
		break;
	case 18:
		cqt_layer18_dump();
		break;
	case 19:
		cqt_layer19_dump();
		break;
	case 20:
		cqt_layer20_dump();
		break;
	case 21:
		cqt_layer21_dump();
		break;
	case 22:
		cqt_layer22_dump();
		break;
	default:
		printf("ERROR:invalid layer number %d\n", l);
		exit(1);
	}
}

void cqt_layer0_dump(void)
{
	NUMPY_HEADER np_0 = np;
	int ret;

	np_0.shape[0] = 224 * 224;
	np_0.shape[1] = 0;
	np_0.shape[2] = 0;
	np_0.shape[3] = 0;

	ret = save_to_numpy(input_1_output[0], "output/l00_0.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
	ret = save_to_numpy(input_1_output[1], "output/l00_1.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
	ret = save_to_numpy(input_1_output[2], "output/l00_2.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
}

void cqt_layer1_dump(void)
{
	NUMPY_HEADER np_0 = np;
	int ret;

	np_0.shape[0] = 224 * 224;
	np_0.shape[1] = 0;
	np_0.shape[2] = 0;
	np_0.shape[3] = 0;

	ret = save_to_numpy(block1_conv1_output[0], "output/l01_0.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
	ret = save_to_numpy(block1_conv1_output[1], "output/l01_1.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
	ret = save_to_numpy(block1_conv1_output[2], "output/l01_2.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
	ret = save_to_numpy(block1_conv1_output[3], "output/l01_3.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
	ret = save_to_numpy(block1_conv1_output[4], "output/l01_4.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
	ret = save_to_numpy(block1_conv1_output[63], "output/l01_63.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
}

void cqt_layer2_dump(void)
{
	NUMPY_HEADER np_0 = np;
	int ret;

	np_0.shape[0] = 224 * 224;
	np_0.shape[1] = 0;
	np_0.shape[2] = 0;
	np_0.shape[3] = 0;

	ret = save_to_numpy(block1_conv2_output[0], "output/l02_0.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
	ret = save_to_numpy(block1_conv2_output[1], "output/l02_1.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
	ret = save_to_numpy(block1_conv2_output[2], "output/l02_2.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
	ret = save_to_numpy(block1_conv2_output[3], "output/l02_3.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
	ret = save_to_numpy(block1_conv2_output[4], "output/l02_4.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
	ret = save_to_numpy(block1_conv2_output[63], "output/l02_63.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
}

void cqt_layer3_dump(void)
{
	NUMPY_HEADER np_0 = np;
	int ret;

	np_0.shape[0] = 112 * 112;
	np_0.shape[1] = 0;
	np_0.shape[2] = 0;
	np_0.shape[3] = 0;

	ret = save_to_numpy(block1_pool_output[0], "output/l03_0.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
	ret = save_to_numpy(block1_pool_output[1], "output/l03_1.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
	ret = save_to_numpy(block1_pool_output[2], "output/l03_2.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
	ret = save_to_numpy(block1_pool_output[3], "output/l03_3.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
	ret = save_to_numpy(block1_pool_output[4], "output/l03_4.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
	ret = save_to_numpy(block1_pool_output[63], "output/l03_63.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
}

void cqt_layer4_dump(void)
{
	NUMPY_HEADER np_0 = np;
	int ret;

	np_0.shape[0] = 112 * 112;
	np_0.shape[1] = 0;
	np_0.shape[2] = 0;
	np_0.shape[3] = 0;

	ret = save_to_numpy(block2_conv1_output[0], "output/l04_0.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
	ret = save_to_numpy(block2_conv1_output[1], "output/l04_1.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
	ret = save_to_numpy(block2_conv1_output[2], "output/l04_2.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
	ret = save_to_numpy(block2_conv1_output[3], "output/l04_3.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
	ret = save_to_numpy(block2_conv1_output[4], "output/l04_4.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
	ret = save_to_numpy(block2_conv1_output[127], "output/l04_127.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
}

void cqt_layer5_dump(void)
{
	NUMPY_HEADER np_0 = np;
	int ret;

	np_0.shape[0] = 112 * 112;
	np_0.shape[1] = 0;
	np_0.shape[2] = 0;
	np_0.shape[3] = 0;

	ret = save_to_numpy(block2_conv2_output[0], "output/l05_0.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
	ret = save_to_numpy(block2_conv2_output[1], "output/l05_1.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
	ret = save_to_numpy(block2_conv2_output[2], "output/l05_2.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
	ret = save_to_numpy(block2_conv2_output[3], "output/l05_3.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
	ret = save_to_numpy(block2_conv2_output[4], "output/l05_4.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
	ret = save_to_numpy(block2_conv2_output[127], "output/l05_127.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
}

void cqt_layer6_dump(void)
{
	NUMPY_HEADER np_0 = np;
	int ret;

	np_0.shape[0] = 56 * 56;
	np_0.shape[1] = 0;
	np_0.shape[2] = 0;
	np_0.shape[3] = 0;

	ret = save_to_numpy(block2_pool_output[0], "output/l06_0.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
	ret = save_to_numpy(block2_pool_output[1], "output/l06_1.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
	ret = save_to_numpy(block2_pool_output[2], "output/l06_2.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
	ret = save_to_numpy(block2_pool_output[3], "output/l06_3.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
	ret = save_to_numpy(block2_pool_output[4], "output/l06_4.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
	ret = save_to_numpy(block2_pool_output[127], "output/l06_127.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
}

void cqt_layer7_dump(void)
{
	NUMPY_HEADER np_0 = np;
	int ret;

	np_0.shape[0] = 56 * 56;
	np_0.shape[1] = 0;
	np_0.shape[2] = 0;
	np_0.shape[3] = 0;

	ret = save_to_numpy(block3_conv1_output[0], "output/l07_0.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
	ret = save_to_numpy(block3_conv1_output[1], "output/l07_1.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
	ret = save_to_numpy(block3_conv1_output[2], "output/l07_2.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
	ret = save_to_numpy(block3_conv1_output[3], "output/l07_3.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
	ret = save_to_numpy(block3_conv1_output[4], "output/l07_4.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
	ret = save_to_numpy(block3_conv1_output[255], "output/l07_255.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
}

void cqt_layer8_dump(void)
{
	NUMPY_HEADER np_0 = np;
	int ret;

	np_0.shape[0] = 56 * 56;
	np_0.shape[1] = 0;
	np_0.shape[2] = 0;
	np_0.shape[3] = 0;

	ret = save_to_numpy(block3_conv2_output[0], "output/l08_0.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
	ret = save_to_numpy(block3_conv2_output[1], "output/l08_1.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
	ret = save_to_numpy(block3_conv2_output[2], "output/l08_2.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
	ret = save_to_numpy(block3_conv2_output[3], "output/l08_3.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
	ret = save_to_numpy(block3_conv2_output[4], "output/l08_4.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
	ret = save_to_numpy(block3_conv2_output[255], "output/l08_255.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
}

void cqt_layer9_dump(void)
{
	NUMPY_HEADER np_0 = np;
	int ret;

	np_0.shape[0] = 56 * 56;
	np_0.shape[1] = 0;
	np_0.shape[2] = 0;
	np_0.shape[3] = 0;

	ret = save_to_numpy(block3_conv3_output[0], "output/l09_0.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
	ret = save_to_numpy(block3_conv3_output[1], "output/l09_1.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
	ret = save_to_numpy(block3_conv3_output[2], "output/l09_2.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
	ret = save_to_numpy(block3_conv3_output[3], "output/l09_3.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
	ret = save_to_numpy(block3_conv3_output[4], "output/l09_4.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
	ret = save_to_numpy(block3_conv3_output[255], "output/l09_255.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
}

void cqt_layer10_dump(void)
{
	NUMPY_HEADER np_0 = np;
	int ret;

	np_0.shape[0] = 28 * 28;
	np_0.shape[1] = 0;
	np_0.shape[2] = 0;
	np_0.shape[3] = 0;

	ret = save_to_numpy(block3_pool_output[0], "output/l10_0.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
	ret = save_to_numpy(block3_pool_output[1], "output/l10_1.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
	ret = save_to_numpy(block3_pool_output[2], "output/l10_2.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
	ret = save_to_numpy(block3_pool_output[3], "output/l10_3.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
	ret = save_to_numpy(block3_pool_output[4], "output/l10_4.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
	ret = save_to_numpy(block3_pool_output[255], "output/l10_255.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
}

void cqt_layer11_dump(void)
{
	NUMPY_HEADER np_0 = np;
	int ret;

	np_0.shape[0] = 28 * 28;
	np_0.shape[1] = 0;
	np_0.shape[2] = 0;
	np_0.shape[3] = 0;

	ret = save_to_numpy(block4_conv1_output[0], "output/l11_0.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
	ret = save_to_numpy(block4_conv1_output[1], "output/l11_1.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
	ret = save_to_numpy(block4_conv1_output[2], "output/l11_2.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
	ret = save_to_numpy(block4_conv1_output[3], "output/l11_3.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
	ret = save_to_numpy(block4_conv1_output[4], "output/l11_4.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
	ret = save_to_numpy(block4_conv1_output[511], "output/l11_511.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
}

void cqt_layer12_dump(void)
{
	NUMPY_HEADER np_0 = np;
	int ret;

	np_0.shape[0] = 28 * 28;
	np_0.shape[1] = 0;
	np_0.shape[2] = 0;
	np_0.shape[3] = 0;

	ret = save_to_numpy(block4_conv2_output[0], "output/l12_0.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
	ret = save_to_numpy(block4_conv2_output[1], "output/l12_1.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
	ret = save_to_numpy(block4_conv2_output[2], "output/l12_2.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
	ret = save_to_numpy(block4_conv2_output[3], "output/l12_3.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
	ret = save_to_numpy(block4_conv2_output[4], "output/l12_4.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
	ret = save_to_numpy(block4_conv2_output[511], "output/l12_511.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
}

void cqt_layer13_dump(void)
{
	NUMPY_HEADER np_0 = np;
	int ret;

	np_0.shape[0] = 28 * 28;
	np_0.shape[1] = 0;
	np_0.shape[2] = 0;
	np_0.shape[3] = 0;

	ret = save_to_numpy(block4_conv3_output[0], "output/l13_0.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
	ret = save_to_numpy(block4_conv3_output[1], "output/l13_1.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
	ret = save_to_numpy(block4_conv3_output[2], "output/l13_2.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
	ret = save_to_numpy(block4_conv3_output[3], "output/l13_3.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
	ret = save_to_numpy(block4_conv3_output[4], "output/l13_4.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
	ret = save_to_numpy(block4_conv3_output[511], "output/l13_511.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
}

void cqt_layer14_dump(void)
{
	NUMPY_HEADER np_0 = np;
	int ret;

	np_0.shape[0] = 14 * 14;
	np_0.shape[1] = 0;
	np_0.shape[2] = 0;
	np_0.shape[3] = 0;

	ret = save_to_numpy(block4_pool_output[0], "output/l14_0.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
	ret = save_to_numpy(block4_pool_output[1], "output/l14_1.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
	ret = save_to_numpy(block4_pool_output[2], "output/l14_2.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
	ret = save_to_numpy(block4_pool_output[3], "output/l14_3.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
	ret = save_to_numpy(block4_pool_output[4], "output/l14_4.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
	ret = save_to_numpy(block4_pool_output[511], "output/l14_511.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
}

void cqt_layer15_dump(void)
{
	NUMPY_HEADER np_0 = np;
	int ret;

	np_0.shape[0] = 14 * 14;
	np_0.shape[1] = 0;
	np_0.shape[2] = 0;
	np_0.shape[3] = 0;

	ret = save_to_numpy(block5_conv1_output[0], "output/l15_0.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
	ret = save_to_numpy(block5_conv1_output[1], "output/l15_1.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
	ret = save_to_numpy(block5_conv1_output[2], "output/l15_2.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
	ret = save_to_numpy(block5_conv1_output[3], "output/l15_3.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
	ret = save_to_numpy(block5_conv1_output[4], "output/l15_4.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
	ret = save_to_numpy(block5_conv1_output[511], "output/l15_511.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
}

void cqt_layer16_dump(void)
{
	NUMPY_HEADER np_0 = np;
	int ret;

	np_0.shape[0] = 14 * 14;
	np_0.shape[1] = 0;
	np_0.shape[2] = 0;
	np_0.shape[3] = 0;

	ret = save_to_numpy(block5_conv2_output[0], "output/l16_0.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
	ret = save_to_numpy(block5_conv2_output[1], "output/l16_1.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
	ret = save_to_numpy(block5_conv2_output[2], "output/l16_2.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
	ret = save_to_numpy(block5_conv2_output[3], "output/l16_3.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
	ret = save_to_numpy(block5_conv2_output[4], "output/l16_4.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
	ret = save_to_numpy(block5_conv2_output[511], "output/l16_511.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
}

void cqt_layer17_dump(void)
{
	NUMPY_HEADER np_0 = np;
	int ret;

	np_0.shape[0] = 14 * 14;
	np_0.shape[1] = 0;
	np_0.shape[2] = 0;
	np_0.shape[3] = 0;

	ret = save_to_numpy(block5_conv3_output[0], "output/l17_0.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
	ret = save_to_numpy(block5_conv3_output[1], "output/l17_1.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
	ret = save_to_numpy(block5_conv3_output[2], "output/l17_2.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
	ret = save_to_numpy(block5_conv3_output[3], "output/l17_3.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
	ret = save_to_numpy(block5_conv3_output[4], "output/l17_4.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
	ret = save_to_numpy(block5_conv3_output[511], "output/l17_511.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
}

void cqt_layer18_dump(void)
{
	NUMPY_HEADER np_0 = np;
	int ret;

	np_0.shape[0] = 7 * 7;
	np_0.shape[1] = 0;
	np_0.shape[2] = 0;
	np_0.shape[3] = 0;

	ret = save_to_numpy(block5_pool_output[0], "output/l18_0.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
	ret = save_to_numpy(block5_pool_output[1], "output/l18_1.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
	ret = save_to_numpy(block5_pool_output[2], "output/l18_2.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
	ret = save_to_numpy(block5_pool_output[3], "output/l18_3.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
	ret = save_to_numpy(block5_pool_output[4], "output/l18_4.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
	ret = save_to_numpy(block5_pool_output[511], "output/l18_511.npy", & np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
}

void cqt_layer19_dump(void)
{
	NUMPY_HEADER np_0 = np;
	int ret;

	np_0.shape[0] = 25088;
	np_0.shape[1] = 0;
	np_0.shape[2] = 0;
	np_0.shape[3] = 0;

	ret = save_to_numpy((void *)flatten_output, "output/l19_0.npy", &np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
}

void cqt_layer20_dump(void)
{
	NUMPY_HEADER np_0 = np;
	int ret;

	np_0.shape[0] = 4096;
	np_0.shape[1] = 0;
	np_0.shape[2] = 0;
	np_0.shape[3] = 0;

	ret = save_to_numpy((void *)fc1_output, "output/l20_0.npy", &np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
}

void cqt_layer21_dump(void)
{
	NUMPY_HEADER np_0 = np;
	int ret;

	np_0.shape[0] = 4096;
	np_0.shape[1] = 0;
	np_0.shape[2] = 0;
	np_0.shape[3] = 0;

	ret = save_to_numpy((void *)fc2_output, "output/l21_0.npy", &np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
}

void cqt_layer22_dump(void)
{
	NUMPY_HEADER np_0 = np;
	int ret;

	np_0.shape[0] = 1000;
	np_0.shape[1] = 0;
	np_0.shape[2] = 0;
	np_0.shape[3] = 0;

	ret = save_to_numpy((void *)predictions_output, "output/l22_0.npy", &np_0);
	if (ret != CQT_RET_OK) {
		printf("ERROR in layer0_output %d\n", ret);
	}
}


